Repository kyma-incubator/reconciler, pull requests merged in 2021-09, with the labels that each got.

#124 Fix bug caused by missing encryption-key during ms-reconciler startup
  Makefile
  cmd/mothership/install/cmd.go
  cmd/mothership/start/cmd.go
  internal/cli/encryptionkey.go
  resources/reconciler/charts/mothership-reconciler/templates/deployment.yaml
  resources/reconciler/charts/mothership-reconciler/templates/mr-configmap.yaml
  resources/reconciler/values.yaml
  scripts/kcversion.sh
Labels: size/M, lgtm

#123 Test rendering of all Kyma components
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/service/test.go
  pkg/reconciler/test/test.go
  pkg/test/componentlist.go
Labels: lgtm, size/L

#120 Improve local scheduler API
  cmd/local/cmd.go
  go.mod
  pkg/scheduler/inventorywatch.go
  pkg/scheduler/localscheduler.go
  pkg/scheduler/localscheduler_test.go
  pkg/scheduler/remotescheduler.go
  pkg/scheduler/remotescheduler_test.go
Labels: lgtm, size/L

#128 Reconciler int tests
  Makefile
  cmd/e2e/cluster_inventory_test.go
  cmd/e2e/request/correct_simple_request.json
  cmd/local/cmd.go
  cmd/local/options.go
  cmd/mothership/start/cmd.go
  cmd/mothership/start/cmd_test.go
  cmd/mothership/start/http.go
  cmd/mothership/start/scheduler.go
  cmd/mothership/start/test/component-reconcilers.json
  cmd/mothership/start/test/request/create_cluster.json
  cmd/mothership/start/test/request/create_cluster_invalid_kubeconfig.json
  configs/reconciler-unittest.yaml
  configs/reconciler.yaml
  internal/cli/context.go
  internal/cli/test.go
  internal/components/componentlist.go
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/cluster/statusfilter.go
  pkg/keb/http.go
  pkg/model/clusterstatus.go
  pkg/model/clusterstatusentity.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/http.go
  pkg/reconciler/instances/e2etest/action.go
  pkg/reconciler/instances/e2etest/e2etest.go
  pkg/reconciler/instances/loader.go
  pkg/reconciler/model.go
  pkg/reconciler/service/interceptor.go
  pkg/reconciler/service/interceptor_test.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/scheduler/config.go
  pkg/scheduler/invoker.go
  pkg/scheduler/localinvoker.go
  pkg/scheduler/localscheduler.go
  pkg/scheduler/localscheduler_test.go
  pkg/scheduler/remoteinvoker.go
  pkg/scheduler/remotescheduler.go
  pkg/scheduler/remotescheduler_test.go
  pkg/scheduler/worker.go
  pkg/scheduler/workerfactory.go
  resources/reconciler/charts/mothership-reconciler/templates/mr-configmap.yaml
  resources/reconciler/charts/mothership-reconciler/values.yaml
Labels: size/XXL, lgtm

#134 Downgraded spf13/cobra
  go.mod
  go.sum
Labels: lgtm, size/XS

#119 Introduce Istio installation for Reconciler
  Dockerfile
  pkg/reconciler/file/path.go
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/kubernetes/adapter/adapter.go
  pkg/reconciler/kubernetes/client.go
  pkg/reconciler/kubernetes/kubeclient/kubeclient.go
  pkg/reconciler/kubernetes/mocks/Client.go
Labels: lgtm, size/L

#106 Review cluster-status updates
  cmd/mothership/start/http.go
  cmd/reconciler/cmd.go
  internal/cli/reconciler/options.go
  internal/cli/reconciler/start.go
  pkg/reconciler/heartbeat/heartbeat.go
  pkg/reconciler/heartbeat/heartbeat_test.go
  pkg/reconciler/model.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/reconciler_test.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/scheduler/inventorywatch.go
  pkg/scheduler/localinvoker.go
  pkg/scheduler/mock_inventorywatch.go
  pkg/scheduler/mock_operations.go
  pkg/scheduler/remotescheduler.go
  pkg/scheduler/remotescheduler_test.go
  pkg/scheduler/statusupdater.go
  pkg/scheduler/worker.go
  resources/reconciler/values.yaml
Labels: lgtm, size/L

#132 Reconciler int tests
  .gitignore
  Makefile
  cmd/mothership/start/cmd.go
  cmd/mothership/start/cmd_test.go
  cmd/mothership/start/http.go
  cmd/mothership/start/test/requests/callback.json
  cmd/mothership/start/test/requests/create_cluster.json
  cmd/mothership/start/test/requests/create_cluster_invalid_kubeconfig.json
  cmd/mothership/start/test/requests/empty.json
  cmd/mothership/start/test/requests/invalid.json
  pkg/app/registry.go
  pkg/cluster/clusterfilter.go
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/cluster/statuschange.go
  pkg/db/postgres.go
  pkg/keb/http.go
  pkg/kubernetes/clientbuilder.go
  pkg/reconciler/kubernetes/progress/progress_test.go
  pkg/reconciler/service/runner.go
  pkg/repository/repository.go
  pkg/scheduler/operations.go
  pkg/scheduler/remotescheduler.go
  pkg/server/params.go
  resources/reconciler/values.yaml
  scripts/bumpimage.sh
Labels: size/XL, lgtm

#135 Persisted operations impl
  cmd/local/cmd.go
  configs/db/postgres/000002_scheduler_operations.down.sql
  configs/db/postgres/000002_scheduler_operations.up.sql
  configs/db/sqlite/reconciler.sql
  pkg/app/registry.go
  pkg/model/operationentity.go
  pkg/model/operationstate.go
  pkg/scheduler/localscheduler_test.go
  pkg/scheduler/mock_operations.go
  pkg/scheduler/operations.go
  pkg/scheduler/remotescheduler.go
  pkg/scheduler/statusupdater.go
  pkg/scheduler/worker.go
Labels: lgtm, size/L

#114 Add e2e test job
  Makefile
  scripts/e2e-test/reconcile-kyma.sh
  scripts/e2e-test/template.json
Labels: lgtm, size/L

#130 Update README.md
  README.md
Labels: lgtm, size/S

#142 Fix vulnerabilities
  Dockerfile
  go.mod
  go.sum
  pkg/scheduler/remotescheduler.go
  resources/reconciler/values.yaml
Labels: lgtm, size/S

#145 Add wookiee team to cmd CODEOWNES
  CODEOWNERS
Labels: lgtm, size/XS

#146 Cli compatibility
  cmd/local/cmd.go
  cmd/mothership/start/cmd_test.go
  cmd/mothership/start/http.go
  pkg/reconciler/callback/callback.go
  pkg/reconciler/callback/callback_test.go
  pkg/reconciler/callback/local.go
  pkg/reconciler/callback/remote.go
  pkg/reconciler/heartbeat/heartbeat.go
  pkg/reconciler/heartbeat/heartbeat_test.go
  pkg/reconciler/instances/rafter/test_files/0.0.0/installation/resources/crds/.gitignore
  pkg/reconciler/instances/rafter/test_files/0.0.1/installation/resources/crds/.gitignore
  pkg/reconciler/model.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/workspace/factory.go
  pkg/reconciler/workspace/factory_test.go
  pkg/reconciler/workspace/test/.gitignore
  pkg/reconciler/workspace/test/local/installation/resources/crds/.gitignore
  pkg/reconciler/workspace/test/local/resources/.gitignore
  pkg/reconciler/workspace/workspace.go
  pkg/scheduler/localinvoker.go
  pkg/scheduler/localscheduler_test.go
Labels: lgtm, size/L

#144 Fix scaffolding script
  Makefile
  pkg/reconciler/instances/busolamigrator/busola.go
  pkg/reconciler/instances/example/example.go
  pkg/reconciler/instances/reconcilerctl.sh
  resources/reconciler/values.yaml
  scripts/reconcilernames.go
Labels: bug, size/M, lgtm

#148 Cli compatibility
  cmd/mothership/start/test/requests/create_cluster.json
  pkg/cluster/test/cluster.json
  pkg/keb/contract.go
  pkg/reconciler/chart/helm_test.go
  pkg/reconciler/chart/test/unittest-kyma/resources/component-1/templates/configmap.yaml
  pkg/reconciler/chart/test/unittest-kyma/resources/component-1/values.yaml
  pkg/reconciler/model.go
Labels: size/M, lgtm

#152 Change wookiee team project permissions
  CODEOWNERS
Labels: lgtm, size/XS

#153 Change the scheduling order (CRD components -> prerequisites -> others)
  pkg/scheduler/localscheduler.go
  pkg/scheduler/localscheduler_test.go
Labels: lgtm, size/S

#154 Fix rafter deployment issue
  pkg/reconciler/instances/rafter/action.go
Labels: lgtm, size/XS

#155 Simplify local scheduler API
  cmd/local/cmd.go
  pkg/scheduler/invoker.go
  pkg/scheduler/localinvoker.go
  pkg/scheduler/localscheduler.go
  pkg/scheduler/localscheduler_test.go
  pkg/scheduler/mock_invoker.go
  pkg/scheduler/remoteinvoker.go
  pkg/scheduler/worker.go
  pkg/scheduler/workerfactory.go
Labels: lgtm, size/L

#157 Improve Istio Reconciler Installation scenario
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/actions/actions.go
  pkg/reconciler/instances/istio/actions/actions_test.go
  pkg/reconciler/instances/istio/actions/mocks/IstioPerformer.go
  pkg/reconciler/instances/istio/istioctl/commander.go
  pkg/reconciler/instances/istio/istioctl/mocks/Commander.go
Labels: size/XL, lgtm

#161 Convert string values from CLI with strvals
  cmd/local/options.go
  go.mod
Labels: lgtm, size/S

#159 Overwrite namespaces only if not set
  pkg/reconciler/kubernetes/kubeclient/kubeclient.go
Labels: lgtm, size/S

#156 Refactoring: create component-reconciler http-endpoint in CLI
  cmd/local/cmd.go
  cmd/local/options.go
  cmd/mothership/start/http.go
  cmd/mothership/start/integration_test.go
  cmd/reconciler/cmd.go
  cmd/reconciler/start/service/cmd.go
  cmd/reconciler/start/service/http.go
  cmd/reconciler/start/service/integration_test.go
  cmd/reconciler/start/service/reconciler.go
  cmd/reconciler/start/service/test/0.0.0/installation/resources/crds/component-1/crd.yaml
  cmd/reconciler/start/service/test/0.0.0/resources/component-1/Chart.yaml
  cmd/reconciler/start/service/test/0.0.0/resources/component-1/templates/pod.yaml
  cmd/reconciler/start/service/test/0.0.0/resources/component-1/values.yaml
  cmd/reconciler/start/service/test/0.0.0/success.yaml
  cmd/reconciler/test/service/cmd.go
  internal/cli/formatter_test.go
  internal/cli/reconciler/server.go
  internal/cli/reconciler/start.go
  internal/cli/test.go
  internal/cli/test/formatter/json.txt
  internal/cli/test/formatter/json_pretty.txt
  internal/cli/test/formatter/table.txt
  internal/cli/test/formatter/yaml.txt
  internal/cli/test/test.go
  pkg/db/factory.go
  pkg/db/marshaller.go
  pkg/db/testfactory.go
  pkg/reconciler/callback/remote.go
  pkg/reconciler/http.go
  pkg/reconciler/instances/e2etest/action.go
  pkg/reconciler/instances/e2etest/e2etest.go
  pkg/reconciler/instances/loader.go
  pkg/reconciler/model.go
  pkg/reconciler/service/action.go
  pkg/reconciler/service/dependencies.go
  pkg/reconciler/service/dependencies_test.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/reconciler_test.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/service/test.go
  pkg/reconciler/service/workerpool.go
  pkg/reconciler/service/workerpool_test.go
  pkg/server/error.go
Labels: size/XXL, lgtm

#143 Update e2e reconciler test
  scripts/e2e-test/template.json
Labels: size/M, lgtm

#164 Rename keb.components to keb.component
  README.md
  cmd/local/options.go
  pkg/keb/contract.go
  pkg/keb/factory.go
  pkg/model/clusterconfigentity.go
  pkg/reconciler/kubernetes/adapter/test/unittest-with-namespace.yaml
  pkg/scheduler/invoker.go
  pkg/scheduler/localscheduler.go
  pkg/scheduler/localscheduler_test.go
  pkg/scheduler/mock_worker.go
  pkg/scheduler/remotescheduler.go
  pkg/scheduler/remotescheduler_test.go
  pkg/scheduler/statusupdater.go
  pkg/scheduler/worker.go
Labels: lgtm, size/L

#160 Validate SQL queries
  configs/reconciler.yaml
  pkg/cluster/inventory.go
  pkg/db/factory.go
  pkg/db/interface.go
  pkg/db/marshaller.go
  pkg/db/mocks.go
  pkg/db/postgres.go
  pkg/db/query.go
  pkg/db/sqlite.go
  pkg/db/validator.go
  pkg/db/validator_test.go
  pkg/model/clusterconfigentity.go
Labels: lgtm, size/L

#165 Bump image version
  resources/reconciler/values.yaml
Labels: lgtm, size/XS

#162 Fix parsing overlapping nested values
  cmd/local/local_test.go
  cmd/local/options.go
Labels: size/M, lgtm

#163 Comprecon int test
  cmd/mothership/start/http.go
  cmd/reconciler/start/service/integration_test.go
  cmd/reconciler/start/service/test/0.0.0/resources/component-1/templates/pod.yaml
  cmd/reconciler/start/service/test/0.0.0/resources/component-1/values.yaml
  pkg/reconciler/heartbeat/heartbeat.go
  pkg/reconciler/heartbeat/heartbeat_test.go
  pkg/reconciler/model.go
  pkg/reconciler/service/runner.go
  pkg/scheduler/localinvoker.go
  resources/reconciler/values.yaml
  scripts/bumpimage.sh
Labels: lgtm, size/L

#169 Set InstallCRD flag the first scheduled component automatically
  pkg/scheduler/localscheduler.go
  pkg/scheduler/localscheduler_test.go
Labels: lgtm, size/L

#167 Extend component reconciler integration tests
  cmd/local/cmd.go
  cmd/mothership/start/integration_test.go
  cmd/reconciler/start/service/integration_test.go
  cmd/reconciler/start/service/test/kubeconfig-unreachable.yaml
  internal/cli/context.go
  internal/cli/options.go
  internal/cli/reconciler/start.go
  pkg/app/registry.go
  pkg/cache/repository.go
  pkg/cluster/statusfilter.go
  pkg/db/postgres.go
  pkg/db/sqlite.go
  pkg/db/validator_test.go
  pkg/logger/zap.go
  pkg/model/converter.go
  pkg/reconciler/callback/callback_test.go
  pkg/reconciler/chart/helm_test.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/heartbeat/heartbeat_test.go
  pkg/reconciler/instances/base/base.go
  pkg/reconciler/instances/busolamigrator/busola.go
  pkg/reconciler/instances/example/example.go
  pkg/reconciler/instances/istio/actions/actions_test.go
  pkg/reconciler/instances/istio/actions/mocks/performer.go
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/instances/rafter/action_test.go
  pkg/reconciler/instances/rafter/rafter.go
  pkg/reconciler/kubernetes/adapter/adapter_test.go
  pkg/reconciler/kubernetes/mocks/client.go
  pkg/reconciler/kubernetes/progress/progress_test.go
  pkg/reconciler/model.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/reconciler_test.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/service/workerpool.go
  pkg/reconciler/service/workerpool_test.go
  pkg/reconciler/workspace/factory_test.go
  pkg/repository/cachedep.go
  pkg/repository/cachedep_test.go
  pkg/repository/repository.go
  pkg/scheduler/inventorywatch.go
  pkg/scheduler/localinvoker.go
  pkg/scheduler/localscheduler_test.go
  pkg/scheduler/remotescheduler.go
  pkg/scheduler/remotescheduler_test.go
  pkg/scheduler/worker.go
  pkg/scheduler/workerfactory.go
Labels: size/XL, lgtm

#176 Incorrect StatusURL in response
  cmd/mothership/start/http.go
Labels: lgtm, size/XS

#177 Separate CRD installation from components
  cmd/mothership/start/scheduler.go
  cmd/reconciler/start/service/integration_test.go
  cmd/reconciler/test/service/cmd.go
  cmd/reconciler/test/service/options.go
  configs/reconciler.yaml
  pkg/cluster/inventory_test.go
  pkg/model/clusterconfigentity.go
  pkg/reconciler/model.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/scheduler/config.go
  pkg/scheduler/handler.go
  pkg/scheduler/invoker.go
  pkg/scheduler/localinvoker.go
  pkg/scheduler/localscheduler.go
  pkg/scheduler/localscheduler_test.go
  pkg/scheduler/mock_worker.go
  pkg/scheduler/remoteinvoker.go
  pkg/scheduler/remotescheduler.go
  pkg/scheduler/remotescheduler_test.go
  pkg/scheduler/statusupdater.go
  pkg/scheduler/worker.go
  resources/reconciler/charts/mothership-reconciler/templates/mr-configmap.yaml
  resources/reconciler/charts/mothership-reconciler/values.yaml
  resources/reconciler/values.yaml
Labels: lgtm, size/L

#182 Use configured hostname for cluster-status URL
  cmd/mothership/start/http.go
  cmd/mothership/start/integration_test.go
  configs/reconciler-unittest.yaml
  internal/cli/test/test.go
  pkg/db/testfactory.go
  pkg/test/config.go
Labels: bug, size/M, lgtm

#184 Add cmd flag to execute up migrations
  cmd/mothership/start/cmd.go
  cmd/mothership/start/options.go
  configs/reconciler.yaml
  go.mod
  go.sum
  internal/cli/options.go
  pkg/db/factory.go
  pkg/db/interface.go
  pkg/db/mocks.go
  pkg/db/postgres.go
  pkg/db/sqlite.go
  pkg/db/testfactory.go
Labels: lgtm, size/L

#183 Add prerequisites from default component list
  README.md
  cmd/local/options.go
Labels: size/M, lgtm

#185 Bump image version and delete out.txt
  .gitignore
  out.txt
  resources/reconciler/values.yaml
Labels: size/XXL, lgtm

#147 Ory installation for Reconciler
  go.mod
  go.sum
  pkg/reconciler/chart/helm.go
  pkg/reconciler/chart/helm_test.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/ory/action_test.go
  pkg/reconciler/instances/ory/db/db.go
  pkg/reconciler/instances/ory/db/model.go
  pkg/reconciler/instances/ory/jwks/jwks.go
  pkg/reconciler/instances/ory/jwks/jwks_test.go
  pkg/reconciler/instances/ory/ory.go
  pkg/reconciler/instances/ory/test/resources/test-ory/Chart.yaml
  pkg/reconciler/instances/ory/test/resources/test-ory/profile.yaml
  pkg/reconciler/instances/ory/test/resources/test-ory/values.yaml
Labels: size/XL, lgtm

#186 bump Istio 1.11.1 -> 1.11.2
  Dockerfile
Labels: lgtm, size/XS

#181 Kyma version as label and disclaimer-warning as annotation
  pkg/reconciler/service/annotationsinterceptor.go
  pkg/reconciler/service/annotationsinterceptor_test.go
  pkg/reconciler/service/labelsinterceptor.go
  pkg/reconciler/service/labelsinterceptor_test.go
  pkg/reconciler/service/runner.go
Labels: lgtm, size/L

#125 Private Registries Support
  cmd/local/cmd.go
  cmd/reconciler/start/service/integration_test.go
  pkg/keb/contract.go
  pkg/reconciler/chart/component.go
  pkg/reconciler/chart/component_test.go
  pkg/reconciler/chart/helm_test.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/git/client.go
  pkg/reconciler/git/client_test.go
  pkg/reconciler/git/clone.go
  pkg/reconciler/git/clone_test.go
  pkg/reconciler/git/mocks/repo_client.go
  pkg/reconciler/instances/busolamigrator/action.go
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
  pkg/reconciler/instances/connectivityproxy/connectivityproxy.go
  pkg/reconciler/instances/connectivityproxy/connectivityproxy_test.go
  pkg/reconciler/instances/connectivityproxy/fromsecret.go
  pkg/reconciler/instances/connectivityproxy/fromsecret_test.go
  pkg/reconciler/instances/connectivityproxy/fromurl.go
  pkg/reconciler/instances/connectivityproxy/fromurl_test.go
  pkg/reconciler/instances/connectivityproxy/secretcopy.go
  pkg/reconciler/instances/connectivityproxy/secretcopy_test.go
  pkg/reconciler/instances/example/action.go
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/rafter/action.go
  pkg/reconciler/instances/rafter/action_test.go
  pkg/reconciler/kubernetes/kubeclient/kubeclient.go
  pkg/reconciler/kubernetes/kubeclient/unstructured.go
  pkg/reconciler/kubernetes/kubeclient/unstructured_test.go
  pkg/reconciler/model.go
  pkg/reconciler/service/action.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/reconciler_test.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/service/test.go
  pkg/reconciler/test/test.go
  pkg/reconciler/workspace/factory.go
  pkg/reconciler/workspace/factory_test.go
  pkg/scheduler/invoker.go
  pkg/scheduler/localinvoker.go
  pkg/scheduler/localscheduler_test.go
  pkg/scheduler/remoteinvoker.go
  pkg/scheduler/worker.go
  pkg/scheduler/worker_test.go
  resources/reconciler/charts/component-reconcilers/templates/deployment.yaml
  resources/reconciler/charts/component-reconcilers/templates/rbac.yaml
Labels: size/XXL, lgtm

#192 Log http errors
  pkg/server/error.go
Labels: lgtm, size/S

#195 Fix reconciler model for unmarshal error
  pkg/reconciler/model.go
  pkg/reconciler/service/runner.go
  pkg/scheduler/invoker.go
Labels: lgtm, size/XS

#196 Add compiler flags to reduce binary size
  Dockerfile
  Makefile
Labels: lgtm, size/XS

#198 Conditional docker-push Command
  Makefile
Labels: lgtm, size/XS

#197 Separate mothership and component reconciler binaries
  Dockerfile.cr
  Dockerfile.mr
  Makefile
  README.md
  cmd/README.md
  cmd/mothership/config/cmd.go
  cmd/mothership/config/create/cmd.go
  cmd/mothership/config/create/key/cmd.go
  cmd/mothership/config/create/key/options.go
  cmd/mothership/config/create/value/cmd.go
  cmd/mothership/config/create/value/options.go
  cmd/mothership/config/get/bucket/cmd.go
  cmd/mothership/config/get/cmd.go
  cmd/mothership/config/get/key/cmd.go
  cmd/mothership/config/get/key/keyprocessor.go
  cmd/mothership/config/get/key/options.go
  cmd/mothership/config/get/value/cmd.go
  cmd/mothership/config/get/value/options.go
  cmd/mothership/config/get/value/valueprocessor.go
  cmd/mothership/local/cmd.go
  cmd/mothership/local/local_test.go
  cmd/mothership/local/options.go
  cmd/mothership/main.go
  cmd/mothership/mothership/cmd.go
  cmd/mothership/mothership/install/cmd.go
  cmd/mothership/mothership/install/options.go
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/integration_test.go
  cmd/mothership/mothership/start/options.go
  cmd/mothership/mothership/start/scheduler.go
  cmd/mothership/mothership/start/test/component-reconcilers.json
  cmd/mothership/mothership/start/test/requests/callback.json
  cmd/mothership/mothership/start/test/requests/create_cluster.json
  cmd/mothership/mothership/start/test/requests/create_cluster_invalid_kubeconfig.json
  cmd/mothership/mothership/start/test/requests/empty.json
  cmd/mothership/mothership/start/test/requests/invalid.json
  cmd/reconciler/main.go
  configs/reconciler.yaml
  internal/README.md
  pkg/README.md
  resources/reconciler/charts/component-reconcilers/templates/deployment.yaml
  resources/reconciler/charts/mothership-reconciler/templates/deployment.yaml
  resources/reconciler/values.yaml
Labels: lgtm, size/L

#174 Propagate context properly
  pkg/reconciler/service/runner.go
  pkg/scheduler/handler.go
  pkg/scheduler/invoker.go
  pkg/scheduler/localinvoker.go
  pkg/scheduler/localscheduler_test.go
  pkg/scheduler/mock_worker.go
  pkg/scheduler/remoteinvoker.go
  pkg/scheduler/worker.go
Labels: bug, size/M, lgtm, area/lifecycle-management

#204 Fix logging inconsistencies
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/kubernetes/adapter/adapter.go
  pkg/reconciler/kubernetes/kubeclient/kubeclient.go
  pkg/reconciler/kubernetes/kubeclient/warnings.go
  pkg/reconciler/kubernetes/kubeclient/warnings_test.go
  pkg/reconciler/kubernetes/progress/progress_test.go
  pkg/reconciler/workspace/factory.go
  pkg/scheduler/localscheduler_test.go
  pkg/scheduler/worker.go
  pkg/scheduler/workerfactory.go
  pkg/test/kubeconfig.go
Labels: lgtm, size/L

#180 Resolve PR, branch, etc. as installation source
  pkg/reconciler/git/clone.go
  pkg/reconciler/git/clone_test.go
  pkg/reconciler/git/resolve.go
  pkg/reconciler/git/resolve_test.go
Labels: lgtm, size/L

#178 Introduce openapi spec
  Makefile
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/integration_test.go
  cmd/reconciler/start/service/integration_test.go
  go.mod
  go.sum
  openapi/.spectral.json
  openapi/README.md
  openapi/docker-compose.yaml
  openapi/external_api.yaml
  openapi/internal_api.yaml
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/keb/contract.go
  pkg/keb/http.go
  pkg/keb/model_gen.go
  pkg/model/clusterstatusentity.go
  pkg/reconciler/callback/callback_test.go
  pkg/reconciler/heartbeat/heartbeat.go
  pkg/reconciler/heartbeat/heartbeat_test.go
  pkg/reconciler/model.go
  pkg/reconciler/model_gen.go
  pkg/scheduler/localinvoker.go
  pkg/scheduler/localscheduler.go
  scripts/git-check.sh
Labels: size/XL, lgtm

#209 Quick fix of destination fetch in Git package
  pkg/reconciler/git/resolve.go
Labels: lgtm, size/XS

#201 Delete namespaces which were managed by reconciler
  pkg/reconciler/kubernetes/adapter/adapter.go
  pkg/reconciler/kubernetes/kubeclient/kubeclient.go
  pkg/reconciler/kubernetes/kubeclient/simplerestclientgetter.go
Labels: size/M, lgtm

#212 Bump image version
  README.md
  resources/reconciler/OWNERS
  resources/reconciler/values.yaml
  scripts/e2e-test/template.json
Labels: lgtm, size/S

#211 Redirect stdout/err of istioctl to zap.Logger
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/istioctl/commander.go
Labels: size/M, lgtm

#213 Pass domain to components in e2e-test
  scripts/e2e-test/get-reconcile-status.sh
  scripts/e2e-test/reconcile-kyma.sh
  scripts/e2e-test/request-reconcile.sh
  scripts/e2e-test/template.json
Labels: lgtm, size/L

#214 Fix callback message model
  cmd/reconciler/start/service/integration_test.go
  openapi/internal_api.yaml
  pkg/reconciler/heartbeat/heartbeat.go
  pkg/reconciler/model.go
  pkg/reconciler/model_gen.go
  pkg/scheduler/localinvoker.go
Labels: size/M, lgtm

#218 Tests Correction
  pkg/reconciler/service/runner_test.go
Labels: lgtm, size/XS

#216 Extracting Common Install Struct
  pkg/reconciler/service/install.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
Labels: lgtm, size/L

#223 Extracting Model to Context Struct
  pkg/reconciler/instances/busolamigrator/action.go
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
  pkg/reconciler/instances/example/action.go
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/rafter/action.go
  pkg/reconciler/instances/rafter/action_test.go
  pkg/reconciler/service/action.go
  pkg/reconciler/service/reconciler_test.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
Labels: size/M, lgtm

#224 Fix bug when deleting namespaces which don't exist
  cmd/mothership/mothership/start/integration_test.go
  pkg/reconciler/kubernetes/adapter/adapter.go
Labels: lgtm, size/XS

#225 Add more logs while reconciliation
  scripts/e2e-test/reconcile-kyma.sh
Labels: lgtm, size/S

#220 Include component resources to be installed with chart
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
Labels: lgtm, size/L

#226 Fix script
  scripts/e2e-test/reconcile-kyma.sh
Labels: lgtm, size/XS

#222 Fix cluster status ordering
  pkg/cluster/inventory.go
Labels: lgtm, size/XS
