Repository kyma-incubator/reconciler, pull requests merged in 2021-08, with the labels that each got.

#66 Interceptor - add managed-by label
  Dockerfile
  go.mod
  go.sum
  pkg/reconciler/model.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
Labels: lgtm, size/L

#70 Add correlation ID to component reconciler
  pkg/logger/zap.go
  pkg/reconciler/callback/callback_test.go
  pkg/reconciler/callback/remote.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/kubernetes/adapter.go
  pkg/reconciler/kubernetes/client.go
  pkg/reconciler/kubernetes/client_test.go
  pkg/reconciler/model.go
  pkg/reconciler/progress/progress.go
  pkg/reconciler/progress/progress_test.go
  pkg/reconciler/progress/watchable_test.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/reconciler_test.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/status/status.go
  pkg/reconciler/status/status_test.go
Labels: lgtm, size/L

#74 Schedule reconciliation workers
  cmd/service/start/cmd.go
  cmd/service/start/http.go
  cmd/service/start/options.go
  cmd/service/start/scheduler.go
  configs/component-reconcilers.json
  go.mod
  pkg/app/registry.go
  pkg/reconciler/model.go
  pkg/scheduler/operations.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/worker.go
Labels: lgtm, size/XL

#77 Charts for reconciler
  Dockerfile
  pkg/db/factory.go
  resources/reconciler/.helmignore
  resources/reconciler/Chart.yaml
  resources/reconciler/OWNERS
  resources/reconciler/charts/mothership-reconciler/.helmignore
  resources/reconciler/charts/mothership-reconciler/Chart.yaml
  resources/reconciler/charts/mothership-reconciler/templates/NOTES.txt
  resources/reconciler/charts/mothership-reconciler/templates/_helpers.tpl
  resources/reconciler/charts/mothership-reconciler/templates/deployment.yaml
  resources/reconciler/charts/mothership-reconciler/templates/service.yaml
  resources/reconciler/charts/mothership-reconciler/templates/tests/test-connection.yaml
  resources/reconciler/charts/mothership-reconciler/values.yaml
  resources/reconciler/charts/postgresql/.helmignore
  resources/reconciler/charts/postgresql/Chart.yaml
  resources/reconciler/charts/postgresql/README.md
  resources/reconciler/charts/postgresql/templates/NOTES.txt
  resources/reconciler/charts/postgresql/templates/_helpers.tpl
  resources/reconciler/charts/postgresql/templates/configmap.yaml
  resources/reconciler/charts/postgresql/templates/extended-config-configmap.yaml
  resources/reconciler/charts/postgresql/templates/init-db-config-map.yaml
  resources/reconciler/charts/postgresql/templates/initialization-configmap.yaml
  resources/reconciler/charts/postgresql/templates/metrics-svc.yaml
  resources/reconciler/charts/postgresql/templates/networkpolicy.yaml
  resources/reconciler/charts/postgresql/templates/secrets.yaml
  resources/reconciler/charts/postgresql/templates/serviceaccount.yaml
  resources/reconciler/charts/postgresql/templates/servicemonitor.yaml
  resources/reconciler/charts/postgresql/templates/statefulset-slaves.yaml
  resources/reconciler/charts/postgresql/templates/statefulset.yaml
  resources/reconciler/charts/postgresql/templates/svc-headless.yaml
  resources/reconciler/charts/postgresql/templates/svc-read.yaml
  resources/reconciler/charts/postgresql/templates/svc.yaml
  resources/reconciler/charts/postgresql/values.yaml
  resources/reconciler/requirements.yaml
  resources/reconciler/templates/_helpers.tpl
  resources/reconciler/values.yaml
Labels: size/XXL, lgtm

#67 Component reconciler refimpl
  Dockerfile
  README.md
  cmd/main.go
  cmd/reconciler/reconciler.go
  cmd/reconciler/start/cmd.go
  cmd/reconciler/start/options.go
  cmd/reconciler/start/service/cmd.go
  cmd/reconciler/start/start.go
  internal/cli/options.go
  internal/cli/reconciler/options.go
  internal/cli/reconciler/recurring.go
  internal/cli/reconciler/retry.go
  internal/cli/reconciler/server.go
  internal/cli/reconciler/worker.go
  pkg/reconciler/callback/callback_test.go
  pkg/reconciler/callback/local.go
  pkg/reconciler/callback/remote.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/instances/example/action.go
  pkg/reconciler/instances/example/example.go
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/new-reconciler.sh
  pkg/reconciler/kubernetes/adapter.go
  pkg/reconciler/kubernetes/client.go
  pkg/reconciler/progress/progress.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/reconciler_test.go
  pkg/reconciler/service/registry.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/status/status.go
  pkg/reconciler/status/status_test.go
  pkg/reconciler/workspace/factory.go
  pkg/reconciler/workspace/factory_test.go
Labels: size/XXL, lgtm

#80 Create component-reconcilers chart
  Makefile
  resources/reconciler/charts/component-reconcilers/.helmignore
  resources/reconciler/charts/component-reconcilers/Chart.yaml
  resources/reconciler/charts/component-reconcilers/templates/deployment.yaml
  resources/reconciler/charts/component-reconcilers/templates/service.yaml
  resources/reconciler/charts/component-reconcilers/values.yaml
  resources/reconciler/charts/mothership-reconciler/Chart.yaml
  resources/reconciler/charts/mothership-reconciler/templates/NOTES.txt
  resources/reconciler/charts/mothership-reconciler/templates/deployment.yaml
  resources/reconciler/charts/mothership-reconciler/values.yaml
  resources/reconciler/requirements.yaml
  resources/reconciler/values.yaml
Labels: lgtm, size/L

#83 Kubeconfig has to be passed from KEB-contract model to reconciler-DB
  pkg/cluster/inventory.go
  pkg/cluster/test/cluster.json
Labels: lgtm, size/XS

#84 Add component name to logs
  pkg/reconciler/service/reconciler.go
Labels: lgtm, size/XS

#85 Fixing issue with missing namespace when deploying manifests
  configs/component-reconcilers.json
  pkg/reconciler/instances/base/base.go
  pkg/reconciler/instances/loader.go
  pkg/reconciler/kubernetes/adapter/adapter.go
  pkg/reconciler/kubernetes/adapter/adapter_test.go
  pkg/reconciler/kubernetes/adapter/test/unittest-with-namespace.yaml
  pkg/reconciler/kubernetes/adapter/test/unittest-without-namespace.yaml
  pkg/reconciler/kubernetes/client.go
  pkg/reconciler/kubernetes/kubeclient/kubeclient.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/test.go
  pkg/scheduler/worker.go
Labels: lgtm, size/L

#90 Improve charts
  Dockerfile
  Makefile
  resources/reconciler/charts/component-reconcilers/templates/deployment.yaml
  resources/reconciler/charts/component-reconcilers/templates/service.yaml
  resources/reconciler/charts/component-reconcilers/values.yaml
  resources/reconciler/charts/mothership-reconciler/templates/_helpers.tpl
  resources/reconciler/charts/mothership-reconciler/templates/configmap.yaml
  resources/reconciler/charts/mothership-reconciler/templates/deployment.yaml
  resources/reconciler/values.yaml
Labels: lgtm, size/L

#92 Add missing namespace fields
  Makefile
  resources/reconciler/charts/component-reconcilers/templates/deployment.yaml
  resources/reconciler/charts/component-reconcilers/templates/service.yaml
  resources/reconciler/charts/mothership-reconciler/templates/configmap.yaml
  resources/reconciler/charts/mothership-reconciler/templates/deployment.yaml
  resources/reconciler/charts/mothership-reconciler/templates/service.yaml
  resources/reconciler/charts/mothership-reconciler/templates/tests/test-connection.yaml
  resources/reconciler/charts/postgresql/templates/init-db-config-map.yaml
Labels: bug, lgtm, size/S

#88 Improve utility-script for creating reconcilers and extend Act-context
  README.md
  cmd/config/cmd.go
  cmd/main.go
  cmd/mothership/cmd.go
  cmd/mothership/start/cmd.go
  cmd/mothership/start/http.go
  cmd/mothership/start/options.go
  cmd/mothership/start/scheduler.go
  cmd/reconciler/cmd.go
  cmd/reconciler/reconciler.go
  cmd/reconciler/start/cmd.go
  cmd/reconciler/start/service/cmd.go
  cmd/reconciler/start/start.go
  cmd/reconciler/test/cmd.go
  cmd/reconciler/test/service/cmd.go
  internal/cli/reconciler/start.go
  pkg/logger/zap.go
  pkg/reconciler/instances/base/base.go
  pkg/reconciler/instances/example/example.go
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/instances/new-reconciler.sh
  pkg/reconciler/instances/reconcilerctl.sh
  pkg/reconciler/kubernetes/adapter/adapter.go
  pkg/reconciler/kubernetes/client.go
  pkg/reconciler/kubernetes/kubeclient/kubeclient.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner.go
  resources/reconciler/charts/mothership-reconciler/templates/deployment.yaml
Labels: size/XL, lgtm

#93 Bump reconciler image
  resources/reconciler/values.yaml
Labels: lgtm, size/XS

#76 Add Busola migrator patch job
  pkg/reconciler/instances/busolamigrator/action.go
  pkg/reconciler/instances/busolamigrator/action_test.go
  pkg/reconciler/instances/busolamigrator/busola.go
  pkg/reconciler/instances/busolamigrator/test_files/virtual-service.yaml
  pkg/reconciler/instances/busolamigrator/vs_client.go
  pkg/reconciler/instances/loader.go
  pkg/reconciler/kubernetes/adapter/adapter.go
  resources/reconciler/values.yaml
  scripts/lint.sh
Labels: lgtm, size/L

#98 Fix components command
  Makefile
  resources/reconciler/charts/component-reconcilers/templates/deployment.yaml
  resources/reconciler/charts/component-reconcilers/templates/service.yaml
Labels: bug, lgtm, size/S

#100 Rename busola-migrator to busola
  pkg/reconciler/instances/busola/action.go
  pkg/reconciler/instances/busola/action_test.go
  pkg/reconciler/instances/busola/busola.go
  pkg/reconciler/instances/busola/test_files/virtual-service.yaml
  pkg/reconciler/instances/busola/vs_client.go
  pkg/reconciler/instances/loader.go
Labels: lgtm, size/S

#99 End2end test suite for reconciler
  cmd/e2e/cluster_inventory_test.go
  cmd/e2e/request/correct_simple_request.json
  cmd/e2e/request/wrong_kubeconfig.json
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/simpletestcomponent/action.go
  pkg/reconciler/instances/simpletestcomponent/simpletestcomponent.go
Labels: lgtm, size/L

#101 Bump image
  resources/reconciler/charts/mothership-reconciler/templates/_helpers.tpl
  resources/reconciler/values.yaml
Labels: lgtm, size/XS

#102 Parametrize the callback URL
  cmd/mothership/start/cmd.go
  cmd/mothership/start/scheduler.go
  configs/reconciler.yaml
  pkg/scheduler/worker.go
  resources/reconciler/charts/mothership-reconciler/templates/cr-configmap.yaml
  resources/reconciler/charts/mothership-reconciler/templates/deployment.yaml
  resources/reconciler/charts/mothership-reconciler/templates/mr-configmap.yaml
  resources/reconciler/values.yaml
Labels: size/M, lgtm

#103 Revert renaming busola migrator
  pkg/reconciler/instances/busolamigrator/action.go
  pkg/reconciler/instances/busolamigrator/action_test.go
  pkg/reconciler/instances/busolamigrator/busola.go
  pkg/reconciler/instances/busolamigrator/test_files/virtual-service.yaml
  pkg/reconciler/instances/busolamigrator/vs_client.go
  pkg/reconciler/instances/loader.go
  resources/reconciler/charts/component-reconcilers/templates/deployment.yaml
  resources/reconciler/values.yaml
Labels: lgtm, size/S

#104 Reconcile CRDs and Istio first
  cmd/mothership/start/scheduler.go
  configs/reconciler.yaml
  pkg/reconciler/model.go
  pkg/reconciler/status/status.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/worker.go
  resources/reconciler/charts/mothership-reconciler/templates/mr-configmap.yaml
  resources/reconciler/charts/mothership-reconciler/values.yaml
  resources/reconciler/values.yaml
Labels: lgtm, size/L

#105 CorrelationID naming refactor
  pkg/scheduler/operations.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/worker.go
Labels: lgtm, size/L

#89 Extract reconciler invocation
  cmd/mothership/start/scheduler.go
  pkg/reconciler/callback/callback_test.go
  pkg/reconciler/callback/local.go
  pkg/reconciler/model.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner_test.go
  pkg/repository/cachedep_test.go
  pkg/scheduler/invoker.go
  pkg/scheduler/localscheduler_integration_test.go
  pkg/scheduler/mock_inventory_watcher.go
  pkg/scheduler/mock_operations_registry.go
  pkg/scheduler/mock_reconciler_invoker.go
  pkg/scheduler/mock_reconciliation_worker.go
  pkg/scheduler/mock_scheduler.go
  pkg/scheduler/mock_worker_factory.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/scheduler/worker.go
  pkg/scheduler/workerfactory.go
Labels: size/XL, lgtm

#87 Add ensure-rafter-secret action
  go.mod
  go.sum
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/rafter/action.go
  pkg/reconciler/instances/rafter/action_test.go
  pkg/reconciler/instances/rafter/rafter.go
  pkg/reconciler/instances/rafter/test_files/0.0.0/resources/rafter/charts/controller-manager/charts/minio/values.yaml
  pkg/reconciler/instances/rafter/test_files/0.0.0/success.yaml
  pkg/reconciler/instances/rafter/test_files/0.0.1/resources/rafter/charts/controller-manager/charts/minio/values.yaml
  pkg/reconciler/instances/rafter/test_files/0.0.1/success.yaml
  pkg/reconciler/instances/rafter/test_files/invalid_values.yaml
  pkg/reconciler/instances/rafter/test_files/valid-values.yaml
  pkg/reconciler/kubernetes/mocks/Client.go
  pkg/test/kubeconfig.go
Labels: size/XL, lgtm

#107 Add encryption for DB columns
  cmd/mothership/cmd.go
  cmd/mothership/install/cmd.go
  cmd/mothership/install/options.go
  cmd/mothership/start/cmd.go
  cmd/mothership/start/options.go
  configs/encryption/.gitignore
  configs/encryption/unittest.key
  configs/reconciler-unittest.yaml
  configs/reconciler.yaml
  internal/cli/encryptionkey.go
  pkg/cluster/inventory.go
  pkg/db/columnhandler.go
  pkg/db/columnhandler_test.go
  pkg/db/encrypt.go
  pkg/db/encrypt_test.go
  pkg/db/factory.go
  pkg/db/interface.go
  pkg/db/mocks.go
  pkg/db/postgres.go
  pkg/db/query.go
  pkg/db/sqlite.go
  pkg/db/testfactory.go
  pkg/files/exists.go
  pkg/kv/repository.go
  pkg/model/clusterentity.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/instances/busolamigrator/busola.go
  pkg/reconciler/instances/rafter/action_test.go
  pkg/reconciler/instances/rafter/rafter.go
  pkg/reconciler/instances/simpletestcomponent/simpletestcomponent.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/workspace/factory.go
  pkg/reconciler/workspace/factory_test.go
  pkg/repository/cachedep_test.go
  pkg/repository/repository.go
  pkg/scheduler/localscheduler_integration_test.go
  pkg/scheduler/localscheduler_test.go
  pkg/scheduler/mock_inventorywatch.go
  pkg/scheduler/mock_invoker.go
  pkg/scheduler/mock_operations.go
  pkg/scheduler/mock_worker.go
  pkg/scheduler/mock_workerfactory.go
  pkg/scheduler/operations.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/test/.gitignore
  resources/reconciler/charts/mothership-reconciler/templates/deployment.yaml
Labels: size/XXL, lgtm

#113 Local installation
  cmd/local/cmd.go
  cmd/local/options.go
  cmd/main.go
  go.mod
  go.sum
Labels: lgtm, size/L

#121 Cherrypick helm client
  go.mod
  go.sum
  pkg/cluster/bucketmerger.go
  pkg/reconciler/chart/component.go
  pkg/reconciler/chart/component_test.go
  pkg/reconciler/chart/helm.go
  pkg/reconciler/chart/helm_test.go
  pkg/reconciler/chart/logadapter.go
  pkg/reconciler/chart/manifest.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/chart/provideropts.go
  pkg/reconciler/chart/test/unittest-kyma/components.yaml
  pkg/reconciler/chart/test/unittest-kyma/resources/component-1/configmap-expected.yaml
  pkg/reconciler/chart/test/unittest-kyma/resources/component-1/profile.yaml
  pkg/reconciler/chart/test/unittest-kyma/resources/component-1/templates/configmap.yaml
  pkg/reconciler/chart/test/unittest-kyma/resources/component-1/values.yaml
  pkg/reconciler/kubernetes/adapter/adapter.go
  pkg/reconciler/kubernetes/kubeclient/kubeclient.go
  pkg/reconciler/kubernetes/kubeclient/unstructured.go
  pkg/reconciler/service/interceptor.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/service/test.go
  pkg/reconciler/workspace/factory.go
  pkg/reconciler/workspace/factory_test.go
  pkg/scheduler/localscheduler_test.go
  pkg/scheduler/worker.go
Labels: size/XXL, lgtm
