Repository kyma-incubator/reconciler, pull requests merged in 2021-10, with the labels that each got.

#171 Feature/istio reconciler upgrade
  pkg/reconciler/chart/mocks/provider.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/actions.go
  pkg/reconciler/instances/istio/actions/actions_test.go
  pkg/reconciler/instances/istio/actions/mocks/istio_performer.go
  pkg/reconciler/instances/istio/actions/mocks/performer.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/clientset/mocks/provider.go
  pkg/reconciler/instances/istio/clientset/provider.go
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/instances/istio/istioctl/commander.go
  pkg/reconciler/instances/istio/istioctl/commander_test.go
  pkg/reconciler/instances/istio/istioctl/mocks/Commander.go
  pkg/reconciler/instances/istio/reset/config/config.go
  pkg/reconciler/instances/istio/reset/data/gatherer.go
  pkg/reconciler/instances/istio/reset/data/gatherer_test.go
  pkg/reconciler/instances/istio/reset/data/mocks/Gatherer.go
  pkg/reconciler/instances/istio/reset/pod/handler.go
  pkg/reconciler/instances/istio/reset/pod/handler_test.go
  pkg/reconciler/instances/istio/reset/pod/matcher.go
  pkg/reconciler/instances/istio/reset/pod/matcher_test.go
  pkg/reconciler/instances/istio/reset/pod/mocks/Handler.go
  pkg/reconciler/instances/istio/reset/pod/mocks/Matcher.go
  pkg/reconciler/instances/istio/reset/pod/reset/action.go
  pkg/reconciler/instances/istio/reset/pod/reset/action_test.go
  pkg/reconciler/instances/istio/reset/pod/reset/mocks/action.go
  pkg/reconciler/instances/istio/reset/proxy/mocks/istio_proxy_reset.go
  pkg/reconciler/instances/istio/reset/proxy/proxy.go
  pkg/reconciler/instances/istio/reset/proxy/proxy_test.go
  pkg/reconciler/instances/istio/test_files/istio-test/Chart.yaml
  pkg/reconciler/service/action.go
  pkg/reconciler/service/install.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/workspace/factory.go
  pkg/reconciler/workspace/factory_test.go
  pkg/reconciler/workspace/mocks/factory.go
Labels: enhancement, size/XXL, lgtm

#227 Rename istio prereq to istio-configuration
  resources/reconciler/charts/mothership-reconciler/values.yaml
Labels: lgtm, size/XS

#230 Rename istio and bump image version for e2e tests
  resources/reconciler/values.yaml
  scripts/e2e-test/template.json
Labels: lgtm, size/XS

#233 Improve scheduler logging
  pkg/scheduler/service/bookkeeper.go
  pkg/scheduler/service/inventorywatch.go
  pkg/scheduler/service/run.go
  pkg/scheduler/service/transition.go
  pkg/scheduler/worker/workerpool.go
Labels: size/M, lgtm

#241 Update openapi specification; regenerate openapi model
  openapi/external_api.yaml
  pkg/keb/model_gen.go
Labels: lgtm, size/L

#244 Improve e2e test logs
  scripts/e2e-test/reconcile-kyma.sh
Labels: lgtm, size/S

#228 Add GCloud and Custom DB support to Ory reconcile action
  pkg/reconciler/instances/ory/action_test.go
  pkg/reconciler/instances/ory/db/db.go
  pkg/reconciler/instances/ory/db/db_test.go
  pkg/reconciler/instances/ory/jwks/jwks.go
  pkg/reconciler/instances/ory/jwks/jwks_test.go
  pkg/reconciler/instances/ory/test/resources/test-ory/values.yaml
Labels: lgtm, size/L, hacktoberfest-accepted

#265 Download Charts with URL
  pkg/reconciler/chart/component.go
  pkg/reconciler/chart/helm.go
  pkg/reconciler/model.go
  pkg/reconciler/service/install.go
  pkg/scheduler/invoker/invoker.go
  resources/reconciler/values.yaml
Labels: size/M, lgtm
