Repository kyma-incubator/reconciler, pull requests merged in 2021-12, with the labels that each got.

#502 Return errors on version mismatch
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/istio_test.go
Labels: lgtm, size/L, area/reconciler, area/service-mesh

#508 Improve check when starting recon to avoid rollbacks
  pkg/db/transaction.go
  pkg/model/clusterstatus.go
  pkg/reconciler/kubernetes/adapter.go
  pkg/scheduler/invoker/localinvoker_test.go
  pkg/scheduler/invoker/remoteinvoker.go
  pkg/scheduler/invoker/remoteinvoker_test.go
  pkg/scheduler/invoker/test.go
  pkg/scheduler/reconciliation/filter.go
  pkg/scheduler/service/bookkeeper.go
  pkg/scheduler/service/scheduler.go
  pkg/scheduler/service/transition.go
Labels: lgtm, size/L

#510 Create entire JWKS secret in Pre-Reconciliation
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/ory/action_test.go
  pkg/reconciler/instances/ory/jwks/jwks.go
  pkg/reconciler/instances/ory/ory.go
Labels: lgtm, size/L, area/reconciler, area/api-gateway

#515 Fix tracking replicaSet: ensure desired replicas is > 0
  pkg/reconciler/kubernetes/progress/ready.go
  pkg/reconciler/kubernetes/progress/ready_test.go
  pkg/reconciler/kubernetes/progress/testdata/dep-after-rolling-update.yaml
  pkg/reconciler/kubernetes/progress/testdata/dep-before-rolling-update.yaml
  pkg/reconciler/kubernetes/progress/tracker_test.go
Labels: size/M, lgtm

#519 Return reconciliation runs from precise timebox
  cmd/mothership/mothership/start/helpers.go
  cmd/mothership/mothership/start/helpers_test.go
  cmd/mothership/mothership/start/http.go
  openapi/external_api.yaml
  pkg/db/query.go
  pkg/db/validator.go
  pkg/keb/model_gen.go
  pkg/scheduler/reconciliation/filter.go
  pkg/scheduler/reconciliation/filter_test.go
Labels: lgtm, size/L, area/reconciler

#517 Increase Limit for CountRetries
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/cluster/mock.go
  pkg/scheduler/service/bookkeeper.go
Labels: lgtm, size/S

#531 Added new cluster status to KEB contract
  configs/db/postgres/000007_rename_error_retryable.down.sql
  configs/db/postgres/000007_rename_error_retryable.up.sql
  go.mod
  go.sum
  openapi/external_api.yaml
  pkg/keb/helpers.go
  pkg/keb/model_gen.go
  pkg/model/clusterstatus.go
Labels: size/M, lgtm

#535 Fix replace patch
  Makefile
  go.mod
  go.sum
  pkg/reconciler/kubernetes/internal/kubeclient.go
  pkg/reconciler/kubernetes/internal/kubeclient_test.go
  pkg/reconciler/kubernetes/internal/patcher.go
  pkg/reconciler/kubernetes/internal/replace.go
  pkg/reconciler/kubernetes/internal/test/manifest-after.yaml
  pkg/reconciler/kubernetes/internal/test/manifest-before.yaml
  pkg/reconciler/kubernetes/internal/test/manifest.yaml
  pkg/reconciler/kubernetes/internal/updatestrategyresolver.go
  pkg/reconciler/kubernetes/internal/updatestrategyresolver_test.go
  pkg/scheduler/service/cleaner.go
  pkg/scheduler/service/run_test.go
Labels: size/XXL, lgtm

#541 Use UTC timezone while looking for items to remove
  pkg/scheduler/service/cleaner.go
  pkg/scheduler/service/run_test.go
Labels: bug, lgtm, size/XS

#542 Disabled clusters can't change their status
  pkg/cluster/inventory.go
  pkg/model/clusterstatus.go
Labels: lgtm, size/XS

#520 Reconcile deletion error state
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/cluster/mock.go
  pkg/cluster/statusfilter.go
  pkg/model/clusterstatus.go
  pkg/scheduler/service/bookkeeper.go
Labels: size/M, lgtm

#511 Enhance Unit Tests
  Makefile
  cmd/mothership/mothership/start/http.go
  configs/reconciler-unittest.yaml
  pkg/cluster/inventory_test.go
  pkg/db/factory.go
  pkg/db/postgres.go
  pkg/db/query.go
  pkg/db/query_test.go
  pkg/db/sqlite.go
  pkg/keb/test/cluster.go
  pkg/keb/test/clusterType.go
  pkg/scheduler/invoker/localinvoker.go
  pkg/scheduler/invoker/remoteinvoker.go
  pkg/scheduler/invoker/remoteinvoker_test.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/bookkeeper.go
  pkg/scheduler/service/bookkeeper_test.go
  pkg/scheduler/service/bookkeepingtask.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/result.go
  pkg/scheduler/service/result_test.go
  pkg/scheduler/service/run.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/service/scheduler_test.go
  pkg/scheduler/worker/workerpool.go
  pkg/scheduler/worker/workerpool_test.go
  scripts/postgres.sh
Labels: size/XXL, lgtm

#550 Increase bookkeeper interval
  cmd/mothership/mothership/start/scheduler.go
Labels: lgtm, size/XS

#553 add missing status mapping
  pkg/model/clusterstatusentity.go
Labels: lgtm, size/XS

#551 added imagebump script for prow
  scripts/prow/reconciler-image-autobump.sh
Labels: lgtm, size/L

#540 Ory hydra post reconcile action sync
  go.mod
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/ory/action_test.go
  pkg/reconciler/instances/ory/db/db.go
  pkg/reconciler/instances/ory/db/db_test.go
  pkg/reconciler/instances/ory/hydra/hydra.go
  pkg/reconciler/instances/ory/hydra/hydra_test.go
  pkg/reconciler/instances/ory/hydra/mocks/syncer.go
  pkg/reconciler/instances/ory/ory.go
Labels: size/XL, lgtm, area/api-gateway

#554 Small Enhanced Info logging
  pkg/scheduler/service/transition.go
Labels: lgtm, size/XS

#561 moved autobump config file to reconciler repo
  scripts/prow/autobump-config/control-plane-autobump-reconciler-config.yaml
  scripts/prow/reconciler-image-autobump.sh
Labels: lgtm, size/S

#563 updated autobump prow script
  scripts/prow/reconciler-image-autobump.sh
Labels: lgtm, size/XS

#546 Modify ResourceInterceptor interface
  pkg/reconciler/kubernetes/adapter.go
  pkg/reconciler/kubernetes/adapter_test.go
  pkg/reconciler/kubernetes/client.go
  pkg/reconciler/kubernetes/resource.go
  pkg/reconciler/kubernetes/resource_test.go
  pkg/reconciler/service/annotationsinterceptor.go
  pkg/reconciler/service/annotationsinterceptor_test.go
  pkg/reconciler/service/labelsinterceptor.go
  pkg/reconciler/service/labelsinterceptor_test.go
  pkg/reconciler/service/servicesinterceptor.go
  pkg/reconciler/service/servicesinterceptor_test.go
Labels: lgtm, size/L

#560 Skip parallel tests
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/scheduler_test.go
  pkg/scheduler/worker/workerpool_test.go
Labels: lgtm, size/S

#564 Unit tests for RMA reconciler
  pkg/reconciler/instances/rma/fake_client.go
  pkg/reconciler/instances/rma/integration_action.go
  pkg/reconciler/instances/rma/integration_action_test.go
  pkg/reconciler/instances/rma/lazy_client.go
  pkg/reconciler/instances/rma/rma.go
  pkg/reconciler/instances/rma/testdata/Chart.yaml
  pkg/reconciler/instances/rma/testdata/templates/configmap.yaml
  pkg/reconciler/instances/rma/testdata/values.yaml
Labels: lgtm, size/L

#568 Fix PVC patch: ignore PVCs when size is not modified
  pkg/reconciler/service/install.go
  pkg/reconciler/service/pvcinterceptor.go
  pkg/reconciler/service/pvcinterceptor_test.go
  pkg/reconciler/service/servicesinterceptor.go
  pkg/reconciler/service/servicesinterceptor_test.go
  pkg/reconciler/service/test/pvcinterceptor.yaml
Labels: lgtm, size/L

#570 Implement HPA interceptor
  pkg/reconciler/kubernetes/adapter.go
  pkg/reconciler/kubernetes/client.go
  pkg/reconciler/kubernetes/mocks/client.go
  pkg/reconciler/kubernetes/resource.go
  pkg/reconciler/kubernetes/resource_test.go
  pkg/reconciler/service/hpainterceptor.go
  pkg/reconciler/service/hpainterceptor_test.go
  pkg/reconciler/service/pvcinterceptor.go
  pkg/reconciler/service/servicesinterceptor.go
  pkg/reconciler/service/test/hpainterceptor.yaml
Labels: lgtm, size/L

#574 Improve logging k8sclient
  pkg/reconciler/kubernetes/internal/kubeclient.go
  pkg/reconciler/kubernetes/internal/kubeclient_test.go
Labels: lgtm, size/S

#521 Add "cleanup" reconciler
  cmd/mothership/mothership/start/integration_test.go
  go.mod
  pkg/model/clusterconfigentity.go
  pkg/model/clusterconfigentity_test.go
  pkg/reconciler/instances/cleaner/action.go
  pkg/reconciler/instances/cleaner/cleaner.go
  pkg/reconciler/instances/cleaner/pkg/cleanup/cli.go
  pkg/reconciler/instances/loader.go
  pkg/reconciler/service/install.go
  pkg/scheduler/invoker/localinvoker_test.go
  pkg/scheduler/invoker/remoteinvoker_test.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/run.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/service/scheduler_test.go
  pkg/scheduler/worker/workerpool_test.go
Labels: size/XL, lgtm, area/reconciler

#497 Add support for multiple istioctl versions
  Dockerfile.cr
  go.mod
  go.sum
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/mocks/istio_performer.go
  pkg/reconciler/instances/istio/actions/mocks/testCommanderResolver.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/bootstrap.go
  pkg/reconciler/instances/istio/bootstrap_test.go
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/instances/istio/istio_test.go
  pkg/reconciler/instances/istio/istioctl/commander.go
  pkg/reconciler/instances/istio/istioctl/commander_test.go
  pkg/reconciler/instances/istio/istioctl/mocks/version_checker.go
  pkg/reconciler/instances/istio/istioctl/resolver.go
  pkg/reconciler/instances/istio/istioctl/resolver_internal_test.go
  pkg/reconciler/instances/istio/istioctl/resolver_test.go
  pkg/reconciler/instances/istio/manifest/manifest.go
  pkg/reconciler/instances/istio/manifest/manifest_test.go
  pkg/reconciler/kubernetes/adapter.go
Labels: size/XXL, lgtm, area/reconciler, area/service-mesh

#576 Remove StatefulSet from reconciliation if it contains PVCs
  pkg/reconciler/kubernetes/internal/updatestrategyresolver.go
  pkg/reconciler/kubernetes/internal/updatestrategyresolver_test.go
  pkg/reconciler/service/pvcinterceptor.go
  pkg/reconciler/service/pvcinterceptor_test.go
  pkg/reconciler/service/test/hpainterceptor.yaml
  pkg/reconciler/service/test/pvcinterceptor-pvc.yaml
  pkg/reconciler/service/test/pvcinterceptor-sfs.yaml
Labels: lgtm, size/L

#583 Fix issues of errorRetryable
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/model/clusterstatusentity.go
  pkg/scheduler/service/bookkeepingtask.go
Labels: size/M, lgtm

#585 Strip namespace from templates of selected non namespaced kinds
  pkg/reconciler/instances/clusteressentials/action_test.go
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/instances/istio/istio_test.go
  pkg/reconciler/instances/serverless/action_test.go
  pkg/reconciler/kubernetes/resource.go
  pkg/reconciler/service/clusterwideresourceinterceptor.go
  pkg/reconciler/service/clusterwideresourceinterceptor_test.go
  pkg/reconciler/service/install.go
Labels: lgtm, size/L

#589 Fix kind names in CLuster-wide interceptor
  pkg/reconciler/service/clusterwideresourceinterceptor.go
  pkg/reconciler/service/clusterwideresourceinterceptor_test.go
Labels: lgtm, size/S

#590 Http Dump Removal
  cmd/reconciler/start/service/http.go
Labels: lgtm, size/XS

#591 Remove unused dependencies feature
  cmd/reconciler/start/service/http.go
  cmd/reconciler/start/service/integration_test.go
  pkg/reconciler/http.go
  pkg/reconciler/service/dependencies.go
  pkg/reconciler/service/dependencies_test.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/reconciler_test.go
  pkg/reconciler/service/workerpool.go
  pkg/reconciler/service/workerpool_test.go
  pkg/scheduler/invoker/remoteinvoker.go
Labels: lgtm, size/L

#587 Patch per default
  go.mod
  go.sum
  pkg/reconciler/kubernetes/internal/kubeclient.go
  pkg/reconciler/kubernetes/internal/updatestrategyresolver.go
  pkg/reconciler/kubernetes/internal/updatestrategyresolver_test.go
  pkg/scheduler/invoker/localinvoker.go
Labels: lgtm, size/L

#594 Bring back EventTypePrefix config migration step
  pkg/reconciler/instances/eventing/preaction/common.go
  pkg/reconciler/instances/eventing/preaction/migrateeventtypeprefixconfigstep.go
  pkg/reconciler/instances/eventing/preaction/migrateeventtypeprefixconfigstep_test.go
  pkg/reconciler/instances/eventing/preaction/preaction.go
  pkg/reconciler/instances/eventing/preaction/removenatsoperatorstep.go
Labels: lgtm, size/L, area/eventing

#597 Do not drop PVC / Statefulset+PVC resources from reconciliation
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/service/install.go
  pkg/reconciler/service/pvcinterceptor.go
  pkg/reconciler/service/pvcinterceptor_test.go
Labels: lgtm, size/L, required-for-kyma2.0, release blocker

#599 logged workerpool capacity reached as warning and added component prio to bookkeeper logs
  pkg/scheduler/service/bookkeeper.go
  pkg/scheduler/worker/workerpool.go
Labels: lgtm, size/XS

#608 Re-enable clusters
  cmd/mothership/mothership/start/http.go
  pkg/cluster/inventory.go
Labels: size/M, lgtm

#614 Upgrade the integration test to check the possibility of changing cluster status
  cmd/mothership/mothership/start/integration_test.go
  cmd/mothership/mothership/start/test/requests/disable_cluster.json
  cmd/mothership/mothership/start/test/requests/enable_cluster.json
  cmd/mothership/mothership/start/test/requests/enable_force_cluster.json
Labels: size/M, lgtm

#610 logged watchable resources as INFO when context is closed or resource timed out
  pkg/reconciler/kubernetes/progress/tracker.go
Labels: lgtm, size/XS

#616 Add Xin, Ali and Jeremy as code-owners
  CODEOWNERS
Labels: lgtm, size/XS

#562 Db transaction fix
  pkg/cache/repository.go
  pkg/cache/repository_test.go
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/cluster/mock.go
  pkg/db/interface.go
  pkg/db/mocks.go
  pkg/db/postgres.go
  pkg/db/sqlite.go
  pkg/db/transaction.go
  pkg/kv/repository.go
  pkg/repository/cachedep.go
  pkg/repository/cachedep_test.go
  pkg/repository/repository.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/transition.go
  pkg/scheduler/worker/workerpool_test.go
Labels: size/XL, lgtm

#596 Wait for all components
  pkg/scheduler/service/bookkeeper.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/result.go
  pkg/scheduler/service/result_test.go
Labels: lgtm, size/L, priority/critical

#618 #617: Adjust keb mapping: retryable errors are mapped to corresponding in-progress states
  pkg/model/clusterstatusentity.go
Labels: lgtm, size/XS

#621 #619 - wait for hydra-maester deployment to be running
  go.mod
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/ory/action_test.go
  pkg/reconciler/instances/ory/hydra/mocks/syncer.go
  pkg/reconciler/instances/ory/hydra/syncer.go
  pkg/reconciler/instances/ory/hydra/syncer_test.go
  pkg/reconciler/instances/ory/k8s/rollout.go
  pkg/reconciler/instances/ory/ory.go
Labels: lgtm, size/L, area/api-gateway

#624 fixed misleading workerpool logs
  pkg/scheduler/worker/workerpool.go
Labels: lgtm, size/S

#580 Change workspace structure for downloaded components (#463)
  pkg/reconciler/chart/component.go
  pkg/reconciler/chart/factory.go
  pkg/reconciler/chart/factory_test.go
  pkg/reconciler/chart/test/unittest-kyma/resources/archives/sap-btp-operator-migration.tgz
  pkg/reconciler/chart/workspace.go
Labels: lgtm, size/L, area/reconciler

#625 add missing rs.new status handling
  pkg/scheduler/service/result.go
  pkg/scheduler/service/result_test.go
Labels: lgtm, size/S

#633 upgrade golang image tag
  Dockerfile.cr
  Dockerfile.mr
Labels: lgtm, size/XS
