Repository kyma-incubator/reconciler, pull requests merged in 2021-07, with the labels that each got.

#30 Stabilize cluster inventory
  cmd/example/register-cluster_simple-exemple.json
  cmd/example/register-cluster_structure.json
  cmd/service/start/cmd.go
  configs/db/postgres/000001_reconciler.down.sql
  configs/db/postgres/000001_reconciler.up.sql
  configs/db/sqlite/reconciler.sql
  configs/reconciler-unittest.yaml
  go.mod
  go.sum
  pkg/cache/repository.go
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/cluster/mock.go
  pkg/cluster/state.go
  pkg/cluster/test/cluster.json
  pkg/db/columnhandler.go
  pkg/db/columnhandler_test.go
  pkg/db/query.go
  pkg/db/query_test.go
  pkg/db/testfactory.go
  pkg/keb/contract.go
  pkg/keb/factory.go
  pkg/kv/repository.go
  pkg/model/clusterconfigentity.go
  pkg/model/clusterentity.go
  pkg/model/clusterstatus.go
  pkg/model/clusterstatusentity.go
  pkg/repository/repository.go
Labels: lgtm, size/XL

#31 Stabilize cluster inventory
  configs/db/postgres/000001_reconciler.up.sql
  configs/db/sqlite/reconciler.sql
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/cluster/mock.go
  pkg/cluster/state.go
  pkg/db/interface.go
  pkg/db/marshaller.go
  pkg/db/mocks.go
  pkg/db/postgres.go
  pkg/db/query.go
  pkg/db/sqlite.go
  pkg/model/clusterconfigentity.go
  pkg/model/clusterentity.go
  pkg/model/clusterstatusentity.go
Labels: lgtm, size/XL

#29 Add the first custom metrics
  cmd/main.go
  cmd/service/start/cmd.go
  go.mod
  go.sum
  pkg/metrics/metrics.go
  pkg/metrics/reconciliation_not_ready.go
  pkg/metrics/reconciliation_status.go
  pkg/metrics/reconciliation_waiting.go
Labels: lgtm, size/L

#33 Stabilize cluster inventory
  cmd/service/start/cmd.go
  cmd/service/start/cmd_test.go
  internal/cli/options.go
  internal/cli/test.go
  pkg/cluster/inventory.go
  pkg/cluster/statusfilter.go
  pkg/db/testfactory.go
  pkg/repository/repository.go
Labels: lgtm, size/L

#34 Changes cluster states
  cmd/service/start/cmd.go
  pkg/cluster/clusterfilter.go
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/cluster/mock.go
  pkg/cluster/statuschange.go
Labels: lgtm, size/L

#38 Add object registry and prepare service-cmd to add boostrapping code
  cmd/config/create/key/cmd.go
  cmd/config/create/value/cmd.go
  cmd/config/get/bucket/cmd.go
  cmd/config/get/key/cmd.go
  cmd/config/get/value/cmd.go
  cmd/main.go
  cmd/service/start/cmd.go
  cmd/service/start/options.go
  internal/cli/options.go
  internal/cli/test.go
  pkg/app/registry.go
  pkg/logger/zap.go
  pkg/server/params.go
  pkg/server/server.go
Labels: lgtm, size/XL

#41 Add Dockerfile
  Dockerfile
  Makefile
Labels: lgtm, size/M

#42 Get latest status
  cmd/service/start/cmd.go
Labels: lgtm, size/S

#39 Add chart provider
  go.mod
  go.sum
  pkg/chart/component.go
  pkg/chart/logadapter.go
  pkg/chart/provider.go
  pkg/chart/provider_test.go
  pkg/chart/provideropts.go
  pkg/chart/test/unittest-complist-expected.yaml
  pkg/chart/test/unittest-complist.yaml
  pkg/chart/test/unittest-kyma/components.yaml
  pkg/chart/test/unittest-kyma/installation/crds/component-1/crd.yaml
  pkg/chart/test/unittest-kyma/resources/component-1/Chart.yaml
  pkg/chart/test/unittest-kyma/resources/component-1/configmap-expected.yaml
  pkg/chart/test/unittest-kyma/resources/component-1/templates/configmap.yaml
  pkg/chart/test/unittest-kyma/resources/component-1/values.yaml
  pkg/cluster/kubeconfig.go
  pkg/cluster/mock.go
  pkg/model/clusterconfigentity.go
  pkg/model/clusterentity.go
  pkg/workspace/factory.go
  pkg/workspace/factory_test.go
Labels: lgtm, size/XXL

#47 Add sqlite support for standalone reconciler
  cmd/main.go
  configs/db/postgres/000001_reconciler.up.sql
  configs/db/sqlite/reconciler.sql
  configs/reconciler-unittest.yaml
  configs/reconciler.yaml
  go.mod
  go.sum
  pkg/db/factory.go
  pkg/db/interface.go
  pkg/db/postgres.go
  pkg/db/sqlite.go
  pkg/db/testfactory.go
Labels: lgtm, size/L

#46 Component reconciler framework - measure progress
  go.mod
  pkg/compreconciler/runner.go
  pkg/compreconciler/status.go
Labels: lgtm, size/L

#49 Component reconciler framework
  Makefile
  cmd/reconciler/start/cmd.go
  cmd/service/start/cmd.go
  cmd/service/start/cmd_test.go
  go.mod
  go.sum
  internal/cli/context.go
  pkg/chart/provider.go
  pkg/chart/provider_test.go
  pkg/chart/test/unittest-complist-expected.yaml
  pkg/chart/test/unittest-complist.yaml
  pkg/compreconciler/callback.go
  pkg/compreconciler/callback_test.go
  pkg/compreconciler/kubectl.go
  pkg/compreconciler/kubernetes.go
  pkg/compreconciler/kubernetes_test.go
  pkg/compreconciler/model.go
  pkg/compreconciler/progress.go
  pkg/compreconciler/progress_test.go
  pkg/compreconciler/reconciler.go
  pkg/compreconciler/reconciler_test.go
  pkg/compreconciler/runner.go
  pkg/compreconciler/runner_test.go
  pkg/compreconciler/status.go
  pkg/compreconciler/status_test.go
  pkg/compreconciler/test.go
  pkg/compreconciler/test/.gitignore
  pkg/compreconciler/test/unittest.yaml
  pkg/compreconciler/watchable.go
  pkg/compreconciler/watchable_test.go
  pkg/db/columnhandler.go
  pkg/files/exists.go
  pkg/git/clone.go
  pkg/kubernetes/clientbuilder.go
  pkg/logger/zap.go
  pkg/server/server.go
  pkg/test/expensive_test.go
  pkg/test/kubeconfig.go
  pkg/workspace/factory.go
  pkg/workspace/factory_test.go
Labels: lgtm, size/XXL

#50 Compreconciler unit tests
  pkg/chart/provider.go
  pkg/compreconciler/kubectl.go
  pkg/compreconciler/progress.go
  pkg/compreconciler/reconciler.go
  pkg/compreconciler/runner.go
  pkg/compreconciler/runner_test.go
  pkg/compreconciler/test/.gitignore
  pkg/compreconciler/test/0.0.0/installation/resources/crds/component-1/crd.yaml
  pkg/compreconciler/test/0.0.0/resources/component-1/Chart.yaml
  pkg/compreconciler/test/0.0.0/resources/component-1/configmap-expected.yaml
  pkg/compreconciler/test/0.0.0/resources/component-1/templates/configmap.yaml
  pkg/compreconciler/test/0.0.0/resources/component-1/templates/pod.yaml
  pkg/compreconciler/test/0.0.0/resources/component-1/templates/pod2.yaml
  pkg/compreconciler/test/0.0.0/resources/component-1/values.yaml
Labels: lgtm, size/L

#48 Scheduler impl
  .gitignore
  cmd/service/start/cmd.go
  cmd/service/start/http.go
  cmd/service/start/options.go
  cmd/service/start/scheduler.go
  go.mod
  go.sum
  pkg/cluster/mock.go
  pkg/compreconciler/reconciler.go
  pkg/scheduler/inventorywatch.go
  pkg/scheduler/inventorywatch_test.go
  pkg/scheduler/scheduler.go
Labels: lgtm, size/XL

#56 Embed state update collector into inventory
  pkg/app/registry.go
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/metrics/reconciliation_status.go
Labels: lgtm, size/M

#58 Integrate ant workers into component reconciler
  .gitignore
  cmd/reconciler/start/cmd.go
  pkg/app/registry.go
  pkg/compreconciler/kubernetes.go
  pkg/compreconciler/model.go
  pkg/compreconciler/progress_test.go
  pkg/compreconciler/reconciler.go
  pkg/compreconciler/reconciler_test.go
  pkg/compreconciler/status.go
  pkg/compreconciler/test.go
  pkg/compreconciler/test/.gitignore
  pkg/error/error.go
  pkg/reconciler/callback/callback.go
  pkg/reconciler/callback/callback_test.go
  pkg/reconciler/callback/local.go
  pkg/reconciler/callback/remote.go
  pkg/reconciler/chart/component.go
  pkg/reconciler/chart/logadapter.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/chart/provideropts.go
  pkg/reconciler/chart/test/unittest-kyma/components.yaml
  pkg/reconciler/chart/test/unittest-kyma/installation/crds/component-1/crd.yaml
  pkg/reconciler/chart/test/unittest-kyma/resources/component-1/Chart.yaml
  pkg/reconciler/chart/test/unittest-kyma/resources/component-1/configmap-expected.yaml
  pkg/reconciler/chart/test/unittest-kyma/resources/component-1/templates/configmap.yaml
  pkg/reconciler/chart/test/unittest-kyma/resources/component-1/values.yaml
  pkg/reconciler/git/clone.go
  pkg/reconciler/git/clone_test.go
  pkg/reconciler/git/testdata/repo.tgz
  pkg/reconciler/kubernetes/kubectl.go
  pkg/reconciler/kubernetes/kubernetes.go
  pkg/reconciler/kubernetes/kubernetes_test.go
  pkg/reconciler/kubernetes/test/unittest.yaml
  pkg/reconciler/model.go
  pkg/reconciler/progress/progress.go
  pkg/reconciler/progress/progress_test.go
  pkg/reconciler/progress/test/unittest.yaml
  pkg/reconciler/progress/watchable.go
  pkg/reconciler/progress/watchable_test.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/reconciler_test.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/service/test/.gitignore
  pkg/reconciler/service/test/0.0.0/installation/resources/crds/component-1/crd.yaml
  pkg/reconciler/service/test/0.0.0/resources/component-1/Chart.yaml
  pkg/reconciler/service/test/0.0.0/resources/component-1/configmap-expected.yaml
  pkg/reconciler/service/test/0.0.0/resources/component-1/templates/configmap.yaml
  pkg/reconciler/service/test/0.0.0/resources/component-1/templates/pod.yaml
  pkg/reconciler/service/test/0.0.0/resources/component-1/templates/pod2.yaml
  pkg/reconciler/service/test/0.0.0/resources/component-1/values.yaml
  pkg/reconciler/status/status.go
  pkg/reconciler/status/status_test.go
  pkg/reconciler/workspace/factory.go
  pkg/reconciler/workspace/factory_test.go
  pkg/reconciler/workspace/test/.gitignore
  pkg/server/server.go
Labels: lgtm, size/XXL

#59 Improve e2e-test for reconciler
  pkg/reconciler/model.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/reconciler_test.go
Labels: lgtm, size/L

#61 Improve error msgs when creating kubeconfigs
  pkg/kubernetes/clientbuilder.go
Labels: lgtm, size/S

#60 Detect incomplete Git repository clones
  pkg/metrics/reconciliation_status.go
  pkg/reconciler/workspace/factory.go
  pkg/reconciler/workspace/factory_test.go
Labels: lgtm, size/M

#62 Move to sugared logger
  cmd/main.go
  internal/cli/options.go
  pkg/app/registry.go
  pkg/cache/repository.go
  pkg/cluster/inventory.go
  pkg/db/postgres.go
  pkg/db/sqlite.go
  pkg/db/transaction.go
  pkg/kv/repository.go
  pkg/logger/zap.go
  pkg/metrics/metrics.go
  pkg/metrics/reconciliation_not_ready.go
  pkg/metrics/reconciliation_waiting.go
  pkg/reconciler/callback/local.go
  pkg/reconciler/callback/remote.go
  pkg/reconciler/chart/logadapter.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/progress/progress.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/status/status.go
  pkg/reconciler/workspace/factory.go
  pkg/repository/cachedep.go
  pkg/repository/repository.go
  pkg/scheduler/inventorywatch.go
  pkg/scheduler/scheduler.go
  pkg/server/server.go
Labels: lgtm, size/L

#65 Delete manifest - native go client
  go.mod
  pkg/reconciler/kubernetes/adapter.go
Labels: lgtm, size/L

#64 Fix logger calls in adapter
  pkg/reconciler/kubernetes/adapter.go
  pkg/reconciler/progress/progress.go
  pkg/reconciler/progress/progress_test.go
  pkg/reconciler/service/reconciler_test.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/test/0.0.0/resources/component-1/templates/configmap.yaml
  pkg/reconciler/service/test/0.0.0/resources/component-1/templates/pod.yaml
  pkg/reconciler/service/test/0.0.0/resources/component-1/templates/pod2.yaml
  pkg/reconciler/status/status.go
  pkg/reconciler/status/status_test.go
Labels: lgtm, size/L
