Repository kyma-incubator/reconciler, pull requests merged in 2021-11, with the labels that each got.

#317 Do not updated operation state to 'error' if component reconciler gets stopped
  pkg/reconciler/heartbeat/heartbeat.go
  pkg/reconciler/heartbeat/heartbeat_test.go
  pkg/scheduler/service/bookkeeper.go
Labels: size/M, lgtm

#338 Fix database migration
  configs/db/postgres/000005_operation_type.up.sql
Labels: lgtm, size/XS

#336 Refactor Eventing reconciler to allow multi-step actions
  pkg/reconciler/instances/eventing/action/action.go
  pkg/reconciler/instances/eventing/action/step.go
  pkg/reconciler/instances/eventing/eventing.go
  pkg/reconciler/instances/eventing/eventing_test.go
  pkg/reconciler/instances/eventing/log.go
  pkg/reconciler/instances/eventing/log/log.go
  pkg/reconciler/instances/eventing/postaction/postaction.go
  pkg/reconciler/instances/eventing/preaction/migrateeventtypeprefixconfigstep.go
  pkg/reconciler/instances/eventing/preaction/migrateeventtypeprefixconfigstep_test.go
  pkg/reconciler/instances/eventing/preaction/preaction.go
  resources/reconciler/values.yaml
Labels: lgtm, size/L, area/eventing

#289 Ory upgrade and config migration
  go.mod
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/ory/action_test.go
  pkg/reconciler/instances/ory/db/db.go
  pkg/reconciler/instances/ory/db/db_test.go
  pkg/reconciler/instances/ory/db/model.go
Labels: size/XL, lgtm

#350 Make teams owners of their component reconcilers
  CODEOWNERS
Labels: lgtm, size/S

#323 Improve db logging
  pkg/cache/repository.go
  pkg/cluster/inventory.go
  pkg/db/columnhandler.go
  pkg/db/columnhandler_test.go
  pkg/db/query.go
  pkg/db/query_test.go
  pkg/kv/repository.go
  pkg/repository/cachedep.go
  pkg/repository/cachedep_test.go
  pkg/scheduler/reconciliation/persistent.go
Labels: lgtm, size/L

#349 istio bump to 1.11.4
  Dockerfile.cr
Labels: lgtm, size/XS

#357 Fix nil state update when starting reconciliation
  pkg/model/clusterstatus.go
  pkg/scheduler/service/transition.go
Labels: lgtm, size/S

#337 Change reconciler logic to replace kubernetes resources instead of patching them
  cmd/reconciler/start/service/integration_test.go
  cmd/reconciler/start/service/test/0.0.0/resources/component-1/templates/pod.yaml
  cmd/reconciler/start/service/test/0.0.0/resources/component-1/values.yaml
  go.mod
  go.sum
  pkg/reconciler/kubernetes/adapter/adapter_test.go
  pkg/reconciler/kubernetes/adapter/test/unittest-with-namespace.yaml
  pkg/reconciler/kubernetes/kubeclient/kubeclient.go
  pkg/reconciler/kubernetes/kubeclient/patcher.go
  pkg/reconciler/kubernetes/kubeclient/replace.go
  pkg/reconciler/kubernetes/progress/progress_test.go
  pkg/reconciler/kubernetes/progress/test/unittest.yaml
Labels: size/XL, lgtm

#352 Add preDeleteAction to ory reconciler
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/ory/action_test.go
  pkg/reconciler/instances/ory/ory.go
Labels: lgtm, size/L, area/reconciler

#304 Remove Helm Charts
  Makefile
  README.md
  resources/README.md
  resources/reconciler/.helmignore
  resources/reconciler/Chart.yaml
  resources/reconciler/charts/component-reconcilers/.helmignore
  resources/reconciler/charts/component-reconcilers/Chart.yaml
  resources/reconciler/charts/component-reconcilers/templates/deployment.yaml
  resources/reconciler/charts/component-reconcilers/templates/rbac.yaml
  resources/reconciler/charts/component-reconcilers/templates/service.yaml
  resources/reconciler/charts/component-reconcilers/values.yaml
  resources/reconciler/charts/mothership-reconciler/.helmignore
  resources/reconciler/charts/mothership-reconciler/Chart.yaml
  resources/reconciler/charts/mothership-reconciler/templates/_helpers.tpl
  resources/reconciler/charts/mothership-reconciler/templates/deployment.yaml
  resources/reconciler/charts/mothership-reconciler/templates/mr-configmap.yaml
  resources/reconciler/charts/mothership-reconciler/templates/service.yaml
  resources/reconciler/charts/mothership-reconciler/values.yaml
  resources/reconciler/charts/postgresql/.helmignore
  resources/reconciler/charts/postgresql/Chart.yaml
  resources/reconciler/charts/postgresql/README.md
  resources/reconciler/charts/postgresql/templates/NOTES.txt
  resources/reconciler/charts/postgresql/templates/_helpers.tpl
  resources/reconciler/charts/postgresql/templates/configmap.yaml
  resources/reconciler/charts/postgresql/templates/extended-config-configmap.yaml
  resources/reconciler/charts/postgresql/templates/init-db-config-map.yaml
  resources/reconciler/charts/postgresql/templates/initialization-configmap.yaml
  resources/reconciler/charts/postgresql/templates/metrics-svc.yaml
  resources/reconciler/charts/postgresql/templates/networkpolicy.yaml
  resources/reconciler/charts/postgresql/templates/secrets.yaml
  resources/reconciler/charts/postgresql/templates/serviceaccount.yaml
  resources/reconciler/charts/postgresql/templates/servicemonitor.yaml
  resources/reconciler/charts/postgresql/templates/statefulset-slaves.yaml
  resources/reconciler/charts/postgresql/templates/statefulset.yaml
  resources/reconciler/charts/postgresql/templates/svc-headless.yaml
  resources/reconciler/charts/postgresql/templates/svc-read.yaml
  resources/reconciler/charts/postgresql/templates/svc.yaml
  resources/reconciler/charts/postgresql/values.yaml
  resources/reconciler/requirements.yaml
  resources/reconciler/templates/_helpers.tpl
  resources/reconciler/values.yaml
  scripts/kcversion.sh
  scripts/reconcilernames.go
Labels: size/XXL, lgtm

#328 Fix statefulset check
  pkg/reconciler/kubernetes/progress/progress.go
Labels: lgtm, size/XS

#345 Check for orphan ops and clean them up
  pkg/scheduler/worker/workerpool.go
Labels: lgtm, size/S

#341 Initial audit log implementation
  cmd/mothership/mothership/start/auditlog.go
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/options.go
  go.mod
  go.sum
Labels: lgtm, size/L

#356 Patch the JWKS secret only when necessary
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/ory/action_test.go
Labels: size/M, lgtm, area/security

#347 Fix waiting for resources after rolling update
  pkg/reconciler/kubernetes/progress/progress.go
  pkg/reconciler/kubernetes/progress/progress_test.go
  pkg/reconciler/kubernetes/progress/ready.go
  pkg/reconciler/kubernetes/progress/ready_test.go
  pkg/reconciler/kubernetes/progress/testdata/all.yaml
  pkg/reconciler/kubernetes/progress/testdata/dep-after-rolling-update.yaml
  pkg/reconciler/kubernetes/progress/testdata/dep-before-rolling-update.yaml
  pkg/reconciler/kubernetes/progress/testdata/ds-after-rolling-update.yaml
  pkg/reconciler/kubernetes/progress/testdata/ds-before-rolling-update.yaml
  pkg/reconciler/kubernetes/progress/testdata/ss-after-rolling-update.yaml
  pkg/reconciler/kubernetes/progress/testdata/ss-before-rolling-update.yaml
  pkg/reconciler/kubernetes/progress/tracker.go
  pkg/reconciler/kubernetes/progress/tracker_test.go
Labels: size/XXL, lgtm

#354 Preserve existing pod-preset certs
  pkg/reconciler/instances/clusteressentials/action.go
  pkg/reconciler/instances/clusteressentials/action_test.go
  pkg/reconciler/instances/clusteressentials/clusteressentials.go
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/serverless/action.go
  pkg/reconciler/instances/utils/utils.go
Labels: lgtm, size/L

#335 Kyma cli / reconciler cli allow the definition of a url for a component
  cmd/mothership/local/local_test.go
  cmd/mothership/local/options.go
  internal/components/componentlist.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/workspace/factory.go
  pkg/reconciler/workspace/mocks/factory.go
Labels: lgtm, size/L

#361 Refine state checks
  pkg/model/clusterstatus.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/service/scheduler.go
  pkg/scheduler/service/scheduler_test.go
  pkg/scheduler/service/transition.go
Labels: lgtm, size/L

#355 integrate istio uninstall action
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/instances/istio/istio_test.go
  pkg/reconciler/instances/istio/test_files/0.0.0/installation/resources/crds/.gitignore
  pkg/reconciler/instances/istio/test_files/0.0.0/resources/istio-configuration/Chart.yaml
  pkg/reconciler/instances/istio/test_files/0.0.0/workspace-ready.yaml
Labels: lgtm, size/L, area/service-mesh

#370 Generate value of SecretsCookie in Ory Hydra secret
  pkg/reconciler/instances/ory/db/db.go
Labels: bug, lgtm, size/XS, area/security

#351 Add stop operation feature
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/http.go
  openapi/external_api.yaml
  pkg/keb/model_gen.go
  pkg/repository/errors.go
  pkg/repository/errors_test.go
  pkg/repository/repository.go
  pkg/scheduler/service/transition.go
  scripts/lint.sh
Labels: lgtm, size/L

#371 Remove test scripts moved to control-plane
  scripts/e2e-test/get-reconcile-status.sh
  scripts/e2e-test/reconcile-kyma.sh
  scripts/e2e-test/request-reconcile.sh
  scripts/e2e-test/template.json
Labels: lgtm, size/L

#382 Git Toggle
  pkg/reconciler/chart/helm.go
  pkg/reconciler/chart/provider.go
Labels: lgtm, size/XS

#383 Fix kubeclient bug causing resource manifests not to regenerate.
  pkg/reconciler/kubernetes/kubeclient/kubeclient.go
  pkg/reconciler/kubernetes/progress/testdata/all.yaml
Labels: lgtm, size/S

#385 Fix security issue with containerd library
  go.mod
  go.sum
  pkg/reconciler/service/runner.go
Labels: size/XL, lgtm

#366 Change istioctl image to use Kyma external repository
  Dockerfile.cr
Labels: lgtm, size/XS, area/reconciler, area/service-mesh

#363 Ensure namespaces will also be processed by interceptors
  pkg/reconciler/kubernetes/adapter/adapter.go
  pkg/reconciler/kubernetes/adapter/adapter_test.go
Labels: lgtm, size/L

#387 Upgrade Go JWT package Dependency
  cmd/mothership/mothership/start/auditlog.go
  go.mod
  go.sum
Labels: lgtm, size/XS

#391 Add runtime-monitoring-agent (rma) component reconciler
  CODEOWNERS
  openapi/external_api.yaml
  pkg/keb/model_gen.go
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/rma/integration_action.go
  pkg/reconciler/instances/rma/lazy_client.go
  pkg/reconciler/instances/rma/rma.go
  pkg/reconciler/kubernetes/kubeclient/kubeclient.go
  pkg/reconciler/model.go
  pkg/scheduler/invoker/invoker.go
  pkg/scheduler/invoker/test.go
Labels: lgtm, size/L

#362 Create State helper generator
  Makefile
  cmd/generators/model-helper/main.go
  pkg/keb/helpers.go
Labels: lgtm, size/L

#394 fix nil-pointer error
  cmd/mothership/local/cmd.go
Labels: lgtm, size/XS

#401 Allign patching istio-sidecar-injector with Kyma 1.x behaviour
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
Labels: bug, lgtm, size/S, area/service-mesh

#397 RMA: Turn level of frequent/common log messages to debug
  pkg/reconciler/instances/rma/integration_action.go
Labels: lgtm, size/XS

#381 Add a delete flag to the local mothership command
  cmd/mothership/local/cmd.go
  cmd/mothership/local/options.go
Labels: size/S

#409 RMA: remove dependency on SimpleRESTClientGetter
  pkg/reconciler/instances/rma/lazy_client.go
Labels: lgtm, size/S

#410 Upgrade migrate pkg to get newest containerd pkg
  go.mod
  go.sum
Labels: lgtm, size/L

#403 Make replace work for ClusterIP services
  pkg/reconciler/instances/clusteressentials/action_test.go
  pkg/reconciler/instances/serverless/action_test.go
  pkg/reconciler/service/install.go
  pkg/reconciler/service/servicesinterceptor.go
  pkg/reconciler/service/servicesinterceptor_test.go
  pkg/reconciler/service/test/service.yaml
Labels: lgtm, size/L

#393 Add kubeclient unittest
  pkg/reconciler/kubernetes/kubeclient/kubeclient_test.go
  pkg/reconciler/kubernetes/kubeclient/test/manifest.yaml
Labels: lgtm, size/L

#413 Upgrade golang base image version
  Dockerfile.cr
  Dockerfile.mr
Labels: lgtm, size/XS

#380 Istio downgrade is now permitted upto one minor
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/istio_test.go
  pkg/reconciler/instances/istio/test_files/1.11.2/installation/resources/crds/.gitignore
  pkg/reconciler/instances/istio/test_files/1.11.2/resources/istio-configuration/Chart.yaml
  pkg/reconciler/instances/istio/test_files/1.11.2/resources/istio-configuration/templates/istio-operator.yaml
  pkg/reconciler/instances/istio/test_files/1.11.2/workspace-ready.yaml
Labels: size/XL, lgtm, area/reconciler

#384 Refactor kubernetes reconciler pkg to minimize exposing internals
  cmd/reconciler/start/service/integration_test.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/instances/connectivityproxy/connectivityproxy.go
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/rma/lazy_client.go
  pkg/reconciler/kubernetes/adapter.go
  pkg/reconciler/kubernetes/adapter_test.go
  pkg/reconciler/kubernetes/client.go
  pkg/reconciler/kubernetes/internal/kubeclient.go
  pkg/reconciler/kubernetes/internal/kubeclient_test.go
  pkg/reconciler/kubernetes/internal/replace.go
  pkg/reconciler/kubernetes/internal/simplerestclientgetter.go
  pkg/reconciler/kubernetes/internal/test/manifest.yaml
  pkg/reconciler/kubernetes/internal/unstructured.go
  pkg/reconciler/kubernetes/internal/warnings.go
  pkg/reconciler/kubernetes/internal/warnings_test.go
  pkg/reconciler/kubernetes/kubeclient/unstructured_test.go
  pkg/reconciler/kubernetes/progress/tracker_test.go
  pkg/reconciler/kubernetes/test/unittest-with-namespace.yaml
  pkg/reconciler/kubernetes/test/unittest-without-namespace.yaml
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/service/servicesinterceptor_test.go
  pkg/reconciler/workspace/factory.go
Labels: lgtm, size/L

#414 Exclude NotFound from unrecoverable errors in serviceinterceptor
  pkg/reconciler/service/servicesinterceptor.go
Labels: lgtm, size/XS

#417 Fix issue with wrong namespace resolution
  pkg/reconciler/service/noupdateinterceptor.go
  pkg/reconciler/service/servicesinterceptor.go
  pkg/scheduler/invoker/localinvoker.go
Labels: size/M, lgtm

#421 Remove migrate binary from the image
  Dockerfile.mr
Labels: lgtm, size/XS

#411 Add status field to reconciliations table
  cmd/mothership/mothership/start/http.go
  configs/db/postgres/000006_add_cluster_status_to_reconcilation.down.sql
  configs/db/postgres/000006_add_cluster_status_to_reconcilation.up.sql
  configs/db/sqlite/reconciler.sql
  pkg/model/converter.go
  pkg/model/reconciliationentity.go
  pkg/scheduler/reconciliation/persistent.go
Labels: size/M, lgtm, release blocker

#372 Fix auditlog format
  cmd/mothership/mothership/start/auditlog.go
  cmd/mothership/mothership/start/auditlog_test.go
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/integration_test.go
  cmd/mothership/mothership/start/options.go
Labels: lgtm, size/L

#430 Fix reconciliations migration
  configs/db/postgres/000006_add_cluster_status_to_reconcilation.up.sql
Labels: lgtm, size/XS

#426 Do not reconcile jobs
  pkg/reconciler/kubernetes/adapter.go
  pkg/reconciler/kubernetes/adapter_test.go
  pkg/reconciler/kubernetes/client.go
  pkg/reconciler/kubernetes/mocks/client.go
  pkg/reconciler/service/noupdateinterceptor.go
  pkg/reconciler/service/noupdateinterceptor_test.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/service/servicesinterceptor.go
  pkg/reconciler/service/test/noupdateinterceptor.yaml
Labels: lgtm, size/L

#425 Drop .WithDependencies() from component reconcilers
  README.md
  pkg/reconciler/instances/busolamigrator/busola.go
  pkg/reconciler/instances/eventing/eventing.go
  pkg/reconciler/instances/example/example.go
Labels: lgtm, size/XS

#434 Fix statefulset reconciliation
  pkg/reconciler/instances/clusteressentials/action_test.go
  pkg/reconciler/instances/serverless/action_test.go
  pkg/reconciler/service/install.go
  pkg/reconciler/service/noupdateinterceptor_test.go
  pkg/reconciler/service/statefulsetinterceptor.go
  pkg/reconciler/service/statefulsetinterceptor_test.go
  pkg/reconciler/service/test/statefulsetinterceptor.yaml
Labels: lgtm, size/L

#429 Add liveness and readiness checks
  cmd/mothership/mothership/start/http.go
  cmd/reconciler/start/service/http.go
  pkg/db/interface.go
  pkg/db/mocks.go
  pkg/db/postgres.go
  pkg/db/sqlite.go
  pkg/reconciler/service/workerpool.go
Labels: size/M, lgtm

#404 Fix race-condition in file downloads
  cmd/mothership/local/cmd.go
  cmd/reconciler/start/service/integration_test.go
  go.mod
  go.sum
  pkg/reconciler/chart/factory.go
  pkg/reconciler/chart/factory_test.go
  pkg/reconciler/chart/helm.go
  pkg/reconciler/chart/mocks/factory.go
  pkg/reconciler/chart/mocks/provider.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/chart/test/local/installation/resources/crds/.gitignore
  pkg/reconciler/chart/test/local/resources/.gitignore
  pkg/reconciler/chart/test/unittest-kyma/resources/archives/testmeplz.tar.gz
  pkg/reconciler/chart/test/unittest-kyma/resources/archives/testmeplz.zip
  pkg/reconciler/chart/workspace.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/mocks/istio_performer.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/istio_test.go
  pkg/reconciler/instances/ory/action_test.go
  pkg/reconciler/instances/rafter/action_test.go
  pkg/reconciler/service/action.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/workspace/factory.go
  pkg/reconciler/workspace/factory_test.go
  pkg/reconciler/workspace/mocks/factory.go
  pkg/reconciler/workspace/test/.gitignore
  pkg/reconciler/workspace/workspace.go
Labels: size/XXL, lgtm

#438 Add pg_isready command to postgres.sh
  scripts/postgres.sh
Labels: lgtm, size/S

#440 provide fix for pg_isready
  scripts/postgres.sh
Labels: lgtm, size/XS

#441 Move metrics and health endpoints to a subrouter
  cmd/mothership/mothership/start/http.go
Labels: lgtm, size/XS

#353 Configuration Improvements
  pkg/reconciler/chart/factory.go
  pkg/reconciler/git/clone.go
  pkg/reconciler/git/clone_test.go
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
  pkg/reconciler/instances/connectivityproxy/command.go
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/instances/connectivityproxy/connectivityproxy.go
  pkg/reconciler/instances/connectivityproxy/mocks/commands.go
  pkg/reconciler/kubernetes/adapter.go
  pkg/reconciler/kubernetes/client.go
  pkg/reconciler/kubernetes/internal/kubeclient.go
  pkg/reconciler/kubernetes/mocks/client.go
Labels: enhancement, lgtm, size/L, area/reconciler

#445 Split API, metrics and health routes
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/integration_test.go
Labels: size/M, lgtm

#446 Fix bug in post action calls in runner
  pkg/reconciler/service/runner.go
Labels: lgtm, size/XS

#427 Modify reconciliation info endpoint
  cmd/mothership/mothership/start/helpers.go
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/integration_test.go
  internal/converters/reconciliation_info.go
  internal/converters/reconciliation_info_test.go
  openapi/external_api.yaml
  pkg/keb/model_gen.go
  pkg/repository/errors.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/server/error.go
Labels: lgtm, size/L

#392 removed migrateeventtypeprefixconfigstep eventing preaction
  pkg/reconciler/instances/eventing/preaction/migrateeventtypeprefixconfigstep.go
  pkg/reconciler/instances/eventing/preaction/migrateeventtypeprefixconfigstep_test.go
  pkg/reconciler/instances/eventing/preaction/preaction.go
Labels: lgtm, size/L

#437 Add get config endpoint
  cmd/mothership/mothership/start/http.go
  internal/converters/config.go
  openapi/external_api.yaml
  pkg/keb/model_gen.go
Labels: size/M, lgtm

#455 Default Main Version for Components with URL
  pkg/scheduler/invoker/invoker.go
Labels: lgtm, size/S

#431 Add preaction to delete the Nats-operator resources if any remain
  pkg/reconciler/instances/eventing/preaction/preaction.go
  pkg/reconciler/instances/eventing/preaction/removenatsoperatorstep.go
  pkg/reconciler/instances/eventing/preaction/removenatsoperatorstep_test.go
  pkg/reconciler/kubernetes/adapter.go
  pkg/reconciler/kubernetes/client.go
  pkg/reconciler/kubernetes/mocks/client.go
Labels: lgtm, size/L

#428 Fix Denial_Of_Service_Resource_Exhaustion
  cmd/mothership/mothership/start/http.go
  pkg/files/reader.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/heartbeat/heartbeat_test.go
  pkg/reconciler/instances/istio/istioctl/commander.go
  pkg/server/error.go
  pkg/server/params.go
Labels: size/M, lgtm

#449 Support parallel pre-components for installation / deletion
  cmd/mothership/local/options.go
  configs/reconciler-unittest.yaml
  configs/reconciler.yaml
  pkg/model/clusterconfigentity.go
  pkg/model/clusterconfigentity_test.go
  pkg/reconciler/chart/factory_test.go
  pkg/reconciler/chart/test/factory/.gitignore
  pkg/reconciler/service/statefulsetinterceptor_test.go
  pkg/reconciler/service/test/statefulsetinterceptor.yaml
  pkg/scheduler/config/config.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/run.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/service/scheduler.go
  pkg/scheduler/service/transition.go
Labels: lgtm, size/L

#461 Update istio to 1.12.0
  Dockerfile.cr
Labels: lgtm, size/XS

#376 Kuberentes client has to validate resources before applying them on k8s
  go.mod
  go.sum
  pkg/reconciler/kubernetes/adapter.go
Labels: lgtm, size/S

#452 Error of missing GIT-revision has to include the repo-URL
  pkg/reconciler/git/clone.go
  pkg/reconciler/service/install.go
Labels: lgtm, size/S

#473 Fix metric labels
  pkg/metrics/reconciliation_status.go
Labels: lgtm, size/S

#477 Revert "Update istio to 1.12.0"
  Dockerfile.cr
Labels: lgtm, size/XS

#470 Adjust clusterIP in the service interceptor if it is equal to None
  pkg/reconciler/service/servicesinterceptor.go
  pkg/reconciler/service/servicesinterceptor_test.go
  pkg/reconciler/service/test/servicesinterceptor.yaml
Labels: size/M, lgtm

#479 Revert "Kuberentes client has to validate resources before applying t…
  go.mod
  go.sum
  pkg/reconciler/kubernetes/adapter.go
Labels: lgtm, size/S

#486 Missing Nil Check in CP Component Reconciler
  pkg/reconciler/instances/connectivityproxy/action.go
Labels: lgtm, size/XS

#488 Fix profile file lookup
  pkg/reconciler/chart/helm.go
Labels: lgtm, size/XS

#489 Change the restriction in Istio to allow using istioctl among one minor comparing to the Istio version
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
Labels: size/M, lgtm, area/reconciler, area/service-mesh

#492 Fix missing encryption for comps
  pkg/model/clusterconfigentity.go
Labels: lgtm, size/XS

#499 Transition fix: use Get instead of GetLatest
  pkg/scheduler/service/scheduler.go
  pkg/scheduler/service/scheduler_test.go
  pkg/scheduler/service/transition.go
  pkg/scheduler/service/transition_test.go
Labels: lgtm, size/S, required-for-kyma2.0

#487 Add retention mechanism
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/integration_test.go
  cmd/mothership/mothership/start/options.go
  cmd/mothership/mothership/start/scheduler.go
  pkg/db/validator.go
  pkg/scheduler/reconciliation/filter.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/service/cleaner.go
  pkg/scheduler/service/cleaner_test.go
  pkg/scheduler/service/run.go
  pkg/scheduler/service/run_test.go
Labels: enhancement, lgtm, size/L, area/reconciler

#484 Patch resources that cannot be replaced
  go.mod
  go.sum
  pkg/reconciler/instances/serverless/action.go
  pkg/reconciler/kubernetes/internal/kubeclient.go
  pkg/reconciler/kubernetes/internal/patcher.go
  pkg/reconciler/kubernetes/internal/replace.go
  pkg/reconciler/kubernetes/internal/updatestrategyresolver.go
  pkg/reconciler/kubernetes/internal/updatestrategyresolver_test.go
  pkg/reconciler/service/install.go
  pkg/reconciler/service/noupdateinterceptor.go
  pkg/reconciler/service/noupdateinterceptor_test.go
  pkg/reconciler/service/statefulsetinterceptor.go
  pkg/reconciler/service/statefulsetinterceptor_test.go
Labels: size/XL, lgtm

#496 Reconcile Cluster which are in error State
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/cluster/mock.go
  pkg/cluster/statusfilter.go
  pkg/model/clusterstatus.go
  pkg/scheduler/service/bookkeeper.go
  pkg/scheduler/service/run_test.go
Labels: lgtm, size/L
