Repository kyma-incubator/reconciler, pull requests merged in 2021-06, with the labels that each got.

#6 Move connection-factory new-fct to db package
  cmd/config/config.go
  cmd/config/create/value/cmd.go
  cmd/config/get/value/cmd.go
  pkg/config/repository_test.go
  pkg/db/factory.go
Labels: lgtm

#5 Add E2E test case
  cmd/config/create/value/cmd.go
  pkg/config/bucketmerger.go
  pkg/config/bucketmerger_test.go
  pkg/config/end2end_test.go
  pkg/config/kvrepository.go
  pkg/config/kvrepository_test.go
Labels: lgtm

#7 Move unittest-db config to config-directory
  configs/db/migrate/README.md
  configs/db/postgres/000001_configuration-management.down.sql
  configs/db/postgres/000001_configuration-management.up.sql
  configs/db/postgres/README.md
  configs/db/sqlite/configuration-management.sql
  configs/reconciler-unittest.yaml
  pkg/config/repository_test.go
  scripts/postgres.sh
Labels: lgtm

#8 Make cache dependencies optional
  configs/db/postgres/README.md
  pkg/config/cachedepmanager_test.go
  pkg/config/cacherepository.go
  pkg/config/cacherepository_test.go
  pkg/config/end2end_test.go
  pkg/config/keyentity.go
  pkg/config/kvrepository.go
  pkg/config/kvrepository_test.go
  pkg/config/repository.go
Labels: lgtm

#9 Fix issue with nested db transactions
  pkg/config/kvrepository.go
Labels: lgtm

#23 Improve .gitignore and makefile
  .gitignore
  Makefile
  pkg/cluster/config.go
Labels: lgtm, size/M

#14 Add issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation-improvement.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/security-vulnerability.md
  .github/ISSUE_TEMPLATE/support-request.md
  .gitignore
  CODEOWNERS
Labels: lgtm, size/L

#24 Add readme and licence
  LICENCE
  README.md
Labels: lgtm, size/L

#27 Add workspace factory
  README.md
  configs/db/postgres/README.md
  go.mod
  go.sum
  pkg/files/exists.go
  pkg/git/clone.go
  pkg/git/clone_test.go
  pkg/git/testdata/repo.tgz
  pkg/test/expensive.go
  pkg/test/expensive_test.go
  pkg/workspace/factory.go
  pkg/workspace/factory_test.go
  pkg/workspace/test/.gitignore
Labels: lgtm, size/L

#28 Add reconciler service cmd
  Makefile
  cmd/config/config.go
  cmd/config/create/key/cmd.go
  cmd/config/create/key/options.go
  cmd/config/create/value/cmd.go
  cmd/config/create/value/options.go
  cmd/config/get/value/cmd.go
  cmd/config/get/value/options.go
  cmd/main.go
  cmd/service/service.go
  cmd/service/start/cmd.go
  cmd/service/start/options.go
  configs/reconciler-unittest.yaml
  configs/reconciler.yaml
  pkg/db/factory.go
  pkg/db/testfactory.go
Labels: lgtm, size/L

#25 Implement cluster-inventory
  cmd/example/register-cluster_complicated-exemple.json
  cmd/example/register-cluster_simple-exemple.json
  cmd/example/register-cluster_structure.json
  cmd/main.go
  cmd/service/start/cmd.go
  configs/db/postgres/000001_configuration-management.down.sql
  configs/db/postgres/000001_configuration-management.up.sql
  configs/db/sqlite/configuration-management.sql
  go.mod
  go.sum
  internal/cli/options.go
  internal/cli/test/yaml.txt
  pkg/cluster/cluster.go
  pkg/cluster/config.go
  pkg/cluster/inventory.go
  pkg/cluster/mock.go
  pkg/cluster/state.go
  pkg/db/columnhandler.go
  pkg/db/query.go
  pkg/model/clusterconfigentity.go
  pkg/model/clusterentity.go
  pkg/model/clusterpropentity.go
  pkg/model/clusterstatus.go
  pkg/model/clusterstatusentity.go
  pkg/model/datatype.go
  pkg/model/datatype_test.go
Labels: lgtm, size/XXL
