Repository kyma-incubator/reconciler, pull requests merged in 2022-08, with the labels that each got.

#1141 Implement check for pods that should have sidecar in Proxy Reset
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/actions/mocks/istio_performer.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/reset/config/config.go
  pkg/reconciler/instances/istio/reset/data/gatherer.go
  pkg/reconciler/instances/istio/reset/data/gatherer_test.go
  pkg/reconciler/instances/istio/reset/data/mocks/Gatherer.go
  pkg/reconciler/instances/istio/reset/proxy/proxy.go
  pkg/reconciler/instances/istio/reset/proxy/proxy_test.go
Labels: lgtm, size/L, area/service-mesh, area/security

#1143 IstioStatus struct refactoring
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/mocks/CommanderResolver.go
  pkg/reconciler/instances/istio/actions/mocks/IstioPerformer.go
  pkg/reconciler/instances/istio/actions/mocks/testCommanderResolver.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/bootstrap.go
  pkg/reconciler/instances/istio/helpers/version_helper.go
  pkg/reconciler/instances/istio/istio_test.go
  pkg/reconciler/instances/istio/istioctl/mocks/version_checker.go
  pkg/reconciler/instances/istio/istioctl/resolver.go
  pkg/reconciler/instances/istio/istioctl/resolver_internal_test.go
  pkg/reconciler/instances/istio/istioctl/resolver_test.go
  pkg/reconciler/instances/istio/reset/config/config.go
  pkg/reconciler/instances/istio/reset/data/gatherer.go
  pkg/reconciler/instances/istio/reset/data/gatherer_test.go
  pkg/reconciler/instances/istio/reset/data/mocks/Gatherer.go
  pkg/reconciler/instances/istio/reset/mocks/Action.go
  pkg/reconciler/instances/istio/reset/mocks/Handler.go
  pkg/reconciler/instances/istio/reset/mocks/IstioProxyReset.go
  pkg/reconciler/instances/istio/reset/mocks/Matcher.go
  pkg/reconciler/instances/istio/reset/mocks/labelSelectorGetter.go
  pkg/reconciler/instances/istio/reset/proxy/proxy.go
  pkg/reconciler/instances/istio/reset/proxy/proxy_test.go
Labels: size/XXL, lgtm, area/security

#1146 Revert "IstioStatus struct refactoring"
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/mocks/CommanderResolver.go
  pkg/reconciler/instances/istio/actions/mocks/istio_performer.go
  pkg/reconciler/instances/istio/actions/mocks/testCommanderResolver.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/bootstrap.go
  pkg/reconciler/instances/istio/helpers/version_helper.go
  pkg/reconciler/instances/istio/istio_test.go
  pkg/reconciler/instances/istio/istioctl/mocks/version_checker.go
  pkg/reconciler/instances/istio/istioctl/resolver.go
  pkg/reconciler/instances/istio/istioctl/resolver_internal_test.go
  pkg/reconciler/instances/istio/istioctl/resolver_test.go
  pkg/reconciler/instances/istio/reset/config/config.go
  pkg/reconciler/instances/istio/reset/data/gatherer.go
  pkg/reconciler/instances/istio/reset/data/gatherer_test.go
  pkg/reconciler/instances/istio/reset/data/mocks/Gatherer.go
  pkg/reconciler/instances/istio/reset/mocks/Action.go
  pkg/reconciler/instances/istio/reset/mocks/Handler.go
  pkg/reconciler/instances/istio/reset/mocks/IstioProxyReset.go
  pkg/reconciler/instances/istio/reset/mocks/Matcher.go
  pkg/reconciler/instances/istio/reset/mocks/labelSelectorGetter.go
  pkg/reconciler/instances/istio/reset/proxy/proxy.go
  pkg/reconciler/instances/istio/reset/proxy/proxy_test.go
Labels: size/XXL, lgtm, area/security

#1152 Revert Only patch new istio webhook(#1139)
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
Labels: kind/bug, lgtm, size/L, area/service-mesh, area/security

#1153 Remove sc-migration reconciler
  CODEOWNERS
  go.mod
  go.sum
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/scmigration/action.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/broker.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/class.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/doc.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/filter.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/plan.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/plan_reference.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/recalculate.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/register.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/types.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/instances/scmigration/btp_operator_migration.go
  pkg/reconciler/instances/scmigration/filter/helper.go
  pkg/reconciler/instances/scmigration/filter/predicate.go
  pkg/reconciler/instances/scmigration/filter/properties.go
  pkg/reconciler/instances/scmigration/helm_broker.go
  pkg/reconciler/instances/scmigration/resource_cleanup.go
  pkg/reconciler/instances/scmigration/sc_removal.go
  pkg/reconciler/instances/scmigration/scmigration.go
  pkg/reconciler/instances/scmigration/service_catalog.go
  pkg/reconciler/instances/scmigration/service_catalog_addons.go
  pkg/reconciler/instances/scmigration/service_manager_proxy.go
  pkg/reconciler/instances/scmigration/utils.go
Labels: size/XXL, lgtm

#1145 Adding label for sidecar injection in kyma-namespace
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/actions/mocks/commander_resolver.go
  pkg/reconciler/instances/istio/actions/mocks/istio_performer.go
  pkg/reconciler/instances/istio/actions/mocks/testCommanderResolver.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/reset/config/config.go
  pkg/reconciler/instances/istio/reset/data/gatherer.go
  pkg/reconciler/instances/istio/reset/data/gatherer_test.go
  pkg/reconciler/instances/istio/reset/data/mocks/Gatherer.go
  pkg/reconciler/instances/istio/reset/proxy/mocks/istio_proxy_reset.go
  pkg/reconciler/instances/istio/reset/proxy/proxy.go
  pkg/reconciler/instances/istio/reset/proxy/proxy_test.go
  pkg/reconciler/instances/istio/test_files/istio-sidecar-disabled/values.yaml
  pkg/reconciler/service/nsinterceptor.go
  pkg/reconciler/service/nsinterceptor_test.go
Labels: lgtm, size/L, area/security

#1156 update goats CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/XS

#1158 breaking change: upgrade to go 1.18.5 - Protecode vulnerabilities
  Dockerfile.cr
  Dockerfile.mr
  go.mod
Labels: lgtm, size/XS

#1160 Add FinalizerIntercepter
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/kubernetes/client.go
  pkg/reconciler/kubernetes/mocks/client.go
  pkg/reconciler/service/finalizerinterceptor.go
  pkg/reconciler/service/finalizerinterceptor_test.go
  pkg/reconciler/service/install.go
  pkg/reconciler/service/test/finalizerinterceptor.yaml
Labels: lgtm, size/L

#1161 Bump istio to 1.14.3 in reconciler
  Dockerfile.cr
Labels: lgtm, size/XS

#1164 Remove unsupported Istio versions from reconciler
  Dockerfile.cr
Labels: lgtm, size/XS

#1163 Add preaction to delete configMaps no longer used in eventing
  pkg/reconciler/instances/eventing/preaction/cleanupDashboardConfigMaps.go
  pkg/reconciler/instances/eventing/preaction/cleanupDashboardConfigMaps_test.go
  pkg/reconciler/instances/eventing/preaction/preaction.go
Labels: lgtm, size/L

#1170 Add check for nil map
  pkg/reconciler/instances/istio/reset/data/gatherer.go
Labels: lgtm, size/XS, area/security

#1075 Drop rafter reconciler
  CODEOWNERS
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/rafter/action.go
  pkg/reconciler/instances/rafter/action_test.go
  pkg/reconciler/instances/rafter/rafter.go
  pkg/reconciler/instances/rafter/test_files/0.0.0/installation/resources/crds/.gitignore
  pkg/reconciler/instances/rafter/test_files/0.0.0/resources/rafter/charts/controller-manager/charts/minio/values.yaml
  pkg/reconciler/instances/rafter/test_files/0.0.0/workspace-ready.yaml
  pkg/reconciler/instances/rafter/test_files/0.0.1/installation/resources/crds/.gitignore
  pkg/reconciler/instances/rafter/test_files/0.0.1/resources/rafter/charts/controller-manager/charts/minio/values.yaml
  pkg/reconciler/instances/rafter/test_files/0.0.1/workspace-ready.yaml
  pkg/reconciler/instances/rafter/test_files/invalid_values.yaml
  pkg/reconciler/instances/rafter/test_files/valid-values.yaml
Labels: lgtm, size/L
