Repository kyma-incubator/reconciler, pull requests merged in 2022-06, with the labels that each got.

#1088 Remove istioctl 1.11.4 from Dockerfile
  Dockerfile.cr
Labels: lgtm, size/XS

#1105 add istioctl 1.14.0 to dockerfile
  Dockerfile.cr
Labels: lgtm, size/XS

#1104 upgrade runc
  go.mod
  go.sum
Labels: lgtm, size/XS

#1111 Use always Kyma Repository as default
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner.go
Labels: lgtm, size/S

#1108 Enable reconciliation without Service Catalog and BTP Operator
  pkg/reconciler/instances/connectivityproxy/search.go
  pkg/reconciler/instances/connectivityproxy/search_test.go
Labels: kind/bug, size/M, lgtm, area/application-connector

#1114 Update istio 1.14.0 to 1.14.1
  Dockerfile.cr
Labels: lgtm, size/XS

#1116 Upgrade containerd to latest
  go.mod
  go.sum
Labels: lgtm, size/L

#1118 Stop retry if err is no such host
  pkg/reconciler/service/runner.go
Labels: lgtm, size/XS

#1120 Wait for pods availability in Ory reconciler test
  pkg/reconciler/instances/ory/test/ory_integration_test.go
Labels: lgtm, size/S, area/api-gateway, kind/failing-test, area/tests
