Repository kyma-incubator/reconciler, pull requests merged in 2022-02, with the labels that each got.

#743 Update CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/XS

#745 change-postgres-isolation-level
  pkg/db/postgres.go
Labels: lgtm, size/XS

#752 revert-custom-metrics-feature
  cmd/mothership/local/cmd.go
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/options.go
  cmd/mothership/mothership/start/scheduler.go
  cmd/reconciler/start/service/http.go
  cmd/reconciler/start/service/integration_test.go
  configs/db/postgres/000010_worker_pool_occupancy.up.sql
  configs/db/sqlite/reconciler.sql
  internal/persistency/registry.go
  openapi/internal_api.yaml
  pkg/metrics/metrics.go
  pkg/metrics/workerpool_occupancy.go
  pkg/model/workerpooloccupentity.go
  pkg/reconciler/heartbeat/heartbeat.go
  pkg/reconciler/heartbeat/heartbeat_test.go
  pkg/reconciler/http.go
  pkg/reconciler/model_gen.go
  pkg/reconciler/occupancy/workerpooloccupancy.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/service/workerpool.go
  pkg/reconciler/service/workerpool_test.go
  pkg/scheduler/invoker/remoteinvoker.go
  pkg/scheduler/invoker/remoteinvoker_test.go
  pkg/scheduler/occupancy/inmemory.go
  pkg/scheduler/occupancy/mock.go
  pkg/scheduler/occupancy/occupancy.go
  pkg/scheduler/occupancy/occupancy_test.go
  pkg/scheduler/occupancy/persistent.go
  pkg/scheduler/service/run.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/worker/workerpool.go
  pkg/scheduler/worker/workerpool_test.go
Labels: size/XXL, lgtm

#704 Istio and istio-configuration components
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/bootstrap.go
  pkg/reconciler/instances/istio/istio.go
Labels: lgtm, size/L, area/installation, area/service-mesh

#757 Fix non-considered pre-components and retry failing DB transactions
  cmd/mothership/mothership/start/scheduler.go
  cmd/reconciler/start/service/integration_test.go
  pkg/cluster/inventory_test.go
  pkg/db/testfactory.go
  pkg/db/transaction.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/service/scheduler_test.go
Labels: lgtm, size/L

#759 Fix DB transaction-retry
  pkg/db/transaction.go
  pkg/db/transaction_test.go
Labels: size/M, lgtm

#762 Revert debug logging on istio reconciler
  pkg/reconciler/instances/istio/istio.go
Labels: lgtm, size/XS

#764 Load Istio target version from values.yaml instead of Chart.yaml
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/istio_test.go
  pkg/reconciler/instances/istio/test_files/0.0.0/resources/istio-configuration/values.yaml
  pkg/reconciler/instances/istio/test_files/1.11.2/resources/istio-configuration/values.yaml
  pkg/reconciler/instances/istio/test_files/istio-test/values.yaml
Labels: size/M, lgtm

#722 Service Catalog migration resource cleanup
  pkg/reconciler/instances/scmigration/action.go
  pkg/reconciler/instances/scmigration/btp_operator_migration.go
  pkg/reconciler/instances/scmigration/helm_broker.go
  pkg/reconciler/instances/scmigration/resource_cleanup.go
  pkg/reconciler/instances/scmigration/sc_removal.go
  pkg/reconciler/instances/scmigration/service_catalog.go
  pkg/reconciler/instances/scmigration/service_catalog_addons.go
  pkg/reconciler/instances/scmigration/service_manager_proxy.go
Labels: size/XXL, lgtm

#763 Add reconciler disclaimers
  pkg/reconciler/instances/ory/db/db.go
  pkg/reconciler/instances/ory/jwks/jwks.go
Labels: lgtm, size/S, area/api-gateway

#778 Revert "Load Istio target version from values.yaml instead of Chart.yaml"
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/istio_test.go
  pkg/reconciler/instances/istio/test_files/0.0.0/resources/istio-configuration/values.yaml
  pkg/reconciler/instances/istio/test_files/1.11.2/resources/istio-configuration/values.yaml
  pkg/reconciler/instances/istio/test_files/istio-test/values.yaml
Labels: size/M, lgtm, area/reconciler, area/service-mesh

#779 Bookkeeper: reduce retry count for deletion
  pkg/scheduler/service/bookkeeper.go
  pkg/scheduler/service/bookkeepingtask.go
  pkg/scheduler/service/bookkeepingtask_test.go
Labels: size/M, lgtm

#771 Resolve issue when using Postgres for db unit test
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/integration_test.go
  pkg/cluster/inventory_test.go
  pkg/keb/test/cluster.go
  pkg/scheduler/reconciliation/filter.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/scheduler_test.go
  pkg/scheduler/worker/workerpool_test.go
Labels: lgtm, size/L

#777 Add finished property to reconciliations endpoint
  cmd/mothership/mothership/start/http.go
  openapi/external_api.yaml
  pkg/keb/model_gen.go
Labels: lgtm, size/XS

#792 fixed implementation of updateOperationRetryID to use its transaction object
  pkg/scheduler/reconciliation/persistent.go
Labels: lgtm, size/XS

#780 Replace SQLite with PosgresSQL for db unit test
  cmd/mothership/mothership/start/integration_test.go
  configs/reconciler-unittest.yaml
  pkg/db/testfactory.go
  scripts/postgres.sh
Labels: lgtm, size/S

#791 Workerpool metrics
  cmd/mothership/main.go
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/integration_test.go
  cmd/mothership/mothership/start/options.go
  cmd/mothership/mothership/start/scheduler.go
  cmd/mothership/mothership/start/test/requests/new_occupancy.json
  cmd/mothership/mothership/start/test/requests/update_occupancy.json
  cmd/reconciler/start/service/reconciler.go
  configs/db/postgres/000010_worker_pool_occupancy.up.sql
  configs/db/sqlite/reconciler.sql
  internal/cli/options.go
  internal/cli/test/test.go
  internal/persistency/registry.go
  pkg/metrics/metrics.go
  pkg/metrics/workerpool_occupancy.go
  pkg/model/occupancyentity.go
  pkg/reconciler/http.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/workerpool.go
  pkg/reconciler/service/workerpool_test.go
  pkg/scheduler/invoker/remoteinvoker.go
  pkg/scheduler/invoker/remoteinvoker_test.go
  pkg/scheduler/occupancy/inmemory.go
  pkg/scheduler/occupancy/mock.go
  pkg/scheduler/occupancy/occupancy.go
  pkg/scheduler/occupancy/occupancy_test.go
  pkg/scheduler/occupancy/persistent.go
  pkg/scheduler/service/run.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/worker/workerpool.go
  pkg/scheduler/worker/workerpool_test.go
Labels: size/XXL, lgtm

#805 Introduce annotation to ignore pod state
  pkg/reconciler/kubernetes/progress/ready.go
  pkg/reconciler/kubernetes/progress/ready_test.go
Labels: size/M, lgtm

#815 Istio integration tests
  pkg/reconciler/instances/istio/tests/helpers.go
  pkg/reconciler/instances/istio/tests/integration_test.go
Labels: lgtm, size/L

#817 Set task type from operation instead of cluster state
  pkg/scheduler/invoker/invoker.go
  pkg/scheduler/invoker/invoker_test.go
  pkg/scheduler/invoker/localinvoker_test.go
  pkg/scheduler/worker/worker.go
Labels: size/M, lgtm

#770 Ory test on evaluation
  pkg/reconciler/instances/ory/test/helpers.go
  pkg/reconciler/instances/ory/test/ory_integration_test.go
Labels: size/M, lgtm, area/api-gateway

#786 Istio-configuration reconciler README.md update
  pkg/reconciler/instances/istio/README.md
Labels: lgtm, size/S

#760 Fix DB transaction retry issue
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/cluster/mock.go
  pkg/db/interface.go
  pkg/db/mocks.go
  pkg/db/postgres.go
  pkg/db/query.go
  pkg/db/query_test.go
  pkg/db/sqlite.go
  pkg/db/transaction.go
  pkg/db/validator.go
  pkg/db/validator_test.go
  pkg/scheduler/service/bookkeepingtask.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/scheduler_test.go
  pkg/scheduler/worker/workerpool_test.go
Labels: lgtm, size/L

#824 RMA: Ensure avs-bridge deployment is absent pre-reconcile time
  pkg/reconciler/instances/rma/integration_action.go
  pkg/reconciler/instances/rma/integration_action_test.go
Labels: lgtm, size/S

#808 Expose processing duration metrics over Prometheus
  cmd/mothership/mothership/start/http.go
  configs/db/postgres/000011_metrics_processing_duration.down.sql
  configs/db/postgres/000011_metrics_processing_duration.up.sql
  configs/db/sqlite/reconciler.sql
  openapi/internal_api.yaml
  pkg/metrics/metrics.go
  pkg/metrics/processing_time.go
  pkg/model/operationentity.go
  pkg/reconciler/model_gen.go
  pkg/reconciler/service/runner.go
  pkg/scheduler/invoker/remoteinvoker.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/operation/filter.go
  pkg/scheduler/reconciliation/operation/filter_test.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/reconciliation/reconciliation_test.go
Labels: size/XL, lgtm

#796 Remove Pull Secret from Connectivity Proxy Reconciler
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/connectivityproxy.go
Labels: size/M, lgtm, area/connectivity-proxy

#776 Introduce reconciler mock component
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/mock/action.go
  pkg/reconciler/instances/mock/mock.go
Labels: lgtm, size/L

#832 Show initial DB error if entity not found by DB query
  pkg/repository/errors.go
Labels: lgtm, size/XS

#828 refactoring istio integration tests
  pkg/reconciler/instances/istio/tests/integration_test.go
Labels: size/M, lgtm

#819 Adjust metric of `not ready` clusters
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
Labels: size/M, lgtm

#838 Fix mock
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/connectivityproxy.go
  pkg/reconciler/instances/mock/action.go
Labels: size/M, lgtm

#839 enable debug for createPostgresConnectionFactory
  Makefile
  pkg/db/factory.go
Labels: lgtm, size/XS

#841 remove wrong namespace from istio integration test
  pkg/reconciler/instances/istio/tests/helpers.go
  pkg/reconciler/instances/istio/tests/integration_test.go
Labels: lgtm, size/XS

#822 Tracker timeout dump
  pkg/reconciler/kubernetes/adapter_test.go
  pkg/reconciler/kubernetes/progress/test/dumpable.yaml
  pkg/reconciler/kubernetes/progress/tracker.go
  pkg/reconciler/kubernetes/progress/tracker_test.go
  pkg/reconciler/kubernetes/tracker_test.go
  pkg/test/file.go
  pkg/test/kubeconfig.go
Labels: lgtm, size/L

#840 Leverage heartbeat to send processing Duration instead of own endpoint
  cmd/mothership/mothership/start/http.go
  openapi/internal_api.yaml
  pkg/reconciler/heartbeat/heartbeat.go
  pkg/reconciler/heartbeat/heartbeat_test.go
  pkg/reconciler/model_gen.go
  pkg/reconciler/service/runner.go
Labels: lgtm, size/L

#831 Occupancy-tracker-for-component-reconcilers
  cmd/reconciler/start/service/cmd.go
  cmd/reconciler/start/service/http.go
  cmd/reconciler/start/service/integration_test.go
  cmd/reconciler/start/service/reconciler.go
  cmd/reconciler/test/service/cmd.go
  pkg/reconciler/service/occupancytracker.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/workerpool.go
  pkg/reconciler/service/workerpool_test.go
Labels: lgtm, size/L

#845 fix istio versions comparison for new images
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
Labels: lgtm, size/L, area/service-mesh

#852 DB quick fix
  configs/db/postgres/000012_update_metrics_processing_duration.down.sql
  configs/db/postgres/000012_update_metrics_processing_duration.up.sql
  pkg/model/operationentity.go
Labels: lgtm, size/XS

#846 Fix duplicated order by clause
  pkg/scheduler/reconciliation/filter.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/reconciliation_test.go
Labels: lgtm, size/S

#855 Remove `FOR UDPATE` from select-stmts to improve performance
  pkg/db/query.go
  pkg/db/query_test.go
Labels: size/M, lgtm

#789 Well defined actions for Istio reconciler
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/instances/istio/istio_test.go
Labels: lgtm, size/L

#848 Fix Metrics Endpoint
  cmd/mothership/mothership/start/http.go
  pkg/metrics/metrics.go
  pkg/metrics/processing_time.go
  pkg/metrics/workerpool_occupancy.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/operation/filter.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/reconciliation/reconciliation_test.go
Labels: lgtm, size/L

#861 enable pprof for profiling data
  .pre-commit-config.yaml
  cmd/mothership/mothership/start/http.go
Labels: lgtm, size/XS

#860 Fix `cannot assign requested address`
  pkg/reconciler/callback/remote.go
  pkg/reconciler/chart/factory.go
  pkg/reconciler/instances/istio/tests/integration_test.go
  pkg/reconciler/service/occupancytracker.go
Labels: lgtm, size/XS

#858 Upgrade to Golang version 1.17.7
  Dockerfile.cr
  Dockerfile.mr
Labels: lgtm, size/XS

#865 Add type field to ReconciliationOperations
  internal/converters/reconciliation_info.go
  openapi/external_api.yaml
  pkg/keb/model_gen.go
Labels: lgtm, size/XS

#857 add support for mutation webhooks in Istio's newer versions
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/istio_test.go
Labels: lgtm, size/L, area/service-mesh

#872 Fix metrics error
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/persistent.go
Labels: lgtm, size/S

#876 Disbale processingDuration Metrics by default - Introduce Feature flags pkg
  cmd/mothership/main.go
  cmd/mothership/mothership/start/http.go
  internal/cli/options.go
  internal/cli/test/test.go
  internal/persistency/registry.go
  pkg/features/features.go
  pkg/features/features_test.go
  pkg/metrics/metrics.go
Labels: lgtm, size/L
