Repository kyma-incubator/reconciler, pull requests merged in 2022-01, with the labels that each got.

#611 #609 - default value in case no profile is passed
  cmd/mothership/local/cmd.go
Labels: lgtm, size/XS

#645 refactor CountRetries logic
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/db/testfactory.go
  pkg/model/clusterstatus.go
Labels: lgtm, size/L

#646 Fix helm chart pathing bug
  pkg/reconciler/chart/component.go
  pkg/reconciler/chart/factory.go
  pkg/reconciler/chart/helm.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/chart/workspace.go
Labels: size/M, lgtm

#640 Allow user to get Cluster State
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/integration_test.go
  openapi/external_api.yaml
  pkg/keb/model_gen.go
  pkg/scheduler/invoker/localinvoker_test.go
  pkg/scheduler/invoker/remoteinvoker_test.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/operation/filter.go
  pkg/scheduler/reconciliation/operation/filter_test.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/bookkeeper.go
  pkg/scheduler/service/bookkeeper_test.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/run.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/service/scheduler_test.go
  pkg/scheduler/worker/worker.go
Labels: size/XL, lgtm

#586 Protect endless reconciliation of operations - 245
  cmd/mothership/mothership/start/http.go
  cmd/reconciler/start/service/integration_test.go
  configs/db/postgres/000008_add_operation_retry_id_and_retries.down.sql
  configs/db/postgres/000008_add_operation_retry_id_and_retries.up.sql
  configs/db/sqlite/reconciler.sql
  configs/reconciler.yaml
  internal/cli/reconciler/start.go
  openapi/internal_api.yaml
  pkg/model/operationentity.go
  pkg/reconciler/heartbeat/heartbeat.go
  pkg/reconciler/heartbeat/heartbeat_test.go
  pkg/reconciler/model.go
  pkg/reconciler/model_gen.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/reconciler_test.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/scheduler/invoker/invoker.go
  pkg/scheduler/invoker/invoker_test.go
  pkg/scheduler/invoker/localinvoker_test.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/service/run.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/worker/config.go
  pkg/scheduler/worker/worker.go
  pkg/scheduler/worker/workerpool.go
  pkg/scheduler/worker/workerpool_test.go
Labels: lgtm, size/L

#660 Fix setting rma authentication overrides
  pkg/reconciler/instances/rma/integration_action.go
  pkg/reconciler/instances/rma/integration_action_test.go
Labels: lgtm, size/L

#661 Add force hydra-maester synchronization in case of hydra rollout
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/ory/action_test.go
  pkg/reconciler/instances/ory/hydra/mocks/syncer.go
  pkg/reconciler/instances/ory/hydra/syncer.go
  pkg/reconciler/instances/ory/hydra/syncer_test.go
Labels: size/M, lgtm

#648 Initial Integration test for Ory reconciler
  Makefile
  pkg/reconciler/instances/ory/test/ory_integration_test.go
Labels: size/M, lgtm

#665 removed loop and replaced with UPDATE command
  configs/db/postgres/000008_add_operation_retry_id_and_retries.up.sql
Labels: lgtm, size/S

#389 Service Catalog migration reconciler
  go.mod
  go.sum
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/scmigration/action.go
  pkg/reconciler/instances/scmigration/btp-operator-migration.go
  pkg/reconciler/instances/scmigration/scmigration.go
Labels: size/XL, lgtm

#672 Revert "Service Catalog migration reconciler (#389)"
  go.mod
  go.sum
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/scmigration/action.go
  pkg/reconciler/instances/scmigration/btp-operator-migration.go
  pkg/reconciler/instances/scmigration/scmigration.go
Labels: size/XL, lgtm

#664 #626: enhance unit-test to verify proper updates of resource limits
  pkg/reconciler/kubernetes/internal/kubeclient_test.go
  pkg/reconciler/kubernetes/internal/test/manifest-after.yaml
  pkg/reconciler/kubernetes/internal/test/manifest-before.yaml
Labels: lgtm, size/S

#669 improve cleanup process
  pkg/reconciler/instances/cleaner/pkg/cleanup/cli.go
  pkg/reconciler/instances/cleaner/pkg/cleanup/pvc.go
  pkg/reconciler/instances/istio/bootstrap.go
  pkg/reconciler/instances/istio/bootstrap_test.go
Labels: lgtm, size/L

#679 add monitoring cr filter to updatestrategyresolver.go
  pkg/reconciler/kubernetes/updatestrategyresolver.go
Labels: bug, lgtm, size/S, area/reconciler

#685 Service Catalog migration reconciler with fewer dependencies
  go.mod
  go.sum
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/scmigration/action.go
  pkg/reconciler/instances/scmigration/btp-operator-migration.go
  pkg/reconciler/instances/scmigration/scmigration.go
  pkg/reconciler/instances/scmigration/utils.go
Labels: size/XL, lgtm

#690 Remove dependency on Service Catalog
  go.mod
  go.sum
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/broker.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/class.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/doc.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/filter.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/plan.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/plan_reference.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/recalculate.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/register.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/types.go
  pkg/reconciler/instances/scmigration/apis/servicecatalog/v1beta1/zz_generated.deepcopy.go
  pkg/reconciler/instances/scmigration/btp-operator-migration.go
  pkg/reconciler/instances/scmigration/filter/helper.go
  pkg/reconciler/instances/scmigration/filter/predicate.go
  pkg/reconciler/instances/scmigration/filter/properties.go
Labels: size/XXL, lgtm

#653 New e2e test-case for external component
  cmd/reconciler/start/service/integration_test.go
Labels: size/M, lgtm

#649 Remove cluster_version & configuration_version from label set
  pkg/metrics/reconciliation_status.go
Labels: lgtm, size/XS

#697 updated gjson lib to v1.13.0 to fix protecode failing pre-merge job
  go.mod
  go.sum
Labels: lgtm, size/S

#691 Refactor helmclient deploy delete logic
  pkg/reconciler/kubernetes/adapter.go
  pkg/reconciler/kubernetes/adapter_test.go
  pkg/reconciler/kubernetes/progress/ready.go
  pkg/reconciler/kubernetes/progress/tracker.go
  pkg/reconciler/kubernetes/progress/watchable.go
  pkg/reconciler/kubernetes/test/unittest-cr.yaml
  pkg/reconciler/kubernetes/test/unittest-crd.yaml
Labels: lgtm, size/L

#699 Create indexes in cluster config statuses
  configs/db/postgres/000009_create_indexes_inventory.down.sql
  configs/db/postgres/000009_create_indexes_inventory.up.sql
Labels: lgtm, size/S

#701 Optimize db
  configs/db/postgres/000009_create_indexes_inventory.down.sql
  configs/db/postgres/000009_create_indexes_inventory.up.sql
Labels: lgtm, size/XS

#680 Use tracker pkg in the Istio proxy reset wait
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/mocks/istio_performer.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/reset/config/config.go
  pkg/reconciler/instances/istio/reset/pod/handler.go
  pkg/reconciler/instances/istio/reset/pod/handler_test.go
  pkg/reconciler/instances/istio/reset/pod/mocks/Handler.go
  pkg/reconciler/instances/istio/reset/pod/reset/action.go
  pkg/reconciler/instances/istio/reset/pod/reset/action_test.go
  pkg/reconciler/instances/istio/reset/pod/reset/mocks/action.go
  pkg/reconciler/instances/istio/reset/proxy/proxy.go
  pkg/reconciler/instances/istio/reset/proxy/proxy_test.go
Labels: size/XL, lgtm, area/reconciler, area/service-mesh

#695 Do not remove the eventing-nats service together with old nats-operator resources
  pkg/reconciler/instances/eventing/preaction/removenatsoperatorstep.go
  pkg/reconciler/instances/eventing/preaction/removenatsoperatorstep_test.go
Labels: lgtm, size/L

#692 Sort reconciliations by date (used to sort KCP output)
  pkg/scheduler/reconciliation/persistent.go
Labels: lgtm, size/XS

#703 No blind mapping
  pkg/cluster/inventory.go
  pkg/repository/errors.go
Labels: lgtm, size/S

#688 Upgrade to latest Golang image
  Dockerfile.cr
  Dockerfile.mr
Labels: lgtm, size/XS

#709 Add config for delete strategy
  cmd/mothership/local/cmd.go
  cmd/mothership/mothership/start/scheduler.go
  configs/reconciler.yaml
  pkg/model/clusterconfigentity.go
  pkg/model/clusterconfigentity_test.go
  pkg/scheduler/config/config.go
  pkg/scheduler/invoker/localinvoker_test.go
  pkg/scheduler/invoker/remoteinvoker_test.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/bookkeeper_test.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/run.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/service/scheduler.go
  pkg/scheduler/service/scheduler_test.go
  pkg/scheduler/service/transition.go
  pkg/scheduler/service/transition_test.go
  pkg/scheduler/worker/workerpool_test.go
Labels: lgtm, size/L

#673 Fix Flaky Parallel Tests
  pkg/db/postgres.go
  pkg/db/sqlite.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/bookkeepingtask.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/scheduler_test.go
  pkg/scheduler/worker/workerpool_test.go
Labels: lgtm, size/L

#717 Fix cleaner component order to run before CRDs
  pkg/model/clusterconfigentity.go
  pkg/model/clusterconfigentity_test.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/worker/workerpool_test.go
Labels: lgtm, size/S

#712 Drop CR finalizers
  pkg/reconciler/instances/cleaner/action.go
  pkg/reconciler/instances/cleaner/pkg/cleanup/cli.go
  pkg/reconciler/instances/cleaner/pkg/cleanup/crd.go
Labels: lgtm, size/L

#711 Remove orphaned NATS pods when upgrading Kyma from 1.X to 2.X
  pkg/reconciler/instances/eventing/preaction/fixtures.go
  pkg/reconciler/instances/eventing/preaction/removenatsoperatorstep.go
  pkg/reconciler/instances/eventing/preaction/removenatsoperatorstep_test.go
Labels: size/XL, lgtm, area/eventing

#718 Don't reconcile jobs
  pkg/reconciler/kubernetes/adapter.go
  pkg/reconciler/kubernetes/kubeclient_test.go
  pkg/reconciler/kubernetes/test/manifest-after.yaml
  pkg/reconciler/kubernetes/test/manifest-before.yaml
  pkg/reconciler/kubernetes/updatestrategyresolver.go
Labels: size/M, lgtm

#719 Add Tomasz as code owner
  CODEOWNERS
Labels: lgtm, size/XS

#696 added new flag to stop after migration and improved migrate logs
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/options.go
  pkg/db/factory.go
  pkg/db/postgres.go
Labels: size/M, lgtm

#681 Custom metrics autoscaling
  cmd/mothership/local/cmd.go
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/options.go
  cmd/mothership/mothership/start/scheduler.go
  cmd/reconciler/start/service/http.go
  cmd/reconciler/start/service/integration_test.go
  configs/db/postgres/000009_worker_pool_occupancy.down.sql
  configs/db/postgres/000009_worker_pool_occupancy.up.sql
  configs/db/sqlite/reconciler.sql
  internal/persistency/registry.go
  openapi/internal_api.yaml
  pkg/metrics/metrics.go
  pkg/metrics/workerpool_occupancy.go
  pkg/model/workerpooloccupentity.go
  pkg/reconciler/heartbeat/heartbeat.go
  pkg/reconciler/heartbeat/heartbeat_test.go
  pkg/reconciler/http.go
  pkg/reconciler/model_gen.go
  pkg/reconciler/occupancy/workerpooloccupancy.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/service/workerpool.go
  pkg/reconciler/service/workerpool_test.go
  pkg/scheduler/invoker/remoteinvoker.go
  pkg/scheduler/invoker/remoteinvoker_test.go
  pkg/scheduler/occupancy/inmemory.go
  pkg/scheduler/occupancy/mock.go
  pkg/scheduler/occupancy/occupancy.go
  pkg/scheduler/occupancy/occupancy_test.go
  pkg/scheduler/occupancy/persistent.go
  pkg/scheduler/service/run.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/worker/workerpool.go
  pkg/scheduler/worker/workerpool_test.go
Labels: size/XXL, lgtm

#721 Fix memory leak in RMA integration action
  pkg/reconciler/instances/rma/fake_client.go
  pkg/reconciler/instances/rma/integration_action.go
  pkg/reconciler/instances/rma/lazy_client.go
Labels: size/M, lgtm

#700 Improved db cleanup
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/options.go
  cmd/mothership/mothership/start/scheduler.go
  pkg/scheduler/service/cleaner.go
  pkg/scheduler/service/cleaner_test.go
Labels: lgtm, size/L

#632 Mothership local with clusterstatus
  cmd/mothership/local/cmd.go
  cmd/mothership/local/local_test.go
  cmd/mothership/local/options.go
Labels: lgtm, size/L

#736 Introduce istio-configuration component reconciler README
  pkg/reconciler/instances/istio/README.md
Labels: size/M, lgtm, area/reconciler, area/documentation, area/service-mesh

#735 Renamed migration scripts
  configs/db/postgres/000010_worker_pool_occupancy.down.sql
  configs/db/postgres/000010_worker_pool_occupancy.up.sql
Labels: lgtm, size/XS

#732 Treat orphans as new ops
  pkg/scheduler/service/result.go
  pkg/scheduler/service/result_test.go
Labels: size/M, lgtm

#737 formatted component reconcilers names to fit metric label validation
  cmd/mothership/mothership/start/scheduler.go
Labels: lgtm, size/XS
