Repository kyma-incubator/reconciler, pull requests merged in 2022-04, with the labels that each got.

#988 Remove ServiceClass and ServicePlan in Service Catalog migration cleanup
  pkg/reconciler/instances/scmigration/sc_removal.go
Labels: size/M, lgtm

#985 Adjust busola-migrator reconciler logging
  pkg/reconciler/instances/busolamigrator/action.go
  pkg/reconciler/instances/busolamigrator/busola.go
Labels: lgtm, size/S

#960 fix: reenable audit log
  cmd/mothership/mothership/start/auditlog.go
  cmd/mothership/mothership/start/auditlog_test.go
Labels: size/M, lgtm

#993 upgrade golang to 1.18.0
  Dockerfile.cr
  Dockerfile.mr
Labels: lgtm, size/XS

#992 Fix sec findings 2022-04-04 for reconciler
  go.mod
  go.sum
Labels: lgtm, size/L

#998 Revert "Fix sec findings 2022-04-04 for reconciler"
  go.mod
  go.sum
Labels: lgtm, size/L

#989 istio: handle unhealthy pods during upgrade
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/reset/data/gatherer.go
  pkg/reconciler/instances/istio/reset/data/gatherer_test.go
  pkg/reconciler/instances/istio/reset/pod/handler.go
  pkg/reconciler/instances/istio/reset/pod/handler_test.go
  pkg/reconciler/instances/istio/reset/pod/matcher.go
  pkg/reconciler/instances/istio/reset/pod/reset/action.go
  pkg/reconciler/instances/istio/reset/pod/reset/action_test.go
  pkg/reconciler/instances/istio/reset/proxy/proxy.go
Labels: lgtm, size/L, area/service-mesh, area/security

#996 Fix security issues 2022-04-05
  go.mod
  go.sum
Labels: size/XL, lgtm

#994 Adjust cluster-essentials reconciler logging
  pkg/reconciler/instances/clusteressentials/action.go
  pkg/reconciler/instances/clusteressentials/clusteressentials.go
Labels: lgtm, size/XS

#1004 Skip migrating instances that don't have SM counterpart
  pkg/reconciler/instances/scmigration/btp_operator_migration.go
Labels: lgtm, size/XS

#995 Fix info message format in sc-reconciler
  pkg/reconciler/instances/scmigration/btp_operator_migration.go
Labels: lgtm, size/XS

#963 feat: Cleanup cluster entities
  configs/db/postgres/000013_add_index_del_created_inventory.down.sql
  configs/db/postgres/000013_add_index_del_created_inventory.up.sql
  configs/db/postgres/000014_cleanup_status_entities_view.down.sql
  configs/db/postgres/000014_cleanup_status_entities_view.up.sql
  configs/db/postgres/000015_cleanup_cluster_entities_view.down.sql
  configs/db/postgres/000015_cleanup_cluster_entities_view.up.sql
  pkg/cluster/inventory.go
  pkg/cluster/inventory_test.go
  pkg/cluster/mock.go
  pkg/db/mocks.go
  pkg/model/clustercleanupentity.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/persistent_test.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/service/cleaner.go
  pkg/scheduler/service/cleaner_test.go
  pkg/scheduler/service/transition.go
  pkg/scheduler/service/transition_test.go
Labels: size/XL, lgtm

#1006 !feat: remove audit log functionality until better concept is in place
  cmd/mothership/mothership/start/auditlog.go
  cmd/mothership/mothership/start/auditlog_test.go
Labels: lgtm, size/L

#956 Rework E2E Integration Test Suite for Mothership and Component Reconciler
  Makefile
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/integration_test.go
  cmd/mothership/mothership/start/mothership_integration_helpers_test.go
  cmd/mothership/mothership/start/mothership_integration_test.go
  cmd/mothership/mothership/start/options.go
  cmd/mothership/mothership/start/scheduler.go
  cmd/mothership/mothership/start/test/component-reconcilers.json
  cmd/mothership/mothership/start/test/requests/callback.json
  cmd/mothership/mothership/start/test/requests/create_cluster.json
  cmd/mothership/mothership/start/test/requests/create_cluster2.json
  cmd/mothership/mothership/start/test/requests/create_cluster_invalid_kubeconfig.json
  cmd/mothership/mothership/start/test/requests/disable_cluster.json
  cmd/mothership/mothership/start/test/requests/empty.json
  cmd/mothership/mothership/start/test/requests/enable_cluster.json
  cmd/mothership/mothership/start/test/requests/enable_force_cluster.json
  cmd/mothership/mothership/start/test/requests/invalid.json
  cmd/mothership/mothership/start/test/requests/new_occupancy.json
  cmd/mothership/mothership/start/test/requests/update_occupancy.json
  cmd/reconciler/start/service/component_integration_suite_test.go
  cmd/reconciler/start/service/component_integration_test.go
  cmd/reconciler/start/service/http.go
  cmd/reconciler/start/service/integration_test.go
  docs/integration-testing.md
  internal/persistency/registry.go
  pkg/db/container_lease.go
  pkg/db/container_test_suite.go
  pkg/db/db_suite_test.go
  pkg/db/encryption_key_file_config.go
  pkg/db/encryption_key_file_config_test.go
  pkg/db/factory.go
  pkg/db/migration_config.go
  pkg/db/migration_config_test.go
  pkg/db/postgres.go
  pkg/db/postgres_container.go
  pkg/db/postgres_container_runtime.go
  pkg/db/transaction_aware_database_container_test_suite.go
  pkg/db/transaction_aware_database_container_test_suite_test.go
  pkg/files/hash.go
  pkg/files/hash_test.go
  pkg/files/root.go
  pkg/logger/zap.go
  pkg/metrics/metrics.go
  pkg/metrics/reconciliation_status.go
  pkg/reconciler/chart/factory.go
  pkg/reconciler/kubernetes/adapter.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner_test.go
  pkg/reconciler/service/test.go
  pkg/reconciler/service/workerpool.go
  pkg/scheduler/invoker/error.go
  pkg/scheduler/invoker/remoteinvoker.go
  pkg/scheduler/invoker/remoteinvoker_test.go
  pkg/test/integration.go
  scripts/.golangci.yml
Labels: size/XXL, lgtm, tw-review-needed

#970 tests: Test suite for scheduler/reconciliation, scheduler/service & cluster pkgs
  pkg/cluster/cluster_suite_test.go
  pkg/cluster/inventory_test.go
  pkg/scheduler/reconciliation/filter_test.go
  pkg/scheduler/reconciliation/persistent_test.go
  pkg/scheduler/reconciliation/reconciliation_suite_test.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/bookkeeper_test.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/cleaner_test.go
  pkg/scheduler/service/inventorywatch_test.go
  pkg/scheduler/service/result_test.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/service/scheduler_test.go
  pkg/scheduler/service/service_suite_test.go
  pkg/scheduler/service/transition_test.go
Labels: size/XXL, lgtm

#1014 Add istioctl 1.13.2 to the Dockerfile
  Dockerfile.cr
Labels: lgtm, size/XS, area/reconciler, area/service-mesh

#1003 Always patch MutatingWebHook
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/instances/istio/istio_test.go
Labels: lgtm, size/L, area/reconciler, area/service-mesh, area/security

#1025 Fix Protecode issues in reconciler
  go.mod
  go.sum
Labels: size/M, lgtm

#1024 Disable atomic deployment of RMA integration
  pkg/reconciler/instances/rma/integration_action.go
Labels: lgtm, size/XS

#1019 Add optional skip for safety check in scmigration
  pkg/reconciler/instances/scmigration/action.go
  pkg/reconciler/instances/scmigration/btp_operator_migration.go
  pkg/reconciler/instances/scmigration/scmigration.go
Labels: lgtm, size/S

#1026 Changing busolamigrator INFO log level to DEBUG
  pkg/reconciler/instances/busolamigrator/busola.go
Labels: lgtm, size/XS

#1030 move (disable) new cleanup logic in one location
  pkg/scheduler/service/cleaner.go
Labels: lgtm, size/S

#1038 feat: add exponential retry when validating a cluster on create/update
  cmd/mothership/mothership/start/http.go
  pkg/kubernetes/clientbuilder.go
  pkg/kubernetes/clientbuilder_test.go
  pkg/kubernetes/kubeconfig-unreachable.yaml
Labels: size/M, lgtm

#983 Feat: Enable debug logs for specific operations
  cmd/mothership/mothership/start/http.go
  configs/db/postgres/000016_add_operation_debug.down.sql
  configs/db/postgres/000016_add_operation_debug.up.sql
  pkg/features/features.go
  pkg/model/operationentity.go
  pkg/reconciler/model.go
  pkg/reconciler/service/workerpool.go
  pkg/scheduler/invoker/invoker.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/worker/worker.go
Labels: lgtm, size/L

#1017 Reintroduce audit log
  cmd/mothership/mothership/start/auditlog.go
  cmd/mothership/mothership/start/auditlog_test.go
  cmd/mothership/mothership/start/http.go
Labels: lgtm, size/L

#1043 Enrich logging for istioctl apply
  pkg/reconciler/instances/istio/istioctl/commander.go
  pkg/reconciler/instances/istio/reset/proxy/proxy.go
Labels: lgtm, size/S, area/service-mesh

#1039 Fix of getting pods with istio sidecar upgrade required
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/mocks/istio_performer.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/reset/data/gatherer.go
  pkg/reconciler/instances/istio/reset/data/gatherer_test.go
  pkg/reconciler/instances/istio/reset/proxy/proxy.go
  pkg/reconciler/instances/istio/test_files/0.0.0/resources/istio-configuration/values.yaml
  pkg/reconciler/instances/istio/test_files/1.11.2/resources/istio-configuration/values.yaml
  pkg/reconciler/instances/istio/test_files/istio-incorrect-values-only-appversion/values.yaml
  pkg/reconciler/instances/istio/test_files/istio-test/values.yaml
  pkg/reconciler/instances/istio/test_files/istio-values-appversion/values.yaml
Labels: lgtm, size/L, area/security

#1044 fix: streamline DB model with enhanced constraints & indices
  configs/db/postgres/000009_create_indexes_inventory.up.sql
  configs/db/postgres/000013_add_index_del_created_inventory.up.sql
  configs/db/postgres/000017_streamline_fks_indices.down.sql
  configs/db/postgres/000017_streamline_fks_indices.up.sql
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/persistent_test.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/service/transition.go
Labels: lgtm, size/L

#1041 chore: dependency upgrade & security fixes
  Makefile
  cmd/mothership/mothership/start/http.go
  go.mod
  go.sum
  pkg/interpreter/yaegi.go
  pkg/keb/factory.go
  pkg/kubernetes/clientbuilder.go
Labels: size/XL, lgtm

#1049 Fix Audit Log Middleware Registration
  cmd/mothership/mothership/start/auditlog.go
  cmd/mothership/mothership/start/auditlog_test.go
  cmd/mothership/mothership/start/http.go
  configs/reconciler.yaml
Labels: size/M, lgtm

#1051 Fix resource exhaustion for istioctl env var
  pkg/reconciler/instances/istio/bootstrap.go
  pkg/reconciler/instances/istio/bootstrap_test.go
Labels: lgtm, size/S, area/security

#1021 Introduce limited Connection Pool Settings
  configs/reconciler.yaml
Labels: lgtm, size/XS

#1054 security fixes
  go.mod
  go.sum
Labels: lgtm, size/L

#1040 Decreasing log level for connectivity proxy
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/loader.go
Labels: lgtm, size/S

#1055 Various Small Dependency Upgrades
  go.mod
  go.sum
Labels: lgtm, size/L

#1057 refactor: Cleaner flags
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/options.go
  cmd/mothership/mothership/start/scheduler.go
  pkg/scheduler/service/cleaner.go
  pkg/scheduler/service/cleaner_test.go
Labels: size/M, lgtm

#986 The logic for removal of remaining certificates after deletion of the Connectivity-Proxy
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/command.go
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/instances/connectivityproxy/mocks/commands.go
Labels: lgtm, size/S, area/connectivity-proxy

#1060 Adjust occupancy logging (reduce noise)
  pkg/reconciler/service/occupancytracker.go
Labels: lgtm, size/S

#1029 Use GORM module to build SQL strings
  go.mod
  go.sum
  pkg/cluster/inventory.go
  pkg/db/columnhandler.go
  pkg/db/columnhandler_test.go
  pkg/db/errors.go
  pkg/db/interface.go
  pkg/db/mocks.go
  pkg/db/postgres.go
  pkg/db/query.go
  pkg/db/query_gorm.go
  pkg/db/query_gorm_test.go
  pkg/db/sqlite.go
  pkg/db/transaction.go
  pkg/model/clusterstatusentity.go
Labels: size/XL, lgtm

#1064 Setup Dependabot
  .github/dependabot.yml
Labels: lgtm, size/XS

#1059 Fix of getting istio prefix on Kyma version < 2.1
  pkg/reconciler/instances/istio/actions/performer.go
Labels: size/M, lgtm, area/security
