Repository kyma-incubator/reconciler, pull requests merged in 2022-07, with the labels that each got.

#1119 mark cluster deleted if operation error contains no such host
  pkg/scheduler/service/bookkeeper_test.go
  pkg/scheduler/service/bookkeepingtask.go
Labels: size/M, lgtm

#1121 Remove ory finalizers during reconciler delete action
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/ory/action_test.go
  pkg/reconciler/instances/ory/k8s/mocks/ory_finalizers_handler.go
  pkg/reconciler/instances/ory/k8s/ory_crds.go
  pkg/reconciler/instances/ory/ory.go
Labels: lgtm, size/L

#1083 Reconciler docu
  README.md
  docs/assets/reconciler-deployment.png
  docs/assets/reconciler-highlevel-overview.png
  docs/assets/reconciler-runtime.png
  docs/assets/reconciler-swlayers.png
  docs/assets/reconciler_buildingblocks.png
  docs/configuration-management.md
  docs/howto.md
Labels: size/XL, lgtm

#1122 Delete ory finalizers in post-delete action
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/ory/action_test.go
  pkg/reconciler/instances/ory/ory.go
Labels: size/M, lgtm

#1124 Fix can't get all crds from cluster
  pkg/reconciler/instances/cleaner/pkg/cleanup/cli.go
  pkg/reconciler/instances/cleaner/pkg/cleanup/crd.go
  pkg/reconciler/instances/cleaner/pkg/cleanup/crd_test.go
  pkg/reconciler/instances/cleaner/pkg/cleanup/test/unittest-crd.yaml
Labels: size/M, lgtm

#1133 Update code owners
  CODEOWNERS
Labels: lgtm, size/XS

#1139 Only patch new istio webhook
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/istio_test.go
Labels: lgtm, area/service-mesh

#1136 Istio sidecar injection disabling
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/mocks/istio_performer.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/test_files/istio-sidecar-disabled/Chart.yaml
  pkg/reconciler/instances/istio/test_files/istio-sidecar-disabled/values.yaml
  pkg/reconciler/instances/istio/test_files/istio-sidecar-empty/Chart.yaml
  pkg/reconciler/instances/istio/test_files/istio-sidecar-enabled/Chart.yaml
  pkg/reconciler/instances/istio/test_files/istio-sidecar-enabled/values.yaml
Labels: size/XL, lgtm, area/service-mesh
