Repository kyma-incubator/reconciler, pull requests merged in 2022-12, with the labels that each got.

#1247 Restart IG on Istio CR update
  go.mod
  go.sum
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_ig_test.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/actions/test-utils/ingress-gateway-client.go
  pkg/reconciler/instances/istio/clientset/provider.go
  pkg/reconciler/instances/istio/ingress-gateway/config.go
  pkg/reconciler/instances/istio/ingress-gateway/config_test.go
  pkg/reconciler/instances/istio/ingress-gateway/deployment.go
  pkg/reconciler/instances/istio/ingress-gateway/deployment_test.go
  pkg/reconciler/instances/istio/ingress-gateway/utils_test.go
  pkg/reconciler/instances/istio/istio_test.go
  pkg/reconciler/instances/istio/merge/merge.go
  pkg/reconciler/instances/istio/merge/merge_test.go
Labels: size/XL, lgtm, area/service-mesh, area/security

#1254 remove eventing reconciler
  CODEOWNERS
  cmd/mothership/mothership/start/mothership_integration_helpers_test.go
  cmd/reconciler/start/service/component_integration_test.go
  pkg/reconciler/instances/eventing/action/action.go
  pkg/reconciler/instances/eventing/action/step.go
  pkg/reconciler/instances/eventing/eventing.go
  pkg/reconciler/instances/eventing/eventing_test.go
  pkg/reconciler/instances/eventing/log/log.go
  pkg/reconciler/instances/eventing/postaction/postaction.go
  pkg/reconciler/instances/eventing/preaction/preaction.go
  pkg/reconciler/instances/loader.go
Labels: lgtm, size/L

#1263 Fix panic in ingress-gateway restart
  pkg/reconciler/instances/istio/ingress-gateway/deployment.go
  pkg/reconciler/instances/istio/ingress-gateway/deployment_test.go
Labels: lgtm, size/S, area/security

#1265 Support of Istio 1.16 in reconciler
  Dockerfile.cr
Labels: lgtm, size/XS

#1266 Fix RMA reconciler nil pointer error
  pkg/reconciler/instances/rma/integration_action.go
Labels: lgtm, size/XS

#1264 Implement mechanism in Connectivity Proxy Reconciler that prevents overwriting user's configuration
  pkg/reconciler/chart/component.go
  pkg/reconciler/chart/factory.go
  pkg/reconciler/chart/mocks/external_component_authenticator.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
  pkg/reconciler/instances/connectivityproxy/command.go
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/instances/connectivityproxy/mocks/commands.go
  pkg/reconciler/instances/connectivityproxy/rendering/chartproviderwithauthentication.go
  pkg/reconciler/instances/connectivityproxy/rendering/chartproviderwithauthentication_test.go
  pkg/reconciler/instances/connectivityproxy/rendering/chartproviderwithfiltering.go
  pkg/reconciler/instances/connectivityproxy/rendering/chartproviderwithfiltering_test.go
  pkg/reconciler/instances/connectivityproxy/rendering/manifestfilters.go
  pkg/reconciler/instances/connectivityproxy/rendering/manifestfilters_test.go
Labels: size/XL, lgtm
