Repository kyma-incubator/reconciler, pull requests merged in 2022-09, with the labels that each got.

#1177 Fix "namespaceByDefault" typo
  pkg/reconciler/instances/istio/actions/performer.go
Labels: lgtm, size/XS, area/security

#1176 Support sidecar injection labels in proxy reset
  pkg/reconciler/instances/istio/reset/data/gatherer.go
  pkg/reconciler/instances/istio/reset/data/gatherer_test.go
Labels: lgtm, size/L, area/service-mesh, area/security

#1172 Support RmiVmalertGroupsNum for VMAlert scaled out
  pkg/reconciler/instances/rma/integration_action.go
  pkg/reconciler/instances/rma/integration_action_test.go
  pkg/reconciler/instances/rma/testdata/values.yaml
  scripts/.golangci.yml
Labels: size/M, lgtm

#1178 Remove busola-migrator reconciler
  CODEOWNERS
  pkg/reconciler/instances/busolamigrator/action.go
  pkg/reconciler/instances/busolamigrator/action_test.go
  pkg/reconciler/instances/busolamigrator/busola.go
  pkg/reconciler/instances/busolamigrator/test_files/virtual-service.yaml
  pkg/reconciler/instances/busolamigrator/vs_client.go
  pkg/reconciler/instances/loader.go
Labels: lgtm, size/L, kind/cleanup

#1181 Enable Istioctl debug logs
  pkg/reconciler/instances/istio/istioctl/commander.go
Labels: lgtm, size/S, area/service-mesh, area/security

#1183 Bump istio to 1.14.4
  Dockerfile.cr
Labels: lgtm, size/XS

#1184 Add istioctl 1.15.0 to Dockerfile
  Dockerfile.cr
Labels: lgtm, size/XS

#1182 Remove istio labeling
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/consts/consts.go
  pkg/reconciler/instances/istio/consts/errors.go
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/instances/istio/reset/data/gatherer.go
  pkg/reconciler/instances/istio/reset/data/gatherer_test.go
  pkg/reconciler/instances/istio/reset/data/mocks/Gatherer.go
  pkg/reconciler/instances/istio/reset/label/action.go
  pkg/reconciler/instances/istio/reset/label/label_with_warning_internal_test.go
  pkg/reconciler/instances/istio/reset/label/label_with_warning_test.go
  pkg/reconciler/instances/istio/reset/label/mocks/action.go
Labels: size/XXL, lgtm, area/security

#1185 Fix " '' is not in tri-dotted format" bug
  pkg/reconciler/instances/istio/action.go
Labels: lgtm, size/XS, area/security
