Repository kyma-incubator/reconciler, pull requests merged in 2022-05, with the labels that each got.

#1069 Update golang to 1.18.1 in Dockerfiles
  Dockerfile.cr
  Dockerfile.mr
Labels: lgtm, size/XS

#1070 refactor: Transition handling for cleanup + increased logs
  pkg/scheduler/service/cleaner.go
  pkg/scheduler/service/service_suite_test.go
  pkg/scheduler/service/transition.go
  pkg/scheduler/service/transition_test.go
Labels: lgtm, size/L

#1073 refresh eventing code owners
  CODEOWNERS
Labels: lgtm, size/XS

#1074 Revert "Use GORM module to build SQL strings (#1029)"
  go.mod
  go.sum
  pkg/cluster/inventory.go
  pkg/db/columnhandler.go
  pkg/db/columnhandler_test.go
  pkg/db/errors.go
  pkg/db/interface.go
  pkg/db/mocks.go
  pkg/db/postgres.go
  pkg/db/query.go
  pkg/db/query_gorm.go
  pkg/db/query_gorm_test.go
  pkg/db/sqlite.go
  pkg/db/transaction.go
  pkg/model/clusterstatusentity.go
Labels: size/XL, lgtm

#1061 Fix of mismatch of data and control plane blocking istio proxy reset
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/istio_test.go
Labels: size/M, lgtm, area/security

#1071 Removed pre-actions from eventing component reconciler for Kyma 1.24.X to 2.x.x
  pkg/reconciler/instances/eventing/preaction/common.go
  pkg/reconciler/instances/eventing/preaction/fixtures.go
  pkg/reconciler/instances/eventing/preaction/migrateeventtypeprefixconfigstep.go
  pkg/reconciler/instances/eventing/preaction/migrateeventtypeprefixconfigstep_test.go
  pkg/reconciler/instances/eventing/preaction/preaction.go
  pkg/reconciler/instances/eventing/preaction/removenatsoperatorstep.go
  pkg/reconciler/instances/eventing/preaction/removenatsoperatorstep_test.go
Labels: size/XXL, lgtm

#1072 Add preaction to handle enabling/disabling the jestream with file storage
  go.mod
  pkg/reconciler/instances/eventing/preaction/common.go
  pkg/reconciler/instances/eventing/preaction/handletogglejsfilestorage.go
  pkg/reconciler/instances/eventing/preaction/handletogglejsfilestorage_test.go
  pkg/reconciler/instances/eventing/preaction/preaction.go
Labels: size/XL, lgtm

#1080 Fix: Istio proxy path bug in performer
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
Labels: size/M, lgtm, area/service-mesh, area/security

#1078 Retry on istioctl apply
  go.mod
  go.sum
  pkg/reconciler/instances/istio/istioctl/commander.go
  pkg/reconciler/instances/istio/istioctl/commander_test.go
  pkg/reconciler/instances/istio/istioctl/executor/cmd_executor.go
  pkg/reconciler/instances/istio/istioctl/executor/cmd_executor_test.go
  pkg/reconciler/instances/istio/istioctl/executor/mocks/cmd_executor.go
  pkg/reconciler/instances/istio/istioctl/resolver.go
Labels: lgtm, size/L, area/service-mesh, area/security

#1087 Enable debug logs for KCP CLI
  cmd/mothership/mothership/start/http.go
  openapi/external_api.yaml
Labels: size/M, lgtm

#1082 Add tests for getting Istio Proxy image path and refactor code
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/test_files/path-tests/istio-configuration/Chart.yaml
  pkg/reconciler/instances/istio/test_files/path-tests/istio-configuration/values.yaml
  pkg/reconciler/instances/istio/test_files/path-tests/istio/Chart.yaml
  pkg/reconciler/instances/istio/test_files/path-tests/istio/values.yaml
Labels: lgtm, size/L, area/service-mesh, area/security

#1091 redact audit log details by key
  cmd/mothership/mothership/start/auditlog.go
  cmd/mothership/mothership/start/auditlog_test.go
Labels: size/M, lgtm

#1089 Feat: Track Reconciliation Status in Configmaps
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/status.go
Labels: lgtm, size/L

#1092 Increase payload limit to 100KB
  cmd/mothership/mothership/start/http.go
Labels: lgtm, size/XS

#1099 createOrUpdateStatusCm should not block further process
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/status.go
Labels: size/M, lgtm
