Repository kyma-incubator/reconciler, pull requests merged in 2022-11, with the labels that each got.

#1226 Use Istio 1.15.3 in reconciler
  Dockerfile.cr
Labels: lgtm, size/XS

#1227 Remove obsolete patching of mutating webhook
  pkg/reconciler/instances/istio/README.md
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/mocks/istio_performer.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/assets/istio-reconciler.svg
  pkg/reconciler/instances/istio/assets/istio-reconciliation-action.svg
  pkg/reconciler/instances/istio/istio_test.go
Labels: size/XL, lgtm, area/security

#1230 Update CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/XS

#1232 chore: upgrade and bump dependencies
  Dockerfile.cr
  Dockerfile.mr
  go.mod
  go.sum
  pkg/db/container_test_suite.go
Labels: size/XL, lgtm

#1229 Apply user configuration to Istio reconciler
  go.mod
  go.sum
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/mocks/istio_performer.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/clientset/mocks/provider.go
  pkg/reconciler/instances/istio/clientset/provider.go
  pkg/reconciler/instances/istio/istio_test.go
  pkg/reconciler/instances/istio/merge/merge.go
  pkg/reconciler/instances/istio/merge/merge_test.go
Labels: size/XL, lgtm, area/service-mesh, area/security

#1241 chore: upgrade and bump dependencies
  Dockerfile.cr
  Dockerfile.mr
  go.mod
  go.sum
Labels: lgtm, size/L

#1245 Update CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/XS

#1244 Support Istio CNI plugin configuration
  go.mod
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/clientset/mocks/provider.go
  pkg/reconciler/instances/istio/clientset/provider.go
  pkg/reconciler/instances/istio/cni/cni.go
  pkg/reconciler/instances/istio/cni/cni_test.go
  pkg/reconciler/instances/istio/merge/merge.go
  pkg/reconciler/instances/istio/merge/merge_test.go
  pkg/reconciler/instances/istio/reset/config/config.go
  pkg/reconciler/instances/istio/reset/data/gatherer.go
  pkg/reconciler/instances/istio/reset/data/gatherer_test.go
  pkg/reconciler/instances/istio/reset/data/mocks/Gatherer.go
  pkg/reconciler/instances/istio/reset/proxy/proxy.go
  pkg/reconciler/instances/istio/reset/proxy/proxy_test.go
Labels: size/XL, lgtm, area/service-mesh, area/security

#1248 Rename Istio CNI ConfigMap key
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/cni/cni.go
  pkg/reconciler/instances/istio/cni/cni_test.go
Labels: lgtm, size/S, area/security
