Repository kyma-incubator/reconciler, pull requests merged in 2022-03, with the labels that each got.

#847 Add diagrams to the Istio Reconciler README.md
  pkg/reconciler/instances/istio/README.md
  pkg/reconciler/instances/istio/assets/istio-reconciler.svg
  pkg/reconciler/instances/istio/assets/istio-reconciliation-action.svg
Labels: size/M, lgtm

#887 Add codeowners for SC migration
  CODEOWNERS
Labels: lgtm, size/XS

#741 bump istioctl to 1.12.3
  Dockerfile.cr
Labels: lgtm, size/XS, area/service-mesh

#875 Service catalog migration keep old instances and bindings
  pkg/reconciler/instances/scmigration/btp_operator_migration.go
  pkg/reconciler/instances/scmigration/sc_removal.go
Labels: size/M, lgtm

#891 add missing previous version of istioctl
  Dockerfile.cr
Labels: lgtm, size/XS

#893 fix type-o in istioctl path
  Dockerfile.cr
Labels: lgtm, size/XS

#856 Implement dry-run mode
  cmd/mothership/mothership/start/http.go
  cmd/reconciler/main.go
  cmd/reconciler/start/cmd.go
  cmd/reconciler/start/service/cmd.go
  cmd/reconciler/start/service/reconciler.go
  internal/cli/reconciler/options.go
  openapi/internal_api.yaml
  pkg/reconciler/model_gen.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/registry.go
  pkg/reconciler/service/runner.go
Labels: size/M, lgtm

#885 Update CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/XS

#892 Fix security issues in reconciler deps
  go.mod
  go.sum
Labels: size/M, lgtm

#882 Enable windows delivery through build-windows
  Makefile
Labels: lgtm, size/XS

#826 Hardcode ServiceManager auth URL suffix for sc-migration
  go.mod
  go.sum
  pkg/reconciler/instances/scmigration/btp_operator_migration.go
  pkg/reconciler/instances/scmigration/utils.go
Labels: lgtm, size/S

#906 Fix security issues reconciler
  go.mod
  go.sum
Labels: lgtm, size/S

#904 expose component reconciler metrics endpoint
  cmd/reconciler/start/service/http.go
Labels: lgtm, size/XS

#877 Propagate State to ReconciliationSequenceConfig to disable cleaner reconciler on normal reconciliations
  pkg/model/clusterconfigentity.go
  pkg/model/clusterconfigentity_test.go
  pkg/model/clusterstatus.go
  pkg/scheduler/invoker/localinvoker_test.go
  pkg/scheduler/invoker/remoteinvoker_test.go
  pkg/scheduler/invoker/test.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/service/scheduler.go
  pkg/scheduler/service/scheduler_test.go
Labels: lgtm, size/L

#890 Add name label to namespaces
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/service/install.go
  pkg/reconciler/service/nsinterceptor.go
  pkg/reconciler/service/nsinterceptor_test.go
Labels: lgtm, size/L

#913 Add hydra-maester startup shift
  pkg/reconciler/instances/ory/hydra/syncer.go
  pkg/reconciler/instances/ory/hydra/syncer_test.go
  pkg/reconciler/instances/ory/test/ory_integration_test.go
Labels: size/M, lgtm, area/api-gateway

#844 A separate occupancy tracker for MR
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/http.go
  cmd/mothership/mothership/start/options.go
  cmd/mothership/mothership/start/scheduler.go
  internal/persistency/registry.go
  pkg/metrics/metrics.go
  pkg/metrics/workerpool_occupancy.go
  pkg/reconciler/service/occupancytracker.go
  pkg/scheduler/occupancy/inmemory.go
  pkg/scheduler/occupancy/mock.go
  pkg/scheduler/occupancy/occupancy.go
  pkg/scheduler/occupancy/occupancy_test.go
  pkg/scheduler/occupancy/persistent.go
  pkg/scheduler/service/occupancytracker.go
  pkg/scheduler/service/run.go
  pkg/scheduler/worker/workerpool.go
  pkg/scheduler/worker/workerpool_test.go
Labels: size/XL, lgtm

#922 Add resource dump when context closed
  pkg/reconciler/kubernetes/progress/tracker.go
Labels: lgtm, size/S

#925 Fix bug not adding cleaner component on deletions
  pkg/scheduler/service/scheduler.go
  pkg/scheduler/service/transition.go
  pkg/scheduler/service/transition_test.go
Labels: size/M, lgtm

#928 Fix sec findings
  Dockerfile.cr
  Dockerfile.mr
  go.mod
  go.sum
Labels: lgtm, size/S

#919 Replace istioctl upgrade usage from Istio reconciler with apply
  pkg/reconciler/instances/istio/istioctl/commander.go
  pkg/reconciler/instances/istio/istioctl/commander_test.go
Labels: size/M, lgtm, area/reconciler, area/service-mesh

#912 Improve cleaner component
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/options.go
  cmd/mothership/mothership/start/scheduler.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/service/cleaner.go
  pkg/scheduler/service/cleaner_test.go
Labels: size/XL, lgtm

#829 Improve Ory integration tests on evaluation profile
  pkg/reconciler/instances/ory/test/ory_integration_test.go
Labels: size/M, lgtm

#905 Create DB Views for calls to speed up SQL lookup on Max aggregrations for Inventory
  configs/db/postgres/000013_active_cluster_views.down.sql
  configs/db/postgres/000013_active_cluster_views.up.sql
  pkg/cluster/clusterfilter.go
  pkg/cluster/inventory.go
  pkg/cluster/state.go
  pkg/cluster/statusfilter.go
  pkg/cluster/statussqlfilter.go
  pkg/db/validator.go
  pkg/model/activeinventoryclusterstatusdetailsentity.go
  pkg/model/converter.go
Labels: size/XL, lgtm

#932 increase startup shift for hydra maester pod
  pkg/reconciler/instances/ory/hydra/syncer.go
Labels: lgtm, size/XS, area/api-gateway

#934 Remove reconciliations by runtimeID
  cmd/mothership/mothership/start/integration_test.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/persistent_test.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/reconciliation/reconciliation_test.go
  pkg/scheduler/service/bookkeeper_test.go
  pkg/scheduler/service/bookkeepingtask_test.go
  pkg/scheduler/service/cleaner.go
  pkg/scheduler/service/run_test.go
  pkg/scheduler/service/transition_test.go
  pkg/scheduler/worker/workerpool_test.go
Labels: lgtm, size/L

#938 Adapt cleaner module to bulk reconciliation removal
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/service/cleaner.go
Labels: lgtm, size/L

#930 add ComponentProcessingDurationMetric to component reconciler
  cmd/reconciler/start/service/cmd.go
  cmd/reconciler/start/service/reconciler.go
  internal/cli/reconciler/start.go
  pkg/metrics/component_processing_duration.go
  pkg/metrics/reconciler_metrics_set.go
  pkg/reconciler/service/reconciler.go
  pkg/reconciler/service/runner.go
  pkg/reconciler/service/runner_test.go
Labels: lgtm, size/L

#945 Revert "Create DB Views for calls to speed up SQL lookup on Max aggregrations for Inventory"
  configs/db/postgres/000013_active_cluster_views.down.sql
  configs/db/postgres/000013_active_cluster_views.up.sql
  pkg/cluster/clusterfilter.go
  pkg/cluster/inventory.go
  pkg/cluster/state.go
  pkg/cluster/statusfilter.go
  pkg/cluster/statussqlfilter.go
  pkg/db/validator.go
  pkg/model/activeinventoryclusterstatusdetailsentity.go
  pkg/model/converter.go
Labels: size/XL, lgtm

#942 Fix placeholder in cleaner logs
  pkg/scheduler/service/cleaner.go
Labels: lgtm, size/XS

#900 Use environment variable to obtain the auth token
  pkg/reconciler/chart/factory.go
  pkg/reconciler/git/clone.go
  pkg/reconciler/git/clone_test.go
  pkg/reconciler/model.go
  pkg/scheduler/invoker/invoker.go
  pkg/scheduler/invoker/invoker_test.go
Labels: lgtm, size/L, area/reconciler

#894 Refactor Istio-configuration Helm chart
  configs/reconciler-unittest.yaml
  configs/reconciler.yaml
  pkg/reconciler/instances/istio/README.md
Labels: lgtm, size/XS, area/service-mesh

#916 idempotently disable sidecar injection into kube-system
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
Labels: size/M, lgtm

#940 Add purge functionality and API endpoint
  cmd/mothership/mothership/start/http.go
  openapi/external_api.yaml
Labels: size/M, lgtm, area/control-plane

#931 occupancy tracking local autoscaling testing findings
  pkg/scheduler/occupancy/inmemory.go
  pkg/scheduler/occupancy/occupancy.go
  pkg/scheduler/occupancy/occupancy_test.go
  pkg/scheduler/service/occupancytracker.go
  pkg/scheduler/worker/workerpool.go
Labels: lgtm, size/L

#929 Remove reconciliations by filter
  pkg/db/query.go
  pkg/db/transaction.go
  pkg/scheduler/reconciliation/filter.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/persistent_test.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/service/cleaner.go
  pkg/scheduler/service/cleaner_test.go
Labels: lgtm, size/L

#886 Testify-Based Integration Test Suite for DB Tests
  docs/integration-testing.md
  go.mod
  go.sum
  pkg/db/columnhandler_test.go
  pkg/db/container_bootstrap.go
  pkg/db/container_lease.go
  pkg/db/container_log_listener.go
  pkg/db/container_runtime.go
  pkg/db/container_test_suite.go
  pkg/db/db_suite_test.go
  pkg/db/factory.go
  pkg/db/interface.go
  pkg/db/postgres.go
  pkg/db/postgres_container.go
  pkg/db/postgres_container_runtime.go
  pkg/db/sqlite.go
  pkg/db/transaction_aware_database_container_test_suite.go
  pkg/db/transaction_aware_database_container_test_suite_test.go
Labels: size/XXL, lgtm

#951 RMA: remove secret cache as it can lead to stale, inconsistent config
  pkg/reconciler/instances/rma/integration_action.go
Labels: size/M, lgtm

#952 feat: Remove obsolete reconciliations inline for all clusters
  pkg/db/query.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/mock.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/reconciliation/persistent_test.go
  pkg/scheduler/reconciliation/reconciliation.go
  pkg/scheduler/service/cleaner.go
Labels: lgtm, size/L

#957 Exclude pods in Pending phase from Istio Proxy Reset
  pkg/reconciler/instances/istio/reset/data/gatherer.go
  pkg/reconciler/instances/istio/reset/data/gatherer_test.go
Labels: lgtm, size/S, area/service-mesh, area/security

#964 Update Ory Hydra hpa test
  pkg/reconciler/instances/ory/test/ory_integration_test.go
Labels: lgtm, size/XS

#955 Safe cleanup of service catalog instances
  pkg/reconciler/instances/scmigration/btp_operator_migration.go
  pkg/reconciler/instances/scmigration/sc_removal.go
Labels: lgtm, size/L

#965 refactor: Rename and reuse cleanup days flag for all entities
  cmd/mothership/mothership/start/cmd.go
  cmd/mothership/mothership/start/options.go
  cmd/mothership/mothership/start/scheduler.go
Labels: lgtm, size/S

#958 Log applied IstioOperator yaml in case of error
  internal/persistency/registry.go
  pkg/features/features.go
  pkg/features/features_test.go
  pkg/metrics/metrics.go
  pkg/reconciler/instances/istio/istioctl/commander.go
  pkg/scheduler/service/run.go
Labels: size/M, lgtm, area/security

#968 Adjust hydra syncer on evaluation profile
  pkg/reconciler/instances/ory/hydra/syncer.go
  pkg/reconciler/instances/ory/hydra/syncer_test.go
Labels: size/M, lgtm, area/api-gateway

#976 Adjust log levels in istio and ory reconcilers
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/bootstrap.go
  pkg/reconciler/instances/istio/istioctl/commander.go
  pkg/reconciler/instances/istio/reset/pod/handler.go
  pkg/reconciler/instances/istio/reset/proxy/proxy.go
  pkg/reconciler/instances/istio/reset/proxy/proxy_test.go
  pkg/reconciler/instances/istio/tests/integration_test.go
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/ory/db/db.go
Labels: lgtm, size/L, area/api-gateway, area/service-mesh, area/security

#978 add plan_name in reconciler_metrics
  pkg/metrics/reconciliation_status.go
Labels: lgtm, size/XS

#974 Adjust info level logs
  pkg/reconciler/service/runner.go
  pkg/scheduler/invoker/remoteinvoker.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/service/bookkeepingtask.go
  pkg/scheduler/service/cleaner.go
  pkg/scheduler/service/inventorywatch.go
  pkg/scheduler/service/scheduler.go
  pkg/scheduler/service/transition.go
  pkg/scheduler/worker/workerpool.go
Labels: lgtm, size/S

#981 Fix: Race condition in occupancy tracker for component reconcilers
  pkg/reconciler/service/occupancytracker.go
Labels: lgtm, size/XS
