Repository kyma-incubator/reconciler, pull requests merged in 2022-10, with the labels that each got.

#1193 Unregister conversion webhooks at Kyma cleanup
  pkg/reconciler/instances/cleaner/pkg/cleanup/crd.go
  pkg/reconciler/instances/cleaner/pkg/cleanup/crd_test.go
  pkg/reconciler/instances/cleaner/pkg/cleanup/test/test-crd-with-conversion.yaml
Labels: lgtm, size/L

#1196 Upgrade golang to 1.19.2
  Dockerfile.cr
  Dockerfile.mr
Labels: lgtm, size/XS

#1202 update go-restful version CVE-2022-1996
  go.mod
  go.sum
Labels: lgtm, size/XS

#1204 Update golang.org/x/text version to v0.3.8
  go.mod
  go.sum
Labels: lgtm, size/S

#1205 Remove eventing pre action
  go.mod
  pkg/reconciler/instances/eventing/preaction/cleanupDashboardConfigMaps.go
  pkg/reconciler/instances/eventing/preaction/cleanupDashboardConfigMaps_test.go
  pkg/reconciler/instances/eventing/preaction/common.go
  pkg/reconciler/instances/eventing/preaction/handletogglejsfilestorage.go
  pkg/reconciler/instances/eventing/preaction/handletogglejsfilestorage_test.go
  pkg/reconciler/instances/eventing/preaction/preaction.go
Labels: size/XL, lgtm

#1214 Remove janmedrek from the Connectivity reconciler CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/XS

#1215 Remove kwiatekus from default owners of reconciler
  CODEOWNERS
Labels: lgtm, size/XS

#1216 Remove myself from owners
  CODEOWNERS
Labels: lgtm, size/XS

#1217 Remove varbanv and invalid users from codeowners
  CODEOWNERS
Labels: lgtm, size/XS

#1209 Adding sslMode and sslRootCert for db connections
  configs/reconciler-unittest.yaml
  configs/reconciler.yaml
  pkg/db/container_test_suite.go
  pkg/db/factory.go
  pkg/db/postgres.go
  pkg/db/postgres_container_runtime.go
  pkg/db/transaction_aware_database_container_test_suite_test.go
Labels: size/M, lgtm

#1218 Added default value for sslMode and sslRootCert control
  pkg/db/postgres.go
Labels: lgtm, size/S, ok-to-test
