Repository kyma-incubator/reconciler, pull requests merged in 2023-04, with the labels that each got.

#1317 Refresh connectivity proxy credentials
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
  pkg/reconciler/instances/connectivityproxy/command.go
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/instances/connectivityproxy/connectivityclient/connectivityclient.go
  pkg/reconciler/instances/connectivityproxy/connectivityclient/connectivityclient_test.go
  pkg/reconciler/instances/connectivityproxy/connectivityclient/mocks/connectivity_client.go
  pkg/reconciler/instances/connectivityproxy/connectivityproxy.go
  pkg/reconciler/instances/connectivityproxy/connectivityproxy_test.go
  pkg/reconciler/instances/connectivityproxy/fromsecret.go
  pkg/reconciler/instances/connectivityproxy/fromsecret_test.go
  pkg/reconciler/instances/connectivityproxy/fromurl.go
  pkg/reconciler/instances/connectivityproxy/fromurl_test.go
  pkg/reconciler/instances/connectivityproxy/loader.go
  pkg/reconciler/instances/connectivityproxy/loader_test.go
  pkg/reconciler/instances/connectivityproxy/map.go
  pkg/reconciler/instances/connectivityproxy/map_test.go
  pkg/reconciler/instances/connectivityproxy/mocks/commands.go
  pkg/reconciler/instances/connectivityproxy/mocks/loader.go
  pkg/reconciler/instances/connectivityproxy/rendering/chartproviderwithauthentication.go
  pkg/reconciler/instances/connectivityproxy/rendering/chartproviderwithauthentication_test.go
  pkg/reconciler/instances/connectivityproxy/rendering/chartproviderwithfiltering_test.go
  pkg/reconciler/instances/connectivityproxy/rendering/manifestfilters.go
  pkg/reconciler/instances/connectivityproxy/rendering/manifestfilters_test.go
  pkg/reconciler/instances/connectivityproxy/secretcopy.go
  pkg/reconciler/instances/connectivityproxy/secretcopy_test.go
  pkg/reconciler/instances/connectivityproxy/secrets/secrets.go
  pkg/reconciler/instances/connectivityproxy/secrets/secrets_test.go
Labels: size/XXL, lgtm

#1331 Enable lint target
  .golangci.yml
  Makefile
  cmd/mothership/config/create/cmd.go
  cmd/mothership/config/get/value/cmd.go
  cmd/mothership/mothership/start/http.go
  internal/cli/reconciler/options.go
  pkg/db/sqlite.go
  pkg/interpreter/yaegi.go
  pkg/reconciler/chart/factory.go
  pkg/reconciler/instances/cleaner/pkg/cleanup/cli.go
  pkg/reconciler/instances/eventing/preaction/handlenatspodmanagementpolicy.go
  pkg/reconciler/instances/istio/merge/merge.go
  pkg/reconciler/instances/istio/reset/pod/reset/action.go
  pkg/reconciler/service/clusterwideresourceinterceptor.go
  pkg/scheduler/reconciliation/inmemory.go
  scripts/lint.sh
Labels: lgtm, size/L, area/security

#1336 Check if Istio was successful installed more resilient (retries)
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_test.go
Labels: size/M, lgtm, area/security

#1337 Connectivity-proxy reconciler: Adding support for nested JSON in binding credential secret when spec.secretRootKey is set
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
  pkg/reconciler/instances/connectivityproxy/command.go
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/instances/connectivityproxy/loader.go
Labels: size/M, lgtm

#1341 Remove docker registry path override
  pkg/reconciler/instances/serverless/action.go
  pkg/reconciler/instances/serverless/action_test.go
Labels: lgtm, size/S
