Repository kyma-incubator/reconciler, pull requests merged in 2023-03, with the labels that each got.

#1300 Fix security vulnerabilities
  go.mod
  go.sum
Labels: lgtm, size/L

#1301 Improve error handling of istioctl invocations
  pkg/reconciler/instances/istio/istioctl/executor/cmd_executor.go
Labels: lgtm, size/S, area/security

#1304 Report only 'storage: true' version in findCRDsByLabel() function
  pkg/reconciler/instances/cleaner/pkg/cleanup/crd.go
Labels: lgtm, size/S

#1308 Adapt code owners
  CODEOWNERS
Labels: lgtm, size/XS

#1307 Istio reconciler reset proxy more resielient, verify Istio install
  go.mod
  go.sum
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/action_test.go
  pkg/reconciler/instances/istio/actions/mocks/istio_performer.go
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/actions/performer_ig_test.go
  pkg/reconciler/instances/istio/actions/performer_test.go
  pkg/reconciler/instances/istio/bootstrap.go
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/instances/istio/istio_test.go
  pkg/reconciler/instances/istio/istioctl/commander_test.go
  pkg/reconciler/instances/istio/istioctl/resolver.go
  pkg/reconciler/instances/istio/reset/data/gatherer.go
  pkg/reconciler/instances/istio/reset/data/gatherer_test.go
  pkg/reconciler/instances/istio/reset/data/mocks/Gatherer.go
Labels: size/XXL, lgtm, area/security

#1310 Update integration_action.go, integration_action_test.go, configmap.yaml, values.yaml
  pkg/reconciler/instances/rma/integration_action.go
  pkg/reconciler/instances/rma/integration_action_test.go
  pkg/reconciler/instances/rma/testdata/templates/configmap.yaml
  pkg/reconciler/instances/rma/testdata/values.yaml
Labels: lgtm, size/S

#1314 Bump Istio to 1.17.1
  Dockerfile.cr
Labels: lgtm, size/XS

#1313 use jellyfish team as default code owner
  CODEOWNERS
Labels: lgtm, size/XS

#1311 Clean up duplicated webhooks when istioctl fails
  go.mod
  go.sum
  pkg/reconciler/instances/istio/actions/performer.go
  pkg/reconciler/instances/istio/webhooks/webhooks.go
  pkg/reconciler/instances/istio/webhooks/webhooks_test.go
Labels: lgtm, size/L, area/security

#1321 Use Istio 1.16.3 in reconciler
  Dockerfile.cr
Labels: lgtm, size/XS

#1325 Fix test with race-condition & disable lint script temporarily
  pkg/reconciler/git/clone_test.go
  scripts/lint.sh
Labels: lgtm, size/S
