Repository kyma-incubator/reconciler, pull requests merged in 2023-08, with the labels that each got.

#1381 Allow expanded pvc reconciliations
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/service/install.go
  pkg/reconciler/service/pvcinterceptor.go
  pkg/reconciler/service/pvcinterceptor_test.go
  pkg/reconciler/service/test/pvcinterceptor-pvc.yaml
  pkg/reconciler/service/test/pvcinterceptor-sfs.yaml
Labels: kind/bug, lgtm, size/L, area/control-plane

#1385 Edit code owners
  CODEOWNERS
Labels: lgtm, size/XS

#1389 remove sap-btp-service-operator from test
  cmd/reconciler/start/service/component_integration_test.go
Labels: lgtm, size/S
