Repository kyma-incubator/reconciler, pull requests merged in 2023-01, with the labels that each got.

#1274 Sync finalizers for OAuth2Client resources
  pkg/reconciler/service/install.go
Labels: lgtm, size/XS

#1276 chore: bump image alpine and golang patches to 1.19.4-alpine3.17
  Dockerfile.cr
  Dockerfile.mr
Labels: lgtm, size/XS

#1275 chore: remove vulnerable go yaml lib in istio reconciler
  go.mod
  go.sum
  pkg/reconciler/instances/istio/ingress-gateway/config.go
Labels: lgtm, size/XS, area/security

#1280 Fix security vulnerabilites
  Makefile
  go.mod
  go.sum
Labels: lgtm, size/L

#1285 Removal of the dependencies to kyma-integration Namespace
  pkg/reconciler/instances/cleaner/action.go
Labels: lgtm, size/XS, area/reconciler

#1286 Remove PodPreset related code
  pkg/reconciler/instances/clusteressentials/action.go
  pkg/reconciler/instances/clusteressentials/action_test.go
  pkg/reconciler/instances/clusteressentials/clusteressentials.go
  pkg/reconciler/instances/loader.go
Labels: lgtm, size/L
