Repository kyma-incubator/reconciler, pull requests merged in 2023-02, with the labels that each got.

#1289 Update istio to 1.16.2 and remove 1.14
  Dockerfile.cr
Labels: lgtm, size/XS

#1290 Trivial cluster-essentials reconciler
  pkg/reconciler/instances/clusteressentials/action.go
  pkg/reconciler/instances/clusteressentials/clusteressentials.go
  pkg/reconciler/instances/loader.go
Labels: size/M, lgtm

#1287 Added eventing reconciler and added a pre-action
  CODEOWNERS
  cmd/mothership/mothership/start/mothership_integration_helpers_test.go
  cmd/reconciler/start/service/component_integration_test.go
  configs/reconciler.yaml
  go.mod
  pkg/reconciler/instances/eventing/action/action.go
  pkg/reconciler/instances/eventing/action/step.go
  pkg/reconciler/instances/eventing/eventing.go
  pkg/reconciler/instances/eventing/eventing_test.go
  pkg/reconciler/instances/eventing/log/log.go
  pkg/reconciler/instances/eventing/postaction/postaction.go
  pkg/reconciler/instances/eventing/preaction/common.go
  pkg/reconciler/instances/eventing/preaction/handlenatspodmanagementpolicy.go
  pkg/reconciler/instances/eventing/preaction/handlenatspodmanagementpolicy_test.go
  pkg/reconciler/instances/eventing/preaction/preaction.go
  pkg/reconciler/instances/loader.go
Labels: size/XL, lgtm

#1296 CRD filter by 'storage==true'
  pkg/reconciler/instances/cleaner/action.go
Labels: lgtm, size/S
