Repository kyma-incubator/reconciler, pull requests merged in 2023-05, with the labels that each got.

#1345 Ignore a component if the lookup failed
  pkg/model/clusterconfigentity.go
Labels: lgtm, size/XS

#1347 Do not return reconciliation error if binding secret is missing
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
  pkg/reconciler/instances/connectivityproxy/loader.go
Labels: lgtm, size/S

#1349 Support service mapping part1
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
  pkg/reconciler/instances/connectivityproxy/command.go
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/instances/connectivityproxy/mocks/commands.go
  pkg/reconciler/instances/connectivityproxy/secrets/secrets.go
  pkg/reconciler/instances/connectivityproxy/secrets/secrets_test.go
  pkg/ssl/create_certificate.go
  pkg/ssl/create_certificate_test.go
Labels: lgtm, size/L
