Repository kyma-incubator/reconciler, pull requests merged in 2023-12, with the labels that each got.

#1411 Clean up after modularizing api-gateway
  Makefile
  go.mod
  go.sum
  pkg/reconciler/instances/clusteressentials/action.go
  pkg/reconciler/instances/clusteressentials/clusteressentials.go
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/ory/action.go
  pkg/reconciler/instances/ory/action_test.go
  pkg/reconciler/instances/ory/db/db.go
  pkg/reconciler/instances/ory/db/db_test.go
  pkg/reconciler/instances/ory/db/model.go
  pkg/reconciler/instances/ory/deprecation/namespace.go
  pkg/reconciler/instances/ory/hydra/mocks/syncer.go
  pkg/reconciler/instances/ory/hydra/syncer.go
  pkg/reconciler/instances/ory/hydra/syncer_test.go
  pkg/reconciler/instances/ory/jwks/jwks.go
  pkg/reconciler/instances/ory/jwks/jwks_test.go
  pkg/reconciler/instances/ory/k8s/mocks/ory_finalizers_handler.go
  pkg/reconciler/instances/ory/k8s/mocks/rollout.go
  pkg/reconciler/instances/ory/k8s/ory_crds.go
  pkg/reconciler/instances/ory/k8s/rollout.go
  pkg/reconciler/instances/ory/ory.go
  pkg/reconciler/instances/ory/test/helpers.go
  pkg/reconciler/instances/ory/test/ory_integration_test.go
  pkg/reconciler/instances/ory/test/resources/test-ory/Chart.yaml
  pkg/reconciler/instances/ory/test/resources/test-ory/profile.yaml
  pkg/reconciler/instances/ory/test/resources/test-ory/values.yaml
Labels: size/XXL, lgtm, cla: yes

#1403 Skip reconcile when Istio CRDs are missing
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
Labels: lgtm, size/L, cla: yes

#1414 Remove fast integration tests
  scripts/prow/cli-integration-latest.sh
  scripts/prow/cli-integration-release-upgrade.sh
  scripts/prow/cli-integration.sh
Labels: lgtm, size/XS, cla: yes

#1406 Get kubeconfig from secret
  pkg/cluster/inventory.go
Labels: size/M, lgtm, cla: yes

#1415 Remove Istio
  CODEOWNERS
  configs/reconciler.yaml
  go.mod
  go.sum
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/instances/istio/OWNERS
  pkg/reconciler/instances/istio/README.md
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/actions/aggregate_action.go
  pkg/reconciler/instances/istio/actions/aggregate_action_test.go
  pkg/reconciler/instances/istio/get/get.go
  pkg/reconciler/instances/istio/get/get_test.go
  pkg/reconciler/instances/istio/get/istio-default-cr.yaml
  pkg/reconciler/instances/istio/get/istio-manager.yaml
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/instances/istio/tests/helpers.go
  pkg/reconciler/instances/loader.go
Labels: size/XXL, lgtm, area/security, cla: yes

#1419 Fix for Istio checks
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
Labels: lgtm, size/S, cla: yes

#1416 fix: Remove error on empty component list
  pkg/cluster/inventory.go
  pkg/scheduler/reconciliation/error.go
  pkg/scheduler/reconciliation/inmemory.go
  pkg/scheduler/reconciliation/persistent.go
  pkg/scheduler/service/transition.go
Labels: lgtm, size/L, cla: yes

#1424 allow empty precomponent
  pkg/scheduler/config/config.go
Labels: lgtm, size/XS, cla: yes

#1427 Upgrade golang:1.21.5-alpine3.19
  Dockerfile.cr
  Dockerfile.mr
Labels: lgtm, size/XS, cla: yes
