Repository kyma-incubator/reconciler, pull requests merged in 2023-06, with the labels that each got.

#1350 Support service mapping part2
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
  pkg/reconciler/instances/connectivityproxy/command.go
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/instances/connectivityproxy/configmaps/repository.go
  pkg/reconciler/instances/connectivityproxy/configmaps/repository_test.go
  pkg/reconciler/instances/connectivityproxy/mocks/commands.go
Labels: lgtm, size/L

#1354 Remove istioctl 1.16.3 from Reconciler image
  Dockerfile.cr
Labels: lgtm, size/XS

#1357 Bump go-git CVE-2023-1732
  go.mod
  go.sum
Labels: lgtm, size/L

#1355 Adapt connectivity-proxy reconciler to version 2.9.2
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
  pkg/reconciler/instances/connectivityproxy/btp_types.go
  pkg/reconciler/instances/connectivityproxy/command.go
  pkg/reconciler/instances/connectivityproxy/command_test.go
  pkg/reconciler/instances/connectivityproxy/connectivityproxy_test.go
  pkg/reconciler/instances/connectivityproxy/mocks/commands.go
  pkg/reconciler/instances/connectivityproxy/mocks/loader.go
  pkg/reconciler/instances/connectivityproxy/secrets/secrets.go
  pkg/reconciler/instances/connectivityproxy/secrets/secrets_test.go
  pkg/reconciler/instances/connectivityproxy/types.go
  pkg/reconciler/instances/connectivityproxy/types_test.go
Labels: size/XL, lgtm, area/connectivity-proxy

#1351 Add warden label to the istio-system namespace
  pkg/reconciler/service/nsinterceptor.go
Labels: lgtm, size/XS

#1360 Bump Istio to 1.18 in image
  Dockerfile.cr
Labels: lgtm, size/XS

#1359 Resolve node port conflict for internal docker registrey
  pkg/reconciler/instances/serverless/aggregate_action.go
  pkg/reconciler/instances/serverless/docker_registry.go
  pkg/reconciler/instances/serverless/docker_registry_test.go
  pkg/reconciler/instances/serverless/nodeport.go
  pkg/reconciler/instances/serverless/nodeport_test.go
  pkg/reconciler/instances/serverless/serverless.go
  pkg/reconciler/instances/serverless/utils_test.go
Labels: lgtm, size/L

#1361 Remove istioctl 1.17.2 from reconciler
  Dockerfile.cr
Labels: lgtm, size/XS

#1365 Fix for loadbalancer detection for empty node port
  pkg/reconciler/instances/serverless/nodeport.go
  pkg/reconciler/instances/serverless/nodeport_test.go
Labels: size/M, lgtm

#1369 Fix for generated too long common name in connectivity-proxy istio certificate
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
  pkg/reconciler/instances/connectivityproxy/command.go
  pkg/reconciler/instances/connectivityproxy/configmaps/repository.go
  pkg/reconciler/instances/connectivityproxy/configmaps/repository_test.go
  pkg/reconciler/instances/connectivityproxy/mocks/commands.go
Labels: lgtm, size/L

#1368 Extend list of code owners of connectivity-proxy-reconciler to all Framefrog team members
  CODEOWNERS
Labels: lgtm, size/XS

#1367 Ignore ISTIO CRDs if migrated CRD could be found on target cluster
  pkg/reconciler/chart/mocks/provider.go
  pkg/reconciler/chart/provider.go
  pkg/reconciler/chart/provider_test.go
  pkg/reconciler/instances/connectivityproxy/rendering/chartproviderwithauthentication.go
  pkg/reconciler/instances/connectivityproxy/rendering/chartproviderwithfiltering_test.go
  pkg/reconciler/service/install.go
Labels: lgtm, size/L

#1370 Remove api prefix from the tunnel's URL
  pkg/reconciler/instances/connectivityproxy/action.go
  pkg/reconciler/instances/connectivityproxy/action_test.go
  pkg/reconciler/instances/connectivityproxy/command.go
  pkg/reconciler/instances/connectivityproxy/configmaps/repository.go
  pkg/reconciler/instances/connectivityproxy/configmaps/repository_test.go
  pkg/reconciler/instances/connectivityproxy/mocks/commands.go
Labels: lgtm, size/L

#1348 Implement post action
  pkg/reconciler/instances/serverless/docker_registry.go
  pkg/reconciler/instances/serverless/istiocleanup.go
  pkg/reconciler/instances/serverless/istiocleanup_test.go
  pkg/reconciler/instances/serverless/serverless.go
Labels: lgtm, size/L
