Repository kyma-incubator/reconciler, pull requests merged in 2023-07, with the labels that each got.

#1374 Update Dockerfile.cr with 1.18.1 istio image
  Dockerfile.cr
Labels: lgtm, size/XS

#1372 Add scripts for Jellyfish prow jobs
  scripts/prow/cli-integration-latest.sh
  scripts/prow/cli-integration-release-upgrade.sh
  scripts/prow/cli-integration.sh
  scripts/prow/reconciler-integration.sh
Labels: size/M, lgtm

#1375 Apply bootstrap EnvoyFilter before proxy reset
  go.mod
  pkg/reconciler/instances/istio/action.go
  pkg/reconciler/instances/istio/clientset/provider.go
  pkg/reconciler/instances/istio/envoy/envoy_action.go
  pkg/reconciler/instances/istio/envoy/envoy_action_test.go
  pkg/reconciler/instances/istio/istio.go
  pkg/reconciler/service/hpainterceptor.go
  pkg/reconciler/service/test/hpainterceptor.yaml
Labels: lgtm, size/L, area/security

#1377 Skip components by env-var
  pkg/model/clusterconfigentity.go
  pkg/model/clusterconfigentity_test.go
Labels: lgtm, size/S

#1378 Update Dockerfile.cr with Istio 1.18.2
  Dockerfile.cr
Labels: lgtm, size/XS
