Repository kyma-incubator/reconciler, pull requests merged in 2024-01, with the labels that each got.

#1428 chore: Upgrade build image
  Dockerfile.cr
  Dockerfile.mr
Labels: lgtm, size/XS, cla: yes

#1429 Add missing kubeconfig overwrites
  pkg/cluster/inventory.go
Labels: size/M, lgtm, cla: yes

#1433 feat: Cache Kubeconfigs
  cmd/reconciler/test/service/cmd.go
  go.mod
  go.sum
  pkg/cache/kubeConfig.go
  pkg/cluster/inventory.go
  pkg/db/transaction.go
  pkg/reconciler/instances/rma/integration_action.go
Labels: lgtm, size/L, cla: yes

#1434 Fix cache lookup NPE error
  pkg/cache/kubeConfig.go
  pkg/cluster/inventory.go
Labels: size/M, lgtm, release blocker, cla: yes

#1435 Upgrade k8s to 1.29.1
  go.mod
  go.sum
  pkg/reconciler/kubernetes/simplerestclientgetter.go
Labels: lgtm, size/L, cla: yes

#1436 Fix vulnerabilities
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes

#1439 Have configurable TTL for KubeConfig cache
  pkg/cache/kubeConfig.go
Labels: size/M, lgtm, cla: yes

#1441 Don't fail if kubeconfig cannot be found
  pkg/cache/kubeConfig.go
Labels: lgtm, size/XS, cla: yes

#1442 Cache also nonexisting kubeconfigs
  pkg/cache/kubeConfig.go
Labels: lgtm, size/S, cla: yes

#1443 Reduce log noise
  pkg/cache/kubeConfig.go
  pkg/cluster/inventory.go
Labels: lgtm, size/S, cla: yes

#1445 Introduce jitter ttl
  pkg/cache/kubeConfig.go
  pkg/cache/kubecConfig_test.go
Labels: lgtm, size/S, cla: yes

#1446 Enhance jitter
  pkg/cache/kubeConfig.go
  pkg/cache/kubecConfig_test.go
Labels: lgtm, size/S, cla: yes

#1449 Connectivity Proxy reconciller with enhanced logging
  pkg/reconciler/instances/connectivityproxy/action.go
Labels: size/M, lgtm, cla: yes

#1448 Warden volume mount cleanup reconciler
  pkg/reconciler/instances/loader.go
  pkg/reconciler/instances/warden/volumemounts.go
  pkg/reconciler/instances/warden/volumemounts_test.go
  pkg/reconciler/instances/warden/warden.go
Labels: size/XL, lgtm, cla: yes
